### ISSUE TITLE
Start vttablets-- we are getting in error

### ISSUE THREAD

**Issue by muthusamyshivaraman** [youtube/vitess#1071]
Hi 
 I have installed Vitess, based on "Run Vitess Locally" and we faced the issue on 05-Start vttablets on this. 
Error message:
vuser@ubuntu:~/Vitess_Ubuntu/vitess/examples/local$ ./vttablet-up.sh
Starting MySQL for tablet test-0000000100...
./vttablet-up.sh: line 81: /home/vuser/Vitess_Ubuntu/vitess/bin/mysqlctl: No such file or directory

**Comment by enisoc** [comment]
Did `make build` fully succeed? It should have built `mysqlctl` and put it in that location. What are the contents of `/home/vuser/Vitess_Ubuntu/vitess/bin/`?

**Comment by muthusamyshivaraman** [comment]
Hi, I have added this content, Kindly verify. thanks. 
/home/vuser/Vitess_Ubuntu/vitess/bin
vuser@ubuntu:~/Vitess_Ubuntu/vitess/bin$ ls -ltr
total 43632
-rwxr-xr-x 1 vuser vuser 6312520 Sep  1 14:59 golint
-rwxr-xr-x 1 vuser vuser 5333808 Sep  1 14:59 protoc-gen-go
-rwxr-xr-x 1 vuser vuser 9932168 Sep  1 14:59 godep
-rwxr-xr-x 1 vuser vuser 5254296 Sep  1 14:59 goimports
-rwxr-xr-x 1 vuser vuser 3233272 Sep  1 14:59 gover
-rwxr-xr-x 1 vuser vuser 8544440 Sep  1 14:59 goveralls
-rwxr-xr-x 1 vuser vuser 6050008 Sep  1 14:59 cover
lrwxrwxrwx 1 vuser vuser      53 Sep  1 14:59 zksrv.sh -> /home/vuser/Vitess_Ubuntu/vitess/go/zk/zkctl/zksrv.sh
vuser@ubuntu:~/Vitess_Ubuntu/vitess/bin$

**Comment by enisoc** [comment]
Based on this line:

```
lrwxrwxrwx 1 vuser vuser 53 Sep 1 14:59 zksrv.sh -> /home/vuser/Vitess_Ubuntu/vitess/go/zk/zkctl/zksrv.sh
```

It looks like you cloned the vitess repo into `~/Vitess_Ubuntu/vitess`. I think this is why the binaries didn't build correctly. Due to the way the Go build tool works, we need the vitess repo to be cloned into a directory tree that matches the Go package path (`src/github.com/youtube/vitess`), like this:

```
git clone https://github.com/youtube/vitess.git /home/vuser/Vitess_Ubuntu/src/github.com/youtube/vitess
cd /home/vuser/Vitess_Ubuntu/src/github.com/youtube/vitess
./bootstrap.sh
source dev.env
make build
```

**Comment by muthusamyshivaraman** [comment]
the content only , I have to create /youtube/vitess folder inside github.com....
Please find the folder structure in below.  

vuser@ubuntu:~/Vitess_Ubuntu/vitess/src/github.com$ ll
total 32
drwxrwxr-x 8 vuser vuser 4096 Sep  2 10:07 ./
drwxrwxr-x 6 vuser vuser 4096 Sep  1 14:59 ../
drwxrwxr-x 3 vuser vuser 4096 Sep  1 14:59 bradfitz/
drwxrwxr-x 5 vuser vuser 4096 Sep  1 14:58 golang/
drwxrwxr-x 3 vuser vuser 4096 Sep  1 14:59 mattn/
drwxrwxr-x 3 vuser vuser 4096 Sep  1 14:59 modocache/
drwxrwxr-x 3 vuser vuser 4096 Sep  1 14:59 pborman/
drwxrwxr-x 3 vuser vuser 4096 Sep  1 14:58 tools/
vuser@ubuntu:~/Vitess_Ubuntu/vitess/src/github.com$

**Comment by enisoc** [comment]
Yes, you should create the `youtube/vitess` folder within that `github.com` folder and put the contents cloned from our git repository.

This command should do that in one step:

```
git clone https://github.com/youtube/vitess.git /home/vuser/Vitess_Ubuntu/src/github.com/youtube/vitess
```

**Comment by muthusamyshivaraman** [comment]
after this , I have started .. ./bootstrap.sh

it shows 
vuser@ubuntu:~/Vitess_Ubuntu/src/github.com/youtube/vitess$ ./bootstrap.sh
skipping zookeeper build. remove /home/vuser/Vitess_Ubuntu/vitess/dist/vt-zookeeper-3.3.5 to force rebuild.
skipping protobuf build. remove /home/vuser/Vitess_Ubuntu/vitess/dist/protobuf to force rebuild.
skipping gRPC build. remove /home/vuser/Vitess_Ubuntu/vitess/dist/grpc to force rebuild.
can't load package: package launchpad.net/gozk/zookeeper: cannot find package "launchpad.net/gozk/zookeeper" in any of:
        /usr/local/go/src/launchpad.net/gozk/zookeeper (from $GOROOT)
        /home/vuser/Vitess_Ubuntu/vitess/src/launchpad.net/gozk/zookeeper (from $GOPATH)
Found MySQL 5.6 installation in /usr.
Cannot execute /usr/bin/mysql_config. Did you install a client dev package?

**Comment by muthusamyshivaraman** [comment]
I think I have start new server.. based on your input..

**Comment by enisoc** [comment]
Yeah, starting over with an empty directory in the right directory structure might help with the zookeeper error.

Also, at the end it looks like it can't find `mysql_config`. This command is only installed when you install the `libmysqlclient-dev` package, which we need to build Vitess.

**Comment by muthusamyshivaraman** [comment]
Hello, 
I am facing the issue on execute etcd file. 

-----------------
vuser@ubuntu:~/etcd-v2.2.0-rc.0-darwin-amd64$ pwd
/home/vuser/etcd-v2.2.0-rc.0-darwin-amd64
vuser@ubuntu:~/etcd-v2.2.0-rc.0-darwin-amd64$ ll
total 27428
drwxr-xr-x 3 root  root      4096 Aug 28 10:36 ./
drwxr-xr-x 5 vuser vuser     4096 Sep  2 12:06 ../
drwxr-xr-x 5 root  root      4096 Aug 28 10:36 Documentation/
-rwxr-xr-x 1 root  root  14987344 Aug 28 10:36 etcd*
-rwxr-xr-x 1 root  root  13063856 Aug 28 10:36 etcdctl*
-rw-r--r-- 1 root  root      5581 Aug 28 10:36 README-etcdctl.md
-rw-r--r-- 1 root  root      4668 Aug 28 10:36 README.md
vuser@ubuntu:~/etcd-v2.2.0-rc.0-darwin-amd64$ ./etcd
-bash: ./etcd: cannot execute binary file: Exec format error
vuser@ubuntu:~/etcd-v2.2.0-rc.0-darwin-amd64$

**Comment by enisoc** [comment]
It looks like you downloaded the OS X binary (labeled `darwin`) for etcd, rather than the Linux binary.

**Comment by muthusamyshivaraman** [comment]
Yes. sorry..

**Comment by muthusamyshivaraman** [comment]
Hi
1.  git clone https://github.com/youtube/vitess.git src/github.com/youtube/vitess
Cloning into 'src/github.com/youtube/vitess'...
remote: Counting objects: 60877, done.
remote: Compressing objects: 100% (135/135), done.
remote: Total 60877 (delta 58), reused 0 (delta 0), pack-reused 60740
Receiving objects: 100% (60877/60877), 47.90 MiB | 1.14 MiB/s, done.
Resolving deltas: 100% (43716/43716), done.
Checking connectivity... done.
2. I have set the path also. 
   export MYSQL_FLAVOR=MySQL56

3. I have verified database, db installed /usr/bin folder only. 

4. I have started  bootstrap.sh
vuser@ubuntu:~/vitess/src/github.com/youtube/vitess$ ./bootstrap.sh
I am getting error here. 
go: cannot find GOROOT directory: /home/vuser/go
Go is not installed or is not on $PATH
----------------------------------------------------------------------------------------
I have update the path here..
vuser@ubuntu:~/vitess/src/github.com/youtube/vitess$ find *.sh
bootstrap.sh
preview-site.sh
publish-site.sh
vuser@ubuntu:~/vitess/src/github.com/youtube/vitess$ find . -name go
./third_party/go
./go

Kindly help on this.

**Comment by enisoc** [comment]
Can you show the output from these:

```
which go
go env
```

**Comment by muthusamyshivaraman** [comment]
vuser@ubuntu:~/vitess/src/github.com/youtube/vitess$ which go
/usr/local/go/bin/go
vuser@ubuntu:~/vitess/src/github.com/youtube/vitess$ go env
go: cannot find GOROOT directory: /home/vuser/go
vuser@ubuntu:~/vitess/src/github.com/youtube/vitess$

**Comment by enisoc** [comment]
It looks like you are using Go installed in `/usr/local/go`, but your `GOROOT` is set as if you have Go installed in `/home/vuser/go`.

If you want to use the Go installed in `/usr/local/go`, you should set:

```
export GOROOT=/usr/local/go
```

**Comment by muthusamyshivaraman** [comment]
After i have start the make build comments.. i am getting this error, but cursor still not exits..
vuser@ubuntu:~/vitess/src/github.com/youtube/vitess$ . ./dev.env
vuser@ubuntu:~/vitess/src/github.com/youtube/vitess$ make build
Wed Sep 2 14:06:31 IST 2015: Building source tree
# pkg-config --cflags gomysql
Package gomysql was not found in the pkg-config search path.
Perhaps you should add the directory containing `gomysql.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gomysql' found
pkg-config: exit status 1

**Comment by muthusamyshivaraman** [comment]
godep: go exit status 2
make: *** [build] Error 1
vuser@ubuntu:~/vitess/src/github.com/youtube/vitess$

**Comment by muthusamyshivaraman** [comment]
I have installed all the software.. based on your instruction. but i got error on this stage..


vuser@ubuntu:~/vitess/src/github.com/youtube/vitess$ make build
Wed Sep 2 14:46:01 IST 2015: Building source tree
# pkg-config --cflags gomysql
Package gomysql was not found in the pkg-config search path.
Perhaps you should add the directory containing `gomysql.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gomysql' found
pkg-config: exit status 1
godep: go exit status 2
make: *** [build] Error 1
vuser@ubuntu:~/vitess/src/github.com/youtube/vitess$

**Comment by enisoc** [comment]
Make sure you have done `source dev.env` in the same shell, just before you run `make build`:

```
source dev.env
make build
```

This should set the `PKG_CONFIG_PATH` correctly for you.

If that still doesn't work, please show the following output to try to diagnose:

```
source dev.env
echo $PKG_CONFIG_PATH
ls -l $VTROOT/lib
```

**Comment by muthusamyshivaraman** [comment]
Hi
  Kindly help me on that.

**Comment by muthusamyshivaraman** [comment]
vuser@ubuntu:~/vitess/src/github.com/youtube/vitess$ source dev.env
vuser@ubuntu:~/vitess/src/github.com/youtube/vitess$ make build
Thu Sep 3 09:14:23 IST 2015: Building source tree
# pkg-config --cflags gomysql
Package gomysql was not found in the pkg-config search path.
Perhaps you should add the directory containing `gomysql.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gomysql' found
pkg-config: exit status 1
godep: go exit status 2
make: *** [build] Error 1
vuser@ubuntu:~/vitess/src/github.com/youtube/vitess$ source dev.env
vuser@ubuntu:~/vitess/src/github.com/youtube/vitess$ echo $PKG_CONFIG_PATH
/home/vuser/vitess/lib
vuser@ubuntu:~/vitess/src/github.com/youtube/vitess$ ls -l $VTROOT/lib
total 0
vuser@ubuntu:~/vitess/src/github.com/youtube/vitess$

**Comment by muthusamyshivaraman** [comment]
Thanks a lot boss:)
Server is up and running :)
Sorry for disturbing a lot :)

**Comment by muthusamyshivaraman** [comment]
Hi 
  I have created restored the database in MySQL, My Vitess also running successfully 
http://192.168.140.105:15000/app/#/vschema/

How I can access the database through this webpage. Kindly let me know.

**Comment by enisoc** [comment]
We don't currently provide web access to perform queries. If you want to test out some queries, you can use the command-line like this:

```
vtctlclient -server localhost:15000 VtGateExecuteShard -server localhost:15001 -keyspace test_keyspace -shards 0 -tablet_type replica 'SELECT * FROM test_table'
```
See the [command reference](http://vitess.io/reference/vtctl.html#queries) or run `vtctlclient -server localhost:15000 help` for more usage info.
