### ISSUE TITLE
one session multiple schema query support 

### ISSUE THREAD

**Issue by ChinaXing** [youtube/vitess#1310]
AS following query, the tow table in tow database/schema use the same sharding key, which will keep the  routing target hit the same shard.

#user connect to the vitess, than execute the following queries ...
```
use db1
select * from tb1 where kid = 12;
select * from db2.tb2 where kid =  12;
```

does the vitess support this query ?

if not, user must do this in two connection ?

**Comment by enisoc** [comment]
Those queries would work, assuming you have two databases in a single shard. It would only require one connection from your app to vtgate, which behind the scenes would use one connection from vtgate to vttablet.

However, by default we only create one database per shard. Usually if there are two tables that we want to have the same sharding scheme, we put them in the same database. Is there a use case you're considering that requires more than one database per shard?

As a side note, if you did have db1 and db2 as two different [keyspaces](http://vitess.io/overview/concepts.html#keyspace), you could still do both queries on a single connection from your app to vtgate. Behind the scenes, vtgate would use two connections to two different vttablets (one for each keyspace).

**Comment by ChinaXing** [comment]
ok.thank you
