### ISSUE TITLE
Kubernetes example inconsistency

### ISSUE THREAD

**Issue by zoidbergwill** [youtube/vitess#1359]
While going through the Kubernetes example, I noticed an inconsistency. I'd happily fix it, but I'm not sure which value they should both use. I see the change to defaulting to 0 nodes is more recent than the `default 3` in `advanced.md`.

`advanced.md`:
```
The cluster-up.sh script supports the following environment variables:

...
GKE_NUM_NODES - Number of nodes to use for the cluster (default 3).
...
```

`clusterup.sh`:
```sh
GKE_NUM_NODES=${GKE_NUM_NODES:-0}
```

**Comment by enisoc** [comment]
I think cluster-up.sh should be changed to default to 3. Looking at the history, it seems that GKE_NUM_NODES used to default to 3, then it was removed, then it was reintroduced with a default of 0 (probably by mistake).

Thanks for catching this!

**Comment by thompsonja** [comment]
Thanks for catching this!  Originally my thought process was to create a
GKE node for each vttablet/vtgate, so it was automatically calculated if
set to 0.  Then we decided to let k8s handle scheduling pods onto nodes
based on resource values, so there isn't necessarily a 1:1 ratio of nodes
to vttablet/vtgate jobs anymore.  I'll update the documentation and/or
update the default value to a sane value.

**Comment by thompsonja** [comment]
Since I split the process of starting a GKE cluster and starting Vitess on said cluster, it doesn't make sense to try to automatically deduce the number of nodes to use.  As such I updated the documentation to mark it as required.
