### ISSUE TITLE
PSR standards compliance

### ISSUE THREAD

**Issue by cyrrill** [youtube/vitess#1404]
The PHP client for Vitess is not following PSR standards, which makes its incorporation in other systems an issue:

There are no namespace declarations
Class loading is done via hardcoded includes rather than via a PSR-4 autoloader
There is more than one class per file. 

Nice to have: PHPDoc on code (PSR-5 draft)

**Comment by enisoc** [comment]
These are all great points. To be honest, I haven't touched PHP in 10+ years, so I'll need to read up on the standards. In the meantime, we would welcome any contributed fixes. We are still allowing breaking changes, so it should be straightforward.

If anyone plans to take a crack at this, please comment here so we don't duplicate effort.

Thanks!

**Comment by cyrrill** [comment]
The idea is that instead of having to do an include or require in every single file where you need to do an import, you can let a PSR autoloader do the work for you.

The autoloader leverages the namespace organization of classes. So for example, instead of doing this in the client code which loads Vitesse:

```
require_once ('../../php/src/VTGateConn.php');
```

You would do:

```
use Youtube\Vitess\VTGateCon;
```

The "use" keyword calls the autoloader in the background which knows where to find the specific file that contains the class and loads it into scope.

That's also why it's important to only have one class per file.


In order for this to work, the Vitess classes need to be put in files, and at the top of each class, a namespace declaration added:

```
<?php

namespace Youtube\Vitesse;

class VTGateCon
{
    (...)
```


The Vitesse composer.json file would then specify the namespaces the package contains, and where to find them in the filesystem. Effectively doing a mapping of disk directories to PHP Namespaces:

```
    "autoload": {
        "psr-4": {
            "Youtube\\Vitesse\\": "src/"
        }
    },
```


Here is a quick video that illustrates this:
https://www.youtube.com/watch?v=VGSerlMoIrY&t=3m15s


PHP has evolved tremendously in the last 10 years ;)

**Comment by cyrrill** [comment]
For reference, I've filed a separate bug report for the Protobuf classes, as they are autogenerated

https://github.com/drslump/Protobuf-PHP/issues/55

**Comment by Rastusik** [comment]
@enisoc I'm considering to do some of the cleanups if the #1438 will be approved.

**Comment by enisoc** [comment]
FYI I'm working on this now. @cyrrill you can close the bug on Protobuf-PHP. I found that they already have an option to put each class in its own file, and it seems to work.

**Comment by cyrrill** [comment]
Perfect, thanks @enisoc

**Comment by enisoc** [comment]
I think I addressed the major problems. Let me know (or send a pull request :) ) if you see anything else.

I'll have to make another pass later for the PHPDoc part. I need to work on the Java client some more before we cut beta.

Thanks for the great suggestions!
