### ISSUE TITLE
Tabletserver records incorrect timings for BEGIN, COMMIT and ROLLBACK

### ISSUE THREAD

**Issue by mattharden** [youtube/vitess#1412]
In go/vt/tabletserver/tabletserver.go, the Begin, Commit, and Rollback functions run

`tsv.qe.queryServiceStats.QueryStats.Record("xxx", time.Now())`

*inside* of a deferred function. The problem here is that time.Now won't get called until the deferred function is already running, so the SQL command will have already completed. We should either pass the start time into the deferred function, store it in a variable before the defer command, or separate out the defer for Record into its own statement like 

`defer tsv.qe.queryServiceStats.QueryStats.Record("xxx", time.Now())`

so that time.Now() will be called at defer time.

**Comment by sougou** [comment]
Nice catch. Would you like to send a fix? Something like this: https://github.com/youtube/vitess/blob/master/go/vt/tabletserver/query_executor.go#L147.
Otherwise, I'll get around to it when I can.

**Comment by mattharden** [comment]
Yes. Do I send the fix in via a Github pull request?
