### ISSUE TITLE
composer.json in the project root directory + packagist.org package

### ISSUE THREAD

**Issue by Rastusik** [youtube/vitess#1438]
To be able to use the PHP client with composer, it is mandatory to move the composer.json file from the /php folder into the project root folder. Is this permitted? I could do it myself. Other projects are having similar issues: composer/packagist#472

After doing this, it would be easier to contribute to the PHP client code, because I would be able to reference the repo directly from the projects I'm working on and I wouldn't need to make changes in a separate repository. 

It would be also nice to register a vitess-php-client package on packagist.org, so no one would be forced to manually insert the link to the vitess repository to composer.json file.

**Comment by enisoc** [comment]
Putting it in the root sounds fine to me. Feel free to send a pull request. Thanks!

**Comment by Rastusik** [comment]
and what about the official package?

**Comment by enisoc** [comment]
Sure, once the composer files are moved to the root, I'll publish it to packagist.org.

**Comment by Rastusik** [comment]
You can publicsh the package now :)

**Comment by enisoc** [comment]
https://packagist.org/packages/vitess/php-client

I installed the GitHub hook, but Packagist hasn't noticed yet. Perhaps it's because no pushes have occurred yet.

**Comment by Rastusik** [comment]
Looks good to me, it should be working, thank you veru much!
