### ISSUE TITLE
OSX examples/local/vttablet-up.sh

### ISSUE THREAD

**Issue by guillaumenel** [youtube/vitess#1449]
Is it time for OS-specific examples/local?
`hostname -i` in ./vttablet-up.sh doesn't work on OSX.

Update:
Replacing it with simply `hostname` does the trick. 

Error:
./vttablet-up.sh
Starting MySQL for tablet test-0000000100...
Starting vttablet for test-0000000100...
Access tablet test-0000000100 at http://macbook.local:15100/debug/status
Starting MySQL for tablet test-0000000101...
hostname: illegal option -- i

While it does appear to launch, when going this route, you can't call vttablet-down.sh example to tear them down again, which was a scary experience for a first time user.

./vttablet-down.sh 
Stopping vttablet for test-0000000100...
cat: /path/to/vt/vtdataroot/vt_0000000100/vttablet.pid: No such file or directory

After the Update, they tear down as they should.

**Comment by enisoc** [comment]
So far, the OS X support (contributed by @Rastusik) has been done by adding platform conditionals in each script as needed. If the changes are minor like the `hostname` flag example you gave, I think this approach is the simplest.

The main Vitess team doesn't do testing on OS X, but if you want to fix examples/local for OS X similar to #1428, we would welcome a pull request.

**Comment by Rastusik** [comment]
I made a pull request for this
