### ISSUE TITLE
Connect the repo to Reviewable

### ISSUE THREAD

**Issue by erzel** [youtube/vitess#1500]
Please connect this repo at https://reviewable.io/repositories#youtube so that all PRs get linked to reviews. Thanks!

**Comment by michael-berlin** [comment]
reviewable.io probably automatically created this for you ;-)

For now, we don't want to do this. Instead, just login on reviewable.io and select the pull request you want to comment on.

**Comment by erzel** [comment]
Oh I see. Sugu please disregard. You can just login to reviewable.io and
reply to my comments.
