### ISSUE TITLE
vtworker SplitClone command take a long time and never return.

### ISSUE THREAD

**Issue by helayzhang** [youtube/vitess#1537]
http://vitess.io/user-guide/horizontal-sharding.html#step-3-2-copy-data-from-source-shard-to-destination-shards

I'm using the example/local project, and try shard feature by following this guide.
Everything goes well until I do the 'Copy data' as step3.2,  I run this:

>vtworker -min_healthy_rdonly_endpoints 1 -cell=test SplitClone test_keyspace/0

The terminal wait and never return, with no print. My test db only has one table with 5 rows data, I wait for this more then 5 minutes.
If I press Ctrl+C to the vtworker progress, I will get this print then:

>E0301 22:07:04.260301   17754 healthcheck_wait.go:145] waitForEndPoints failed for map[{test_keyspace 0}:true] (context error: context canceled)
E0301 22:07:04.261328   17754 vtworker.go:81] findTargets() failed: FindWorkerTablet() failed for test/test_keyspace/0: error waiting for rdonly endpoints for (test,test_keyspace/0): waitForEndPoints failed for map[{test_keyspace 0}:true] (context error: context canceled)

Seems the vtworker is waiting for rdonly tablet。I list all tablets status, and got:

>$VTROOT/bin/vtctlclient -server localhost:15999 ListAllTablets test
test-0000000100 test_keyspace 0 master gim-server2:15100 gim-server2:33100 []
test-0000000101 test_keyspace 0 replica gim-server2:15101 gim-server2:33101 []
test-0000000102 test_keyspace 0 replica gim-server2:15102 gim-server2:33102 []
test-0000000200 test_keyspace -80 master gim-server2:15200 gim-server2:33200 []
test-0000000201 test_keyspace -80 rdonly gim-server2:15201 gim-server2:33201 []
test-0000000202 test_keyspace -80 rdonly gim-server2:15202 gim-server2:33202 []
test-0000000300 test_keyspace 80- master gim-server2:15300 gim-server2:33300 []
test-0000000301 test_keyspace 80- rdonly gim-server2:15301 gim-server2:33301 []
test-0000000302 test_keyspace 80- rdonly gim-server2:15302 gim-server2:33302 []

Seems no problems?

What can I do next or How can I get more debuging info by the vtworker?

**Comment by helayzhang** [comment]
Solved this problem, I manually change one of the replica tablet of source shard to rdonly status.
Then I'm able to SplitClone data. For SplitDiff is the same, I first manually make a rdonly tablet then SplitDiff.

>$VTROOT/bin/vtctlclient -server localhost:15999 ChangeSlaveType test-0000000101 rdonly
vtworker -min_healthy_rdonly_endpoints=1 -cell=test SplitClone test_keyspace/0

**Comment by enisoc** [comment]
Sorry for the slow response, but FYI the reason you always need a `rdonly` tablet on the source and destination when doing clone, diff, etc. is because `replica` tablets are assumed to be needed for serving live traffic. The `rdonly` tablets are reserved for batch processes and can be taken out of serving temporarily for clone and diff operations.

**Comment by michael-berlin** [comment]
Yes, the problem was that you didn't have any ```rdonly``` tablet in the source shard:

```
test-0000000100 test_keyspace 0 master gim-server2:15100 gim-server2:33100 []
test-0000000101 test_keyspace 0 replica gim-server2:15101 gim-server2:33101 []
test-0000000102 test_keyspace 0 replica gim-server2:15102 gim-server2:33102 []
```

vtworker was blocking infinitely waiting for at least 1 healthy rdonly tablet to show up (```-min_healthy_rdonly_endpoints=1```).

By changing a ```replica``` to an ```rdonly``` you made an ```rdonly``` tablet available in the source shard and the command worked.

Note: The fact that it was blocking infinitely is a bug in vtworker though. You should have seen an error after a timeout. I have a pending fix for that.

**Comment by helayzhang** [comment]
@enisoc @michael-berlin Thanks, I'm a newbie for using vitess, and your replies helps me understand more.

I have finished all of the 'Reshard' test now, and doing other testing on the sharded database. I try to insert new datas to new sharded database. Using the old V1 APIs, I've got this:

>exec failed: shard, host: test_keyspace.80-.master, uid:300 host:"gim-server2" port_map:<key:"grpc" value:16300 > port_map:<key:"mysql" value:33300 > port_map:<key:"vt" value:15300 > , vttablet: rpc error: code = 3 desc = "gRPCServerError: error: Query disallowed due to rule: enforce keyspace_id range for INSERT_PK"
exec failed: shard, host: test_keyspace.-80.master, uid:200 host:"gim-server2" port_map:<key:"grpc" value:16200 > port_map:<key:"mysql" value:33200 > port_map:<key:"vt" value:15200 > , vttablet: rpc error: code = 3 desc = "gRPCServerError: error: Query disallowed due to rule: enforce keyspace_id range for INSERT_PK"
exit status 1

keyspace_id of this new insert row is 12638131125462603235(0xAF63A94C860195E3).
As you see, no matter I choose "-80" or "80-" shard, the insert always fails.
So I have a look at the VTGateV3Features, and found V1 APIs are not suitable for a sharded database. App may faces the AUTO_INCRIMENT primary index and has to calc sharded keyspace_ids. 
In these pages: https://godoc.org/github.com/youtube/vitess/go/vt/vitessdriver
and https://github.com/youtube/vitess/blob/master/doc/VTGateV3Features.md

Am I right? As described alpha, will VTGateV3 APIs changes a lot in soon?

At last, I'm keep reading about VTGateV3, and it will be great if there is a V3 demo for Golang(not found yet:)).

**Comment by sougou** [comment]
It's a failsafe mechanism where we ensure that writes don't accidentally get sent to the wrong shard. For it to succeed, you need to send in a bind variable called "keyspace_id" that has the correct kespace id with each DML.
When you built your sharded keyspace, there was a place you needed to specify the sharding key. If you specified something other than keyspace_id there, then you need to send that bind var as the keyspace id.

As for the V3 questions: Yes, we'll support auto inc columns, and the inserts will get routed to the correct shards.

**Comment by helayzhang** [comment]
My test code(golang), modified by example/local/client.go

keyspace := "test_keyspace"
shard := "80-" // or "-80"
timeout := 10 * time.Second

// Connect to vtgate.
db, err := vitessdriver.OpenShard(*server, keyspace, shard, "master", timeout)
if err != nil {
    fmt.Printf("client error: %v\n", err)
    os.Exit(1)
}
defer db.Close()

tx, err := db.Begin()
if err != nil {
    fmt.Printf("begin failed: %v\n", err)
    os.Exit(1)
}
// Hard coded here, for I know next auto_increment primary key will be 4
// I use tohash(strconv.Itoa(id)) to be keyspace_id, which is type of uint64
// result of kid will be 12638131125462603235 (0xAF63A94C860195E3)
kid := tohash(strconv.Itoa(4))
// After this insert, I imagine a new row with primary key(id) 4 will be created, which keyspace_id is corresponding to hashed key of test_table's primary key.
sql := fmt.Sprintf("INSERT INTO test_table (keyspace_id, msg) VALUES (%d, '%s')", kid, "V is for speed")
if _, err := tx.Exec(sql); err != nil {
    fmt.Printf("exec failed: %v\n", err)
    os.Exit(1)
}
if err := tx.Commit(); err != nil {
    fmt.Printf("commit failed: %v\n", err)
    os.Exit(1)
}
