### ISSUE TITLE
Why I cannot insert into a Sharded Keyspace(V3 API), got "gRPCServerError: error: Query disallowed due to rule: enforce user_id range for INSERT_PK"

### ISSUE THREAD

**Issue by helayzhang** [youtube/vitess#1550]
I use example/demo to test my own vschema files, then try them onto my normal project.

I create a "user" keyspace, and a "lookup" keyspace. The "user" keyspace has 2 shards: -80/80-, "lookup" has 1 shard: 0.

And after create, I do these commands:
>$VTROOT/bin/vtctlclient -server localhost:15999 SetKeyspaceShardingInfo user user_id uint64
$VTROOT/bin/vtctlclient -server localhost:15999 RebuildKeyspaceGraph user
$VTROOT/bin/vtctlclient -server localhost:15999 RebuildKeyspaceGraph lookup
$VTROOT/bin/vtctlclient -server localhost:15999 InitShardMaster -force user/-80 zim_dev-0000000100
$VTROOT/bin/vtctlclient -server localhost:15999 InitShardMaster -force user/80- zim_dev-0000000200
$VTROOT/bin/vtctlclient -server localhost:15999 InitShardMaster -force lookup/0 zim_dev-0000000300
$VTROOT/bin/vtctlclient -server localhost:15999 ApplySchema -sql-file=lookup_schema.sql lookup
$VTROOT/bin/vtctlclient -server localhost:15999 ApplySchema -sql-file=user_schema.sql user
$VTROOT/bin/vtctlclient -server localhost:15999 ApplyVSchema -vschema_file=vschema.json

Then I can list tablets as:
>zim_dev-0000000100 user -80 master gim-server2:15100 gim-server2:33100 []
zim_dev-0000000101 user -80 replica gim-server2:15101 gim-server2:33101 []
zim_dev-0000000102 user -80 replica gim-server2:15102 gim-server2:33102 []
zim_dev-0000000200 user 80- master gim-server2:15200 gim-server2:33200 []
zim_dev-0000000201 user 80- replica gim-server2:15201 gim-server2:33201 []
zim_dev-0000000202 user 80- replica gim-server2:15202 gim-server2:33202 []
zim_dev-0000000300 lookup 0 master gim-server2:15300 gim-server2:33300 []
zim_dev-0000000301 lookup 0 replica gim-server2:15301 gim-server2:33301 []
zim_dev-0000000302 lookup 0 replica gim-server2:15302 gim-server2:33302 []

Then I try to use V3 APIs to insert data(Just like I do in example/demo.)
Here is my golang code:
>    tabletTypeMaster := topodatapb.TabletType_MASTER
    // Connect to vtgate.
    ctx := context.TODO()
    conn, err := vtgateconn.DialProtocol(ctx, "grpc", *server, timeout)
    if err != nil {
        fmt.Printf("dial failed: %v", err)
        os.Exit(1)
    }
    defer conn.Close()
    _, err = conn.Execute(ctx, "select * from user", nil, tabletTypeMaster)
    if err != nil {
        fmt.Printf("client error: %v", err)
        os.Exit(1)
    }
    tx, err := conn.Begin(ctx)
    defer tx.Rollback(ctx)
    _, err = tx.Execute(ctx,
        "insert into user(app_id, account, password, nickname, avatar, gender, signature, extern, device, version) values('appid1', 'user_1', 'pass_1', 'name_1', '', 0, '', '', '', '')",
        nil, tabletTypeMaster)
    if err != nil {
        fmt.Printf("client error: %v", err)
        os.Exit(1)
    }
    tx.Commit(ctx)

In the example/demo project, same db schema and vschema, "insert into user(app_id, account, password, nickname, avatar, gender, signature, extern, device, version) values('appid1', 'user_1', 'pass_1', 'name_1', '', 0, '', '', '', '')" this insert can be executed correctly. I can see a autoincr user_id is created and used as keyspace_id in user table.

Why I cannot insert use above code, I guess somewhere has problems, but I don't know how to fix it.

Here is my lookup_schema.sql user_schema.sql and vschema.json:
[files.zip](https://github.com/youtube/vitess/files/158789/files.zip)

**Comment by sougou** [comment]
It looks like your example should work. What error are you getting?

**Comment by thompsonja** [comment]
I'm guessing it's because the sharding key set in SetKeyspaceShardingInfo
is user_id but there's no user_id in the insert statement?

**Comment by sougou** [comment]
user_id is hash_autoinc. So, that should be fine. V3 will use the lookup to generate an id for it.

**Comment by helayzhang** [comment]
Console output:

>$go run client.go -server=localhost:15991
client error: execInsertSharded: shard, host: user.-80.master, uid:100 host:"gim-server2" port_map:<key:"grpc" value:16100 > port_map:<key:"mysql" value:33100 > port_map:<key:"vt" value:15100 > , vttablet: rpc error: code = 3 desc = "gRPCServerError: error: Query disallowed due to rule: enforce user_id range for INSERT_PK"exit status 1

My client.go:
[client.go.zip](https://github.com/youtube/vitess/files/159560/client.go.zip)

**Comment by sougou** [comment]
This is one area I'm not too familiar with, but I believe the command you have to run is this:
```
...> vtctl help SetKeyspaceShardingInfo
Usage: SetKeyspaceShardingInfo [-force] [-split_shard_count=N] <keyspace name> [<column name>] [<column type>]

Updates the sharding information for a keyspace.

  -force
        Updates fields even if they are already set. Use caution before calling this command.
  -split_shard_count int
        Specifies the number of shards to use for data splits
```
In your case, you should try: `vtctl SetKeyspaceShardingInfo user keyspace_id uint64`

v3 is currently hardcoded to send `keyspace_id` as the sharding key. This is a restriction we plan to remove in the future.

**Comment by helayzhang** [comment]
And one difference between my project and example/demo:

I notice example/demo use a python script to create a vtcombo process, and not see vttablets.
In my project, I use shell scripts modified from example/local to create/start sevaral vttablets, not start vtcombo. Should I use vtcombo instead of vttablets? 
Not very unberstand vtcombo's usages, is vtcombo a V3 support version of vttablet?

In my project, I start zookeeper, vtctl, vttablets, vtgate as example/local does, only change cell/keyspace/shard infos. I can upload my shell scripts if that will help.

Thanks~

**Comment by sougou** [comment]
vtcombo is an all-in-one executable of vitess. We mainly use it for testing.
The main advantage is that it's easier to bring up, because it's one binary. So, it's convenient for someone to try it out quickly. But if you already have the individual pieces up and running, you should stay with those.

**Comment by helayzhang** [comment]
“In your case, you should try: vtctl SetKeyspaceShardingInfo user keyspace_id uint64

v3 is currently hardcoded to send keyspace_id as the sharding key. This is a restriction we plan to remove in the future.”

Thanks, and I just run this, without change other things, and problem still exists:

>$VTROOT/bin/vtctlclient -server localhost:15999 SetKeyspaceShardingInfo -force user keyspace_id uint64
W0305 10:19:13.444621    7036 logger.go:93] W0305 02:19:13.442850 keyspace.go:59] Forcing keyspace ShardingColumnName change from user_id to keyspace_id

>$go run client.go -server=localhost:15991
client error: execInsertSharded: shard, host: user.-80.master, uid:100 host:"gim-server2" port_map:<key:"grpc" value:16100 > port_map:<key:"mysql" value:33100 > port_map:<key:"vt" value:15100 > , vttablet: rpc error: code = 3 desc = "gRPCServerError: error: Query disallowed due to rule: enforce user_id range for INSERT_PK"exit status 1

Should I change my db schema too, change "user_id" column name into "keyspace_id"? And also in vschema?

**Comment by sougou** [comment]
This should have worked. Can you try restarting your vttablets? Maybe they didn't pick up the change.

**Comment by helayzhang** [comment]
That works! After I restart vitess, everything works right now.

Thank you for help me!

**Comment by sougou** [comment]
I've filed an internal issue to make sure that the vttablets will update themselves when the vtctl command is run.
