### ISSUE TITLE
How to use a VIndex type "hash" in a vschema, need a example of vschema/schema.

### ISSUE THREAD

**Issue by helayzhang** [youtube/vitess#1554]
As I have my own unique key, and want to use it as "keyspace_id" for sharding.

In example/demo, I see how to create an auto_increase hash key of keyspace. Now I'm seeking the way to use a "hash" key:

>https://github.com/youtube/vitess/blob/master/doc/V3VindexDesign.md
numeric: binpack a uint64 into a keyspace_id
hash: hashes a uint64 into a keyspace_id
hash_autoinc: Same as hash, but can generate autoincrement values
lookup_hash: Uses a lookup table, and hashes the result to generate a keyspace_id. It’s non-unique.
lookup_hash_unique: lookup_hash, but unique
lookup_hash_autoinc
lookup_hash_unique_autoinc

For example, use my own user_id(uint64) which is hashed from a unique key.

My testing output:
>WARNING:root:vtclient_exception for None.None.master: ('VitessError', u'execInsertSharded: hash.Create: cannot route query: insert into () values(:): syntax error at position 14', 'Execute', 2, "insert into tbl_user(keyspace_id, app_id, account, password, nickname, avatar, gender, signature, extern, device, version) values(1, 'appid1', 'user_1', 'pass_1', 'name_1', '', 0, '', '', '', '') /* run this a few times */", 'tablet_type=master')

My config files:
[vschema.zip](https://github.com/youtube/vitess/files/161138/vschema.zip)

Very appreciated to any help~

**Comment by sougou** [comment]
Sorry about responding late on this. Looks like you closed this issue. Let us know if you still need this question (or others) answered.

**Comment by helayzhang** [comment]
Not at all, I have fixed my problems. 

I found I should use "numeric" vindex type instead of "hash", and use these vschema, can successfully setup my own keyspace id.

"user_idx": {
           "Type": "numeric"
         }

this is very simple, but I have a problem before because my user_id column(which used as keyspace_id) is SQL type of BIGINT,  this cause I cannot shard to the second shard. 
That should be BIGINT UNSIGNED, then everything runs well.
My user_id which is bigger then or equal to 0x8000 0000 0000 0000 will be sharded to the 80- shard.

**Comment by sougou** [comment]
This is because v3 is not yet feature-complete on the resharding side.
The way to make this work (for now) is to create both columns: user_id and keyspace_id, and populate them both. The v3 API can actually auto-fill the keyspace_id column based on user_id.
Basically, the non-v3 resharding still requires the keyspace_id column.
Once v3 is feature-complete, resharding will work with just the user_id column.

**Comment by helayzhang** [comment]
In my test, I create only a user_id column and no keyspace_id, no problem got by now.
Seems current V3 version will create a internal keyspace_id and use it (I guess).
Thanks for your help~

**Comment by helayzhang** [comment]
Another question ~

In a real deployment, 

conn, err := vtgateconn.DialProtocol(ctx, "grpc", *server, timeout)

Should I create a connection pool to manage my conns(to vtgate)? Will that benefit something or vitess has done these things for me?

**Comment by sougou** [comment]
The vtgate connection is multiplexed, and you can send multiple simultaneous requests through it.
These requests eventually reach vttablet, which will use a connection from a pool of mysql connections to run your query.

**Comment by helayzhang** [comment]
Thanks~, so I just need keep only one vtgate connection in my client, and it is thread-safe to multiple request Excute/Transactions. For example, I may call vtgate.conn.Execute(use same conn) from concurrency goroutines, is it OK too?

I have another problem, I found I cannot change a vindex column values, that will got:

>error: cannot change vindex columns

I think some situations need to change those columns, if a have a user keyspace, and make "name" column a vindex to lookup "user_id", I can use vindex type "lookup_hash". However, user may change their "name" in future, is there some ways to do this change?

**Comment by sougou** [comment]
Yes. You can execute multiple concurrent requests to VTGate.

The reason why you cannot change a vindex column is because it may result in the row migrating from one shard to another. However, you can achieve the same thing by deleting the row and re-creating it with the new values. This will ensure that every row is always consistent with respect to the keyspace_id.

**Comment by helayzhang** [comment]
I can understand if I change the keyspace_id value, may result in the row migrating from one shard to another. But if I only want to change a lookup column, may it result in migrating too?
It seems that "user" keyspace is sharded by "user_id", and "lookup" keyspace is not sharded.
So I think change "name" column should not make effect to "user_id" itself. Only do these changes:

1. change the row in lookup table(lookup keyspace):  name_user_idx, change "name" column
2. change the row in user table(user keyspace): change "name" column

**Comment by sougou** [comment]
I think what you say is possible. I'll need to dig into the code to make sure that allowing this doesn't accidentally allow other things that could potentially be invalid.
I'll let you know what I find.

**Comment by helayzhang** [comment]
Thanks a lot, I'll read more code too, and keep tracking this.

**Comment by sougou** [comment]
I looked at the code. We currently allow lookup tables to be used as a shared foreign key index. This means that multiple tables can reuse an existing name->keyspace_id relationship to co-locate (and find) data that belongs to the same name.
In such situations, changing a name could cause rows from other tables to become unreachable.

We're currently debating whether shared foreign keys are worth it. If we decide to not support this, we can reconsider allowing name changes.

Note that there is a similar issue with deletes. However, it's easier to expect the app to delete all detail table rows before deleting the main table row, which will also remove the lookup entry.

**Comment by helayzhang** [comment]
Really appreciate your great help and job!
It is true what you said, and I think using shared foreign key index is for performance considering.
Really useful for me of the details you supply.

During my use of Vitess, I found I often need to restart vtgate progress, that's not good for me.
I often meet this situation:

1. create a new table of a existing sharded keyspace
2. I do "ApplySchema" to the keyspace, to create table.
3. I do "ReloadSchema" to every tablet in that keyspace.
4. because that table has a new vindex(often it is a auto-incr id and lookup the keyspace_id, If I don't create a vindex for table, I will get gRPCServerError: error: DML too complex Error when insert), I also need to change my vschema.json. So i do "ApplyVSchema" to vtgate.

After all above done, I cannot do a insert to my new table, an error: "table tbl_test not found" faised, although I can found the schema by "GetSchema" command, checked it is correct. At last, I need restart vtgate, then things will go well.

It seems that, if i change vschema, I need to restart vtgate?

**Comment by sougou** [comment]
It's a known issue. We intend to fix it.
