### ISSUE TITLE
Guide to setup vitess on GCE

### ISSUE THREAD

**Issue by ronlobo** [youtube/vitess#1577]
Hey there,

Any plans on a guide to setup vitess on Google container engine?

That would be nutz!

**Comment by thompsonja** [comment]
Hi Ron, please refer to [vitess.io](http://vitess.io/getting-started/) for instructions on how to set up Vitess on Google Container Engine using Kubernetes, along with a sample guestbook app.  Feel free to reach out if you have any additional questions!

**Comment by ronlobo** [comment]
Hey,

thanks for pointing that out.
Just noticed that on http://vitess.io/getting-started/ the link to http://kubernetes.io/gettingstarted/ is outdated.
But the tutorial is great!

**Comment by enisoc** [comment]
Thanks for letting us know about the broken link. I'll get that fixed.
