### ISSUE TITLE
Docker Build on Ubuntu 14.04 amd64

### ISSUE THREAD

**Issue by hardcoar** [youtube/vitess#1639]
I followed the instructions here: http://vitess.io/getting-started/local-instance.html

im following #3 in starting vitess cluster, and when i try to start ./zk-up.sh i get this error on my terminal:
" mkdir: cannot create directory '/vtdataroot': Permission denied "

any thoughts on this?

**Comment by enisoc** [comment]
Did you explicitly set the `VTDATAROOT` env var to `/vtdataroot`? If so, you may need to choose a different location, that a non-root user has permission to modify. If you instead inherited `VTDATAROOT` by sourcing `dev.env`, then you need to make sure your `src/github.com/youtube/vitess` tree is itself rooted in a directory that a non-root user has permission to modify.

**Comment by enisoc** [comment]
I'm going to close this for now since I haven't heard back in a while. Feel free to reopen the issue if you need more help with this.
