### ISSUE TITLE
Tracking and Throwing meaningful exception returned from vtgate/vttablet/mysql

### ISSUE THREAD

**Issue by harshit-gangal** [youtube/vitess#1676]
As per my understanding currently vitess is handling errors documented here
https://github.com/youtube/vitess/blob/master/proto/vtrpc.proto

Going forward, it is good to track and throw SQL Errors

One use case I am thinking of is when some action needs to be taken when a duplicate entry present.

Talking in terms of SQLException.
It typically contains.

**- a string describing the error. **

**- a "SQLstate" string, https://dev.mysql.com/doc/refman/5.6/en/error-messages-server.html**

**- an integer error code,  that is the actual error code returned by the underlying database.**

- a chain to a next Exception. This can be used to provide additional error information.

- the causal relationship, if any for this SQLException.

Is there any plan to start reporting SQL Exceptions better with error codes and SQL State?

**Comment by enisoc** [comment]
I think this is a good idea. It seems like the main things we're missing in our current `SQLException` instances are the SQLSTATE and the integer error code.

There are two ways to get access to those error codes at the client level:
* Parse them out of the error string and inject them into `SQLException` in the low-level Java client.
* Plumb through the semantic values of `mysql_errno()` and `mysql_sqlstate()` all the way from the native mysql C client lib running on vttablet, through vtgate, to the vtgate client.

The first is easy but potentially brittle. The second would take more refactoring. I'll look into the options and report back here.

**Comment by sougou** [comment]
There is prior art: https://github.com/youtube/vitess/blob/master/py/vtdb/vtgate_utils.py#L92.
