### ISSUE TITLE
go/pools: timeUsed is not update

### ISSUE THREAD

**Issue by eahydra** [youtube/vitess#1697]
In go/pools/resource_pool.go#L50 timeUsed is not update, Is there no problem?
When set IdleTimeout such as 30 seconds, then when I next get resource from pools, then close the resource. So, Is no problem?

**Comment by sougou** [comment]
It does get updated, but indirectly. When a resource is returned through the Put call, a new resourceWrapper is created with a fresh timeUsed: https://github.com/youtube/vitess/blob/master/go/pools/resource_pool.go#L149.
The construction uses the old style anonymous construction of struct. We should change it to explicitly reference the fields that are being initialized.

**Comment by eahydra** [comment]
OK, I got it!
