### ISSUE TITLE
Error on kvctl.sh

### ISSUE THREAD

**Issue by TheDeadCode** [youtube/vitess#1719]
See this error

```
root@ubuntu:~/golang/src/github.com/youtube/vitess/examples/kubernetes# ./kvtctl.sh InitShardMaster -force test_keyspace/0 test-0000000100
Starting port forwarding to vtctld...
Error: flag needs an argument: --template
Run 'kubectl help' for usage.
```

**Comment by enisoc** [comment]
Hm it seems like somehow this command is getting cut off after `--template`:

https://github.com/youtube/vitess/blob/master/examples/kubernetes/env.sh#L30

Are you perhaps using a custom script to run `kubectl`, for example by setting the `KUBECTL` env var?

Can you show the output of `kubectl version`?

**Comment by TheDeadCode** [comment]
@enisoc :
```
root@ubuntu:~/golang/src/github.com/youtube/vitess/examples/kubernetes# kubectl version
Client Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.1", GitCommit:"6a5c06e3d1eb27a6310a09270e4a5fb1afa93e74", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}
```

**Comment by enisoc** [comment]
It looks like your `kubectl` client is version 1.0.1, which is pretty old. Can you try to update it to 1.2.x? How you do that will depend on how you installed `kubectl` in the first place.

**Comment by TheDeadCode** [comment]
Worked thanks!
