### ISSUE TITLE
Database name created as vt_<keyspace name> 

### ISSUE THREAD

**Issue by harshit-gangal** [youtube/vitess#1756]
When we start vttablet the database created is with vt_ as prefix.
On checking with @sougou currently through InitTablet only the database name can be overridden.

Can this be provided as a parameter while starting vttablet?

**Comment by alainjobart** [comment]
Yes it also can be provided as a parameter to vttablet, as init_db_name_override.

Note this is only used when you also pass init_keyspace, init_shard and init_tablet_type, which you probably do already...

Does that work for you?

**Comment by raunak-agarwal-flipkart** [comment]
Thanks Alain
Providing *init_db_name_override *works good. However, this flag has to be
set *prior* to *i**nit_keyspace, init_shard and init_tablet_type *flags.



~ Thanks and Regards
Raunak Kumar Agarwal
Ph. 9980125313
