### ISSUE TITLE
vschema not working correctly on my setup

### ISSUE THREAD

**Issue by Rastusik** [youtube/vitess#1786]
Hi, as @enisoc requested, I'm opening an issue regarding the empty vschema.

What Im doing is, |'m running this command to import vschema:
```
vtctlclient -server localhost:25999 ApplyVSchema -vschema_file=vschema.json project
```
the content of the vschema file is the following:
```
{
  "Keyspaces": {
    "project": {
      "sharded": false,
      "vindexes": {
      },
      "tables": {
        "_definition_sqlite": {},
        "_dummy": {},
        "_dummy2": {},
        "_error_log": {},
        ... truncated... just a bunch of other tables
      }
    }
  }
}
```

There is no error running this command. After that I'm checking the imported vschema with this command:

```
vtctlclient -server localhost:25999 GetVSchema project
```

I'm getting this response:

```
{}
```

When I'm checking the topology browser (/app/#/topo/tsm/vt/vschema), I see this:

```
{
  "keyspaces": {
    "project": {}
  }
}
```

It looks like the schema is being processed, because my app isn't able to read data from the tables before I import the vschema, after that the app is working.

Am I doing something wrong?

Thanks for help.

m

**Comment by ashudeep-sharma** [comment]
There has been some changes in the vschema.json file, it doesn;t start with keyspaces and project, it starts with sharded attribute, so if you specify the vschema like this: it should work:

`{
      "sharded": true,
      "vindexes": {
        "hash": {
          "type": "hash"
        },
        "tracking_shipment_idx": {
          "type": "lookup_hash",
          "params": {
            "table": "tracking_shipment_idx",
            "from": "trackingid",
            "to": "shipmentid"
          },
          "owner": "shipment"
        }
      },
      "tables": {
        "shipment": {
          "column_vindexes": [{
            "column": "shipmentid",
            "name": "hash"
          }, {
            "column": "trackingid",
            "name": "tracking_shipment_idx"
          }],
          "auto_increment": {
            "column": "shipmentid",
            "sequence": "shipment_idx"
          }
        },
        "runsheet": {
          "column_vindexes": [{
            "column": "runsheetid",
            "name": "hash"
          }, {
            "column": "createdatetime",
            "name": "date_runsheet_idx"
          }],
          "auto_increment": {
            "column": "runsheetid",
            "sequence": "runsheet_idx"
          }
        },
        "runsheet_shipments": {
          "column_vindexes": [{
            "column": "runsheetid",
            "name": "hash"
          }]
        }
      }
    }`

**Comment by Rastusik** [comment]
wow, that works, thank you!

In that cas sombedy should update this file: https://github.com/youtube/vitess/blob/master/examples/demo/schema/vschema.json

I'm always checking for changes in this particular file to see the vschema format changes .... is there any alternative?

**Comment by Rastusik** [comment]
is this one always more accurate? https://github.com/youtube/vitess/blob/master/examples/kubernetes/vschema.json

**Comment by sougou** [comment]
The one under examples/demo works only for vtcombo. The format is different because we need the ability to specify vschemas for multiple keyspaces, all in one file.
To upload using vtctl, you'll need to apply the vschema for each keyspace individually.
I think the single file case for vtcombo is confusing. Maybe we should break this up into individual files also. Let's see what others feel.

**Comment by sougou** [comment]
To answer your other question, the one under examples/kubernetes uses ApplyVSchema. So, that should always work.

**Comment by Rastusik** [comment]
Understood, thanks. So I'm closing this issue
