### ISSUE TITLE
resharding with a "unicode loose md5" column panic the vtworker

### ISSUE THREAD

**Issue by tsingakbar** [youtube/vitess#1787]
The call stack is as follows:

> panic: runtime error: index out of range
> 
> goroutine 302 [running]:
> panic(0xbb5a60, 0xc8200100b0)
> 	/opt/go/src/runtime/panic.go:481 +0x3e6
> github.com/youtube/vitess/vendor/golang.org/x/text/internal/colltab.(*Iter).Next(0xc820134c60, 0xc820067001)
> 	/Users/yuqing/projects/GoHome/src/github.com/youtube/vitess/vendor/golang.org/x/text/internal/colltab/iter.go:105 +0x2f8
> github.com/youtube/vitess/vendor/golang.org/x/text/collate.(*Collator).getColElems(0xc820134400, 0xc82044a700, 0x7, 0x12, 0x0, 0x0, 0x0)
> 	/Users/yuqing/projects/GoHome/src/github.com/youtube/vitess/vendor/golang.org/x/text/collate/collate.go:223 +0xf5
> github.com/youtube/vitess/vendor/golang.org/x/text/collate.(*Collator).Key(0xc820134400, 0xc820a7e400, 0xc82044a700, 0x7, 0x12, 0x0, 0x0, 0x0)
> 	/Users/yuqing/projects/GoHome/src/github.com/youtube/vitess/vendor/golang.org/x/text/collate/collate.go:200 +0xbf
> github.com/youtube/vitess/go/vt/vtgate/vindexes.normalize(0xc82044a700, 0x7, 0x12, 0x0, 0x0, 0x0)
> 	/Users/yuqing/projects/GoHome/src/github.com/youtube/vitess/go/vt/vtgate/vindexes/unicodeloosemd5.go:72 +0xc5
> github.com/youtube/vitess/go/vt/vtgate/vindexes.unicodeHash(0xc92bc0, 0xc82097b800, 0x0, 0x0, 0x0, 0x0, 0x0)
> 	/Users/yuqing/projects/GoHome/src/github.com/youtube/vitess/go/vt/vtgate/vindexes/unicodeloosemd5.go:62 +0xdb
> github.com/youtube/vitess/go/vt/vtgate/vindexes.(*UnicodeLooseMD5).Map(0xc8202cdfc0, 0x0, 0x0, 0xc82051d460, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
> 	/Users/yuqing/projects/GoHome/src/github.com/youtube/vitess/go/vt/vtgate/vindexes/unicodeloosemd5.go:48 +0x123
> github.com/youtube/vitess/go/vt/worker.(*v3Resolver).keyspaceID(0xc820172180, 0xc82077b100, 0x4, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
> 	/Users/yuqing/projects/GoHome/src/github.com/youtube/vitess/go/vt/worker/key_resolver.go:163 +0x1be
> github.com/youtube/vitess/go/vt/worker.(*RowSplitter).Split(0xc820177350, 0xc820256060, 0x4, 0x4, 0xc82066a000, 0x811, 0x811, 0x0, 0x0)
> 	/Users/yuqing/projects/GoHome/src/github.com/youtube/vitess/go/vt/worker/row_splitter.go:43 +0x110
> github.com/youtube/vitess/go/vt/worker.(*SplitCloneWorker).processData(0xc820242000, 0x7fafc0878518, 0xc8204486c0, 0xc82043cc40, 0x1, 0xc820396940, 0xc820177350, 0xc82044a800, 0x4, 0x4, ...)
> 	/Users/yuqing/projects/GoHome/src/github.com/youtube/vitess/go/vt/worker/split_clone.go:701 +0x3c5
> github.com/youtube/vitess/go/vt/worker.(*SplitCloneWorker).copy.func4(0xc820530140, 0xc820530150, 0xc820242000, 0xc8201721c0, 0x2, 0x2, 0xc8202cdf88, 0xc82024fbb0, 0xc82049e600, 0xc820177350, ...)
> 	/Users/yuqing/projects/GoHome/src/github.com/youtube/vitess/go/vt/worker/split_clone.go:574 +0x43d
> created by github.com/youtube/vitess/go/vt/worker.(*SplitCloneWorker).copy
> 	/Users/yuqing/projects/GoHome/src/github.com/youtube/vitess/go/vt/worker/split_clone.go:578 +0x2c27

I tried to add a mutex to lock the line https://github.com/youtube/vitess/blob/master/go/vt/vtgate/vindexes/unicodeloosemd5.go#L72 , this problem disappered.(Now complaining about read-only mysql instead, but it is a quite different thing, and I'm checking my mysql configuration now...)

**Comment by sougou** [comment]
Thanks for the report. I think this is a bug with collate. I'll post this in the golang-nuts group to see what they say.

**Comment by mpvl** [comment]
Note: A single Collator value is NOT safe for concurrent use.
I suggest using a new Collator per goroutine, if possible.
