### ISSUE TITLE
`go get github.com/youtube/vitess/go/cmd/vtctlclient` fails

### ISSUE THREAD

**Issue by sgrankin** [youtube/vitess#1811]
Issue:

```
$ docker run -it --rm golang:1.6 bash -c "go get github.com/youtube/vitess/go/cmd/vtctlclient"
# github.com/youtube/vitess/go/vt/proto/vtctlservice
src/github.com/youtube/vitess/go/vt/proto/vtctlservice/vtctlservice.pb.go:40: undefined: grpc.SupportPackageIsVersion2
```

I'm expecting this to work because it's explicitly called out in http://vitess.io/getting-started/

Likely cause:
https://github.com/grpc/grpc-go/commit/e78224b060cf3215247b7be455f80ea22e469b66
A breaking change in the master branch of a dependency, exposed when doing `go get` with an empty go tree.

Given the govendor use in vitess, I think the right solution (if continuing to support `go get` as the distribution method for this command) is to simply check in the contents of /vendor/... -- go 1.6 should fetch and use those instead of the head of grpc.

Thoughts?  I can submit a PR if this sounds right.

**Comment by enisoc** [comment]
We do want to try to keep `go get` working for `vtctlclient`. It would be unfortunate though if we have to check in all of `/vendor/` to achieve that. Maybe we can special-case `grpc-go` to check in only that, since they seem to be the ones who break us most often. I'll try that and see how it goes.

Thanks for reporting!

**Comment by enisoc** [comment]
I'm updating the version we vendor, which should make `go get` start working again: https://github.com/youtube/vitess/pull/1812

I'd like to look some more at our options for fixing this long term, so I'll keep this issue open.

**Comment by boj** [comment]
I just ran across this error on my local machine after setting up a clean Go 1.7.3 environment and am unsure how to proceed.

```
go get github.com/youtube/vitess/go/cmd/vtctlclient
# github.com/youtube/vitess/go/vt/proto/vtctlservice
../go/src/github.com/youtube/vitess/go/vt/proto/vtctlservice/vtctlservice.pb.go:42: undefined: grpc.SupportPackageIsVersion3
```

Would it make sense to simply offer release builds downloadable via github?

**Comment by michael-berlin** [comment]
Thanks for reporting this problem :)

I've created a pull request to unbreak you: https://github.com/youtube/vitess/issues/1811#issuecomment-258740349

I agree that we should consider to distribute binaries of vtctlclient. We could use as a service like http://gobuild.io for that?

@enisoc Does the Kubernetes have any other dependency than vtctlclient?

**Comment by enisoc** [comment]
@michael-berlin No, `vtctlclient` is the only part of Vitess you need to install locally to run in Kubernetes.

**Comment by michael-berlin** [comment]
We've stopped the problem for now by adjusting our code to the latest gRPC version. In general, it should be noted that we can usually do this rather quickly.

re: Using a build service like gobuild.io. Such a service would probably always use the latest version and run into the same problem as somebody running `go get`.

Therefore, I'm considering to provide binaries for Linux and MacOSX. We could update the binaries every time we upload newer Kubernetes images (vitess lite Docker image) and store them on GitHub. Once we have the binaries, people can also skip installing Go.
