### ISSUE TITLE
VtGate throwing Error on keeping watch for deleted keyspace

### ISSUE THREAD

**Issue by harshit-gangal** [youtube/vitess#1844]
When a keyspace is deleted. Vtgate Keep a watch on vschema for this keyspace and keep filling logs with error.
As per @sougou  this was a known bug
Can this be fixed?

**Comment by alainjobart** [comment]
Can you copy the log message that you see? I don't think it's the vschema, it might be the SrvKeyspace...

**Comment by harshitgangal** [comment]
E0704 22:05:05.930066   82799 serving_graph.go:93] Cannot set watch on
/zk/test/vt/ns/test_keyspace, waiting for 30s to retry: zookeeper: getw
"/zk/test/vt/ns/test_keyspace": no node

**Comment by alainjobart** [comment]
Yes this is not the vschema, it's the regular SrvKeyspace watch. Thanks for clearing that up. I'll work on a fix.

**Comment by alainjobart** [comment]
Also, a work-around, restarting vtgate should fix the errors, as the keyspace should be gone in the first place... Not ideal I agree.

**Comment by alainjobart** [comment]
This PR should fix this: https://github.com/youtube/vitess/pull/1967
