### ISSUE TITLE
Incompatibility comparing to mysql SQL query with an field alias in GROUP BY clause

### ISSUE THREAD

**Issue by Rastusik** [youtube/vitess#1861]
Hi there,

while testing Vitess, we found that the following query is not compatible with mysql query:

```
SELECT `field` as `alias`, `whatever` as `arrival` FROM `nice_table` WHERE `id_field` = 'X' GROUP BY `field`
```

The query returns this error:

```
symbol field not found
```

A workaround is to overwrite the query as follows:

```
SELECT `field` as `alias`, `whatever` as `arrival` FROM `nice_table` WHERE `id_field` = 'X' GROUP BY `alias`
```

This is not a big issue, I'm just letting you know.

**Comment by sougou** [comment]
This is not as simple as it appears. In reality, `alias` hides the `field` expression. However, I believe MySQL allows you to reference any table columns in the GROUP BY expressions. This is why it allowed you to use `field`. If you changed the GROUP BY to use a column that's not in the SELECT expression, it would still work.
However, this is non-standard SQL, and in my opinion, a confusing feature. So, I felt that we should not support it in Vitess.

**Comment by Rastusik** [comment]
Well, it depends then whether Vitess wants to support standard SQL or MySQL. 

I can understand both decisions. The first one might complicate migrations of some applications. It’s similar to the INSERT INTO autoincrement_vindexed_table (id, title) VALUES (0, ‘test’); 

Should it be backwards compatible with MySQL or not? 

Feel free to close the issue, if it is already decided, I just wasn’t sure if this was a bug or not.

**Comment by sougou** [comment]
There may or may not be a secret agenda to support other engines like Postgres SQL in the future :).

**Comment by Rastusik** [comment]
what if postgres supports this type of query? :)

**Comment by chrisgillis** [comment]
Just thought I'd mention that we've also experienced similar errors when grouping by a field not present in the select clause.

`SELECT col1 FROM t1 WHERE shard_key=x GROUP BY col2` will result in `symbol col2 not found` unless col2 is present in the select clause explicitly or by wildcard.

**Comment by sougou** [comment]
It's the same code path. It will become evident once you ramp up on how the v3 symbol table works :).
