### ISSUE TITLE
can't find file 'vendor/autoload.php' under 'php' directory

### ISSUE THREAD

**Issue by geekard** [youtube/vitess#1862]
zhangjun@geekard-2:~/golang/src/github.com/youtube/vitess/examples/local% php client.php -server=localhost:15991

Warning: require_once(/Users/zhangjun/golang/src/github.com/youtube/vitess/examples/local/../../php/vendor/autoload.php): failed to open stream: No such file or directory in /Users/zhangjun/golang/src/github.com/youtube/vitess/examples/local/client.php on line 17

Fatal error: require_once(): Failed opening required '/Users/zhangjun/golang/src/github.com/youtube/vitess/examples/local/../../php/vendor/autoload.php' (include_path='.:') in /Users/zhangjun/golang/src/github.com/youtube/vitess/examples/local/client.php on line 17

zhangjun@geekard-2:~/golang/src/github.com/youtube/vitess% ls -F /Users/zhangjun/golang/src/github.com/youtube/vitess/examples/local/../../php
README.md  pdo/  src/  tests/

**Comment by Rastusik** [comment]
thanks for the report, I'll look into it ASAP

**Comment by enisoc** [comment]
Did you run `composer install`? That should have created this file.

https://github.com/youtube/vitess/blob/master/php/README.md#grpc-dependencies

**Comment by geekard** [comment]
Oh, Yes!  It goes well now!
