### ISSUE TITLE
vitess/Makefile 136: sed of OSX doesn't support '--in-place -r'

### ISSUE THREAD

**Issue by geekard** [youtube/vitess#1863]
under OSX,  '--in-place -r' should be '-i -E' ,  or use gnu-sed
$ brew install gnu-sed
$ export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
or just use basic regexp with escape('-i' is fine, OSX and Linux all support it).

**Comment by enisoc** [comment]
Thanks for the suggestion!
