### ISSUE TITLE
unicode_loose_md5 vindex type memory leak where column is binary

### ISSUE THREAD

**Issue by adkhare** [youtube/vitess#1871]
[pprof.zip](https://github.com/youtube/vitess/files/364447/pprof.zip)

Attached is the pprof as suggested by sougu. Also, below is the vschema:
{
  "sharded": true,
  "vindexes": {
    "hash": {
      "type": "hash"
    },
    "unicode_loose_md5": {
      "type": "unicode_loose_md5"
    }
  },
  "tables": {
    "user": {
      "column_vindexes": [
        {
          "column": "tenant_id",
          "name": "unicode_loose_md5"
        }
      ]
    }
  }
}
~

**Comment by enisoc** [comment]
I tried switching my sharded local example to use `unicode_loose_md5`, but I still can't reproduce the leak. I also tried sending writes while the masters are down, but no leak.

So it's not as simple as a leak that happens every time we call into the vindex. There could be some interaction between this vindex and those strange inconsistent write failures you were seeing.

Anything else you can provide to help us reproduce would be great.

**Comment by sougou** [comment]
@mpvl @ashudeep-sharma 
I think this can happen only if there is an invalid input. It looks like the code went into an infinite loop. @adkhare: would you be able to identify the bit-pattern that caused the OOM? Maybe @mpvl can find out by looking at the call stack:

```
heap profile: 3: 1946730496 [78: 9729093568] @ heap/1048576
1: 1542381568 [1: 1542381568] @ 0x445dc3 0x941572 0x9409f5 0x947c67 0x947d32 0x8914c5 0x89107f 0x6df230 0x6df00b 0x6dec83 0x53eac4 0x53b340 0x537baf 0x53064a 0x797a87 0x5375cd 0x54a2aa 0x527e88 0x783c08 0x714115 0x71691d 0x71b8e0 0x463121
#	0x941572	github.com/youtube/vitess/vendor/golang.org/x/text/collate/colltab.(*table).appendNext+0x382	/home/amit/vitess/src/github.com/youtube/vitess/vendor/golang.org/x/text/collate/colltab/table.go:123
#	0x9409f5	github.com/youtube/vitess/vendor/golang.org/x/text/collate/colltab.(*table).AppendNext+0xc5	/home/amit/vitess/src/github.com/youtube/vitess/vendor/golang.org/x/text/collate/colltab/table.go:28
#	0x947c67	github.com/youtube/vitess/vendor/golang.org/x/text/internal/colltab.(*Iter).appendNext+0x227	/home/amit/vitess/src/github.com/youtube/vitess/vendor/golang.org/x/text/internal/colltab/iter.go:88
#	0x947d32	github.com/youtube/vitess/vendor/golang.org/x/text/internal/colltab.(*Iter).Next+0x32		/home/amit/vitess/src/github.com/youtube/vitess/vendor/golang.org/x/text/internal/colltab/iter.go:100
#	0x8914c5	github.com/youtube/vitess/vendor/golang.org/x/text/collate.(*Collator).getColElems+0xf5		/home/amit/vitess/src/github.com/youtube/vitess/vendor/golang.org/x/text/collate/collate.go:223
#	0x89107f	github.com/youtube/vitess/vendor/golang.org/x/text/collate.(*Collator).Key+0xbf			/home/amit/vitess/src/github.com/youtube/vitess/vendor/golang.org/x/text/collate/collate.go:200
#	0x6df230	github.com/youtube/vitess/go/vt/vtgate/vindexes.normalize+0x1a0					/home/amit/vitess/src/github.com/youtube/vitess/go/vt/vtgate/vindexes/unicodeloosemd5.go:84
#	0x6df00b	github.com/youtube/vitess/go/vt/vtgate/vindexes.unicodeHash+0xdb				/home/amit/vitess/src/github.com/youtube/vitess/go/vt/vtgate/vindexes/unicodeloosemd5.go:62
#	0x6dec83	github.com/youtube/vitess/go/vt/vtgate/vindexes.(*UnicodeLooseMD5).Map+0x123			/home/amit/vitess/src/github.com/youtube/vitess/go/vt/vtgate/vindexes/unicodeloosemd5.go:48
#	0x53eac4	github.com/youtube/vitess/go/vt/vtgate.(*Router).handlePrimary+0x304				/home/amit/vitess/src/github.com/youtube/vitess/go/vt/vtgate/router.go:533
#	0x53b340	github.com/youtube/vitess/go/vt/vtgate.(*Router).execInsertSharded+0x450			/home/amit/vitess/src/github.com/youtube/vitess/go/vt/vtgate/router.go:325
#	0x537baf	github.com/youtube/vitess/go/vt/vtgate.(*Router).ExecuteRoute+0x2bf				/home/amit/vitess/src/github.com/youtube/vitess/go/vt/vtgate/router.go:97
#	0x53064a	github.com/youtube/vitess/go/vt/vtgate.(*requestContext).ExecuteRoute+0x4a			/home/amit/vitess/src/github.com/youtube/vitess/go/vt/vtgate/request_context.go:50
#	0x797a87	github.com/youtube/vitess/go/vt/vtgate/engine.(*Route).Execute+0x47				/home/amit/vitess/src/github.com/youtube/vitess/go/vt/vtgate/engine/route.go:33
#	0x5375cd	github.com/youtube/vitess/go/vt/vtgate.(*Router).Execute+0x24d					/home/amit/vitess/src/github.com/youtube/vitess/go/vt/vtgate/router.go:67
#	0x54a2aa	github.com/youtube/vitess/go/vt/vtgate.(*VTGate).Execute+0x2aa					/home/amit/vitess/src/github.com/youtube/vitess/go/vt/vtgate/vtgate.go:166
#	0x527e88	github.com/youtube/vitess/go/vt/vtgate/grpcvtgateservice.(*VTGate).Execute+0x2a8		/home/amit/vitess/src/github.com/youtube/vitess/go/vt/vtgate/grpcvtgateservice/server.go:93
#	0x783c08	github.com/youtube/vitess/go/vt/proto/vtgateservice._Vitess_Execute_Handler+0x168		/home/amit/vitess/src/github.com/youtube/vitess/go/vt/proto/vtgateservice/vtgateservice.pb.go:432
#	0x714115	github.com/youtube/vitess/vendor/google.golang.org/grpc.(*Server).processUnaryRPC+0xeb5		/home/amit/vitess/src/github.com/youtube/vitess/vendor/google.golang.org/grpc/server.go:530
#	0x71691d	github.com/youtube/vitess/vendor/google.golang.org/grpc.(*Server).handleStream+0x109d		/home/amit/vitess/src/github.com/youtube/vitess/vendor/google.golang.org/grpc/server.go:687
#	0x71b8e0	github.com/youtube/vitess/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1+0xa0	/home/amit/vitess/src/github.com/youtube/vitess/vendor/google.golang.org/grpc/server.go:352
```

**Comment by ashudeep-sharma** [comment]
I tried to check this , for me it is working fine.I did the following steps to reproduce this:
For me this seems to be working fine, I checked with the following QPS:
"QPSByDbType": {"All":[381.65,408.96666666666664,382.8666666666667,406.9,388.48333333333335,415.8833333333333,404.18333333333334,387.1166666666667,396.75,319.95,370.28333333333336,388.6166666666667,409.05,416.43333333333334,386.65],"master":[381.65,408.96666666666664,382.8666666666667,406.9,388.48333333333335,415.8833333333333,404.18333333333334,387.1166666666667,396.75,319.95,370.28333333333336,388.6166666666667,409.05,416.43333333333334,386.65]},
"QPSByKeyspace": {"All":[381.65,408.96666666666664,382.8666666666667,406.9,388.48333333333335,415.8833333333333,404.18333333333334,387.1166666666667,396.75,319.95,370.28333333333336,388.6166666666667,409.05,416.43333333333334,386.65],"Any":[381.65,408.96666666666664,382.8666666666667,406.9,388.48333333333335,415.8833333333333,404.18333333333334,387.1166666666667,396.75,319.95,370.28333333333336,388.6166666666667,409.05,416.43333333333334,386.65]},
"QPSByOperation": {"All":[381.65,408.96666666666664,382.8666666666667,406.9,388.48333333333335,415.8833333333333,404.18333333333334,387.1166666666667,396.75,319.95,370.28333333333336,388.6166666666667,409.05,416.43333333333334,386.65],"Execute":[381.65,408.96666666666664,382.8666666666667,406.9,388.48333333333335,415.8833333333333,404.18333333333334,387.1166666666667,396.75,319.95,370.28333333333336,388.6166666666667,409.05,416.43333333333334,386.65]}

For me the VTGate memory consumption never increased from more than 0.2%
Here are some of the stats that i collected:
7701 ashudeep  20   0  145m  12m 7644 S  60.4  0.2   0:23.98 vtgate 
7701 ashudeep  20   0  145m  13m 7660 S  65.1  0.2   0:31.06 vtgate 
7701 ashudeep  20   0  235m  13m 7676 S  61.4  0.2   2:29.91 vtgate
7701 ashudeep  20   0  235m  13m 7772 S  57.8  0.2  17:14.26 vtgate

**Comment by ashudeep-sharma** [comment]
@adkhare: It will also help if you can give the details of the table schema and the way you were executing the queries.

I had my setup[8 VtTablets,1 VTGate and VTCTL] on a single machine.
I executed my queries using preparedStatement in JDBC with 10 threads to achieve a qps of around 400. There seems to be no issue.

As Sugu said, it would be great if u can share the steps mentioned above for us to cross-check whats the real issue here.

**Comment by enisoc** [comment]
If the collator is getting stuck for certain inputs, that could also explain the other symptom @adkhare described in slack: some writes would go through fine but some would get stuck at vtgate (never even reaching vttablet). Maybe we can just hook up a binary fuzzer to Collator.Key() to reproduce this.

**Comment by adkhare** [comment]
https://gist.github.com/adkhare/7d01012d2c951105e7721324415181e1 is the python client script for writing to vitess

**Comment by enisoc** [comment]
Thanks for the script @adkhare! I was immediately able to reproduce the leak.

It seems to be just as @sougou said: Sending invalid unicode (in this case, a random binary string generated via the uuid lib) can cause the collate library to get stuck and loop indefinitely. Note that the `unicode_loose_md5` vindex is only intended for use on columns that contain valid unicode, so inserting the binary version of a UUID is not a supported use case (sending a textual representation would have been fine). However, it should of course not get stuck in an infinite loop if you do, so we will fix that.

I will first try updating our vendored collate libs to check that the bug still exists in the latest version. It's also possible that we're responsible for checking that our input is valid unicode before we send it to `Collator.Key()`, so I'll look into the docs. If necessary, I'll file a bug against the collate lib.
