### ISSUE TITLE
VTTablet errors on high load

### ISSUE THREAD

**Issue by adkhare** [youtube/vitess#1873]
I am giving high load on single vtgate. 2 shards are loaded with total of ~1.5K qps and I am seeing following errors on tablet:
E0715 20:30:14.116411   17492 throttled.go:61] TxPoolFull: skipped 33 log messages
E0715 20:33:05.479648   17492 tablet_error.go:245] TxPoolFull:tx_pool_full: Transaction pool connection limit exceeded

not sure if they are relevant or might lead to data loss.

**Comment by enisoc** [comment]
The `tx_pool_full` error means the tablet is limiting the number of concurrent transactions to protect mysqld. You can tune this setting to your needs by changing the `-queryserver-config-transaction-cap` flag on vttablet. The default (20) is rather conservative. We generally keep it at several hundred, but it depends on the resources you allocate to mysqld, and also on the particular blend of transactions you send (mysql lock contention, etc.).

**Comment by adkhare** [comment]
Will these errors cause the data loss? Or they will just reduce the concurrency and slow down the writes

**Comment by sougou** [comment]
tx pool full errors are returned on a call to Begin. As long as the app handles the error correctly, there should be no corruption.
With `queryserver-config-txpool-timeout`, you can specify for how long you want vttablet to wait before returning a tx pool error.
In general, MySQL performance degrades when there are too many concurrent transaction. The low 100s of connections we recommend is for handling temporary spikes. In other words, you should avoid going overboard on how big you want to set your tx pool.

**Comment by sougou** [comment]
Forgot to provide the customary launch doc link: https://github.com/youtube/vitess/blob/master/doc/LaunchingVitess.md#query-server-parameters
