### ISSUE TITLE
OSX: Error while compiling proto definitions

### ISSUE THREAD

**Issue by Rastusik** [youtube/vitess#1877]
```bash
~/DEV/vitess_build/src/github.com/youtube/vitess • make build
Mon Jul 18 13:49:29 CEST 2016: Compiling proto definitions
cp: illegal option -- u
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_director
```

I think the cp -au (the 'u' part) statement in Makefile can be written safely without the 'u' parameter, it shouldn't make any visible performance impacts, don't you think?

**Comment by enisoc** [comment]
@michael-berlin Is it ok if we remove `-u`? Why did you add it?

**Comment by Rastusik** [comment]
well, I'm not entirely sure about it tbh ... when I removed it manually, another problem occuder #1878

**Comment by michael-berlin** [comment]
The main idea behind adding `-u` was probably to avoid copies when they are not necessary.

Given that the target is called only by `make proto` let's remove the `-u`. @Rastusik let me know if I should change it or you want to do that.

**Comment by Rastusik** [comment]
@michael-berlin I'll let you know after resolving #1878 

It would probably make sense to resolve both the issues at once

**Comment by enisoc** [comment]
This should be fixed by https://github.com/youtube/vitess/commit/a6a7c3e48998ae757487f9312a040585f81ed918.
