### ISSUE TITLE
Grouping with column names when aliasing leads to an error

### ISSUE THREAD

**Issue by mdhheydari** [youtube/vitess#1885]
I tried running these queries through vtgate:
```
select u.id as col0 from users u where u.username='mdhheydari' group by col0
select u.id as col0 from users u where u.username='mdhheydari' group by id
select u.id as col0 from users u where u.username='mdhheydari' group by u.id
```
The first one works but the other two raise an error 'symbol id not found' and 'symbol u.id not found'. while all of them works in mysql, Is there a way to run them in vitess too?

**Comment by Rastusik** [comment]
#1861
