### ISSUE TITLE
update Google Cloud API client import paths and more

### ISSUE THREAD

**Issue by jba** [youtube/vitess#1913]
The Google Cloud API client libraries for Go are making some breaking changes:

* The import paths are changing from `google.golang.org/cloud/...` to
  `cloud.google.com/go/...`. For example, if your code imports the BigQuery client
  it currently reads
```import "google.golang.org/cloud/bigquery"```
It should be changed to
```import "cloud.google.com/go/bigquery"```

* Client options are also moving, from `google.golang.org/cloud` to
  `google.golang.org/api/option`. Two have also been renamed:
  - `WithBaseGRPC` is now `WithGRPCConn`
  - `WithBaseHTTP` is now `WithHTTPClient`

* The `cloud.WithContext` and `cloud.NewContext` methods are gone, as are the
deprecated pubsub and container functions that required them. Use the `Client`
methods of these packages instead.

You should make these changes before September 12, 2016, when the packages at
`google.golang.org/cloud` will go away.

**Comment by alainjobart** [comment]
I have the PR at:
https://github.com/youtube/vitess/pull/1915
to address this, thank you for the report!
