### ISSUE TITLE
keep_logs parameter doesn;t work in VTGate/VTTablets

### ISSUE THREAD

**Issue by ashudeep-sharma** [youtube/vitess#1994]
I tried using keep_logs parameter to purge the logs after x seconds, but it doesn;t seems to work.
While starting tablets and VTGate used keep_logs 100s as the configuration. Is there any other setting that needs to be done to make this functionality work??

**Comment by enisoc** [comment]
The `keep_logs` flag will only purge logs that are no longer the current one; that is, the log has rotated and that file is no longer in use.

We use the `glog` package for logging, which rotates logs when they reach 1800MiB:

https://github.com/golang/glog/blob/master/glog_file.go#L34

**Comment by ashudeep-sharma** [comment]
To workaround the 1800MiB part, i restarted VTGate/VTCTL so that it creates new files, but still i couldn;t see the older files getting purged.It still shows the older files.

**Comment by ashudeep-sharma** [comment]
@harshit-gangal  and I debugged this and we found two issues here, There seems to be a problem with _func parseTimestamp(filename string)_ in purge.go. 

This function works on two assumptions, first it always considers that the time-zone is UTC and second it assumes that the date format in the fileName occurs at 5th index, which might not be true in case the folderPath have extra '.' in the folder names since it splits the folder path  on '.'

Here is the code:

_func parseTimestamp(filename string) (timestamp time.Time, err error) {
	parts := strings.Split(filepath.Base(filename), ".")
	if len(parts) < 6 {
		return time.Time{}, fmt.Errorf("malformed logfile name: %v", filename)
	}
	return **time.Parse("20060102-150405", parts[5])**

}_

As a part of the fix for this we think there can be two changes either use 
return **time.ParseInLocation("20060102-150405", parts[len(parts)-2],time.Now().Location())**
instead of return **time.Parse("20060102-150405", parts[5])** if we are sure that our second last substring will always be a date or to iterate through every string  in 
parts := strings.Split(filepath.Base(filename), ".")
and check for the proper formatting and then use the corresponding function.

The Best Approach could be to check the file modifyDateTime from file.ModTime() using os.Stat() function to get the last Modified Time so that we don;t depend on fileName.
Please let us know which approach should we go ahead with?

**Comment by enisoc** [comment]
Thanks for the detailed analysis! I like your solution to use `ParseInLocation()` and `parts[len(parts)-2]`. Do you plan to submit a pull request?

**Comment by ashudeep-sharma** [comment]
@enisoc : Created Pull Request for this https://github.com/youtube/vitess/pull/2011

I ran only the logutil_test test, let me know in case needs to fix some other tests for it.
