### ISSUE TITLE
PHP Composer Dependecy Forces Problematic Dependency

### ISSUE THREAD

**Issue by tjcelaya** [youtube/vitess#2002]
The [php-client package](https://packagist.org/packages/vitess/php-client#v2.0.0) depends explicitly on grpc `dev-release-0_13` and as such is several versions behind the current release of grpc (`v1.0.0`).

Would it be possible for this dependency to be updated to use a newer version? There are currently conflicts between protobuf libraries because a dependency of grpc was forked. This can be temporarily "fixed" by using this fake repo [pixelfederation/datto-Protobuf-PHP-fake](https://github.com/pixelfederation/datto-Protobuf-PHP-fake) as a composer override, but that solution is error-prone and can cause issues.

**Comment by alainjobart** [comment]
We have on our list to upgrade our tree to proto 3.0.0 and gRPC 1.0.0, we'll address this shortly.
