### ISSUE TITLE
DB, table and field names in backticks should allow special chars 

### ISSUE THREAD

**Issue by percona-csalguero** [youtube/vitess#2022]
According to MySQL docs http://dev.mysql.com/doc/refman/5.7/en/identifiers.html, db, table and field names in backticks, can have special chars.

**Comment by sougou** [comment]
This is a dup of #1953. I'll get to this, eventually :)

**Comment by percona-csalguero** [comment]
I already have a fix. I didn't PR it yet

**Comment by sougou** [comment]
This is non-trivial because I know of at least one downstream dependency in vtgate: Bind var names are generated based on the column name, and that will cause incorrect query rewrites.

**Comment by sougou** [comment]
Just to clarify: If that was the only place, the fix there would also be trivial :). What's non-trivial is making sure that there are no other such dependencies. There should be a way to make the compiler tell us all the places where column names are used. I just have to figure out how. Then we can verify each use case.
