### ISSUE TITLE
Column aliasing in Select query cause order by to fail

### ISSUE THREAD

**Issue by ashudeep-sharma** [youtube/vitess#2110]
@sougou 
This query work as aliased column is used in order by.
select **msg0_.pk as pk0_** from msg msg0_ where sk = 1 **order by pk0_** desc limit 2; 

This query is trying to use msg0_.pk in order by but the plan generation fails with reason "symbol msg0_.pk not found"
select **msg0_.pk as pk0_** from msg msg0_ where sk = 1 **order by msg0_.pk** desc limit 2;  

But, these kind of query are very common as most of the third party tools which run over the drivers/clients send these queries to Vitess.

**Comment by sougou** [comment]
This is another variation of #1861. pk0_ essentially hides the symbol it aliases. But this specific problem is easier to address without changing the visibility rules. It's essentially multiple aliases for the same symbol element.

**Comment by sougou** [comment]
Closed via #2121
