### ISSUE TITLE
Unable to build under OSX Sierra because of Protobuf compile error.

### ISSUE THREAD

**Issue by Rastusik** [youtube/vitess#2115]
Hi guys,

I just wanted you to know that the OSX build doesn't work under OSX Sierra because of this Protobuf compile error: https://github.com/google/protobuf/issues/2182

I'm not sure what to do about this, I think the only option is just wait for a fix in the Protobuf library, then wait for Grpc to icnlude Protobuf with the fix and then update Grpc in Vitess?

Seems like I'm out for a couple of weeks :)

**Comment by michael-berlin** [comment]
This came up on our mailing list as well: https://groups.google.com/d/msg/vitess/eUwzT7Kw_a0/OMSLuz_uBQAJ

There I've mentioned that the protobuf issue thread lists a work-around and that is to remove `-Werror` from the Makefile.

Can you please confirm if that works?

I have a feeling that it might take a while until any upstream fix has trickled down to us. In the meantime, I wouldn't mind if we patch the Makefile as part of our `travis/install_grpc.sh` script. We did this before for other things e.g. here: https://github.com/youtube/vitess/commit/ce4239f84a684712d9c4696525cc64b1f1a0e5c3

Martin, this may be something which is easy for you to put together and test?

**Comment by Rastusik** [comment]
I'll try to confirm later today, I have found such flag in protobuf/src/Makefile.am

**Comment by Rastusik** [comment]
@michael-berlin so I tried the following with the protobuf dir in travis/install_grpc.sh:

```
# build protobuf on OSX Sierra
  sed -i '' -e 's,-Werror,,' $VTROOT/dist/grpc/grpc/third_party/protobuf/src/Makefile.am
  sed -i '' -e 's,-Werror,,' $VTROOT/dist/grpc/grpc/third_party/protobuf/more_tests/Makefile
  sed -i '' -e 's,-Werror,,' $VTROOT/dist/grpc/grpc/third_party/protobuf/python/setup.py
```

the files were replaced before compiling protobuf, but the error still occured. I haven't found any other reasonable occurences of the -Werror flag

**Comment by michael-berlin** [comment]
I've tried it and the removal of `-Werror` from the Makefile should work.

See the PR I created: https://github.com/youtube/vitess/pull/2123

Make sure to delete `$VTROOT/dist/grpc` and re-run `bootstrap.sh`. Also, make sure that grpc is using its own copy of protobuf and not a system-wide one.

For reference, here's what I tried on my Linux machine (note that the `sed` syntax there is slightly different):

* `-Werror` is present:

  ```sh
$ grep -e "-Werror" $VTROOT/dist/grpc/grpc/third_party/protobuf/src/Makefile
                           -Wall -Werror
  ```

* Patch `travis/install_grpc.sh` such that it removes the flag before running `make` in the `grpc` directory.

* Remove old `grpc` directory.
  ```sh
$ rm -rf $VTROOT/dist/grpc
  ```

* Re-run bootstra.sh.
  ```sh
$ ./bootstrap.sh 
[...]
bootstrap finished - run 'source dev.env' in your shell before building.
  ```

* `-Werror` is no longer present:

  ```sh
$ grep -e "-Werror" $VTROOT/dist/grpc/grpc/third_party/protobuf/src/Makefile
  ```

**Comment by Rastusik** [comment]
I think I didn't write it clearly - yesterday I was doing the same thing as you describe. I used the former 3 sed commands in the travis/install_grpc.sh script **before** running the make command on protobuf library and the whole thing returned the same error as before. In your pull request, there is one of my 3 sed commands, I don't think this will help.

Or am I not understanding anything?

**Comment by michael-berlin** [comment]
Yes, you're correct. 

Assuming the sed command itself has the desired effect on macOS, this should work. I can only test this on Linux and there it worked. 

I've mentioned other reasons why it may not have worked in your case:

* `dist/grpc` directory was not deleted
* different protobuf library is used (not the one shipped with grpc)

**Comment by Rastusik** [comment]
well, I can test one more time, but I think that the fact, that your changes work in linux proves nothing.  

Regarding option 1:
I've seen that the bootstrap script (or the grpc script) in vitess deletes the whole dist/grpc directory on every run, if grpc isn't present (which it wasn't in this case), so in every run I've seen new git clones of grpc and it's dependencies (with protobuf among them) ... 

Regarding option 2:
I'm getting a compile error on the protobuf source from grpc, because I'm running the bootstrap.sh script shipped with vitess ... I think that this workaround doesn't work with the shipped protobuf library source...

**Comment by Rastusik** [comment]
tested one more time, I even checked the occurence of the Werror string in the protobuf source files during build ... still getting the same error

**Comment by michael-berlin** [comment]
Is the `-Werror` string gone now?

Maybe you're using a different protobuf copy?

**Comment by Rastusik** [comment]
the -wError string is completely gone from the protobuf sources in the grpc/third_party folder ... 

I'm not sure if I follow - but how can I use a different protobuf copy? this error occurs during the build of protobuf. I'm in the Vitess master branch and I'm building the protobuf copy bundled with grpc downloaded during the vitess bootstrap process...

The compile error is purely OSX specific: 

```
third_party/protobuf/src/google/protobuf/stubs/atomicops_internals_macosx.h:173:9: error: 'OSAtomicCompareAndSwap64Barrier' is deprecated: first deprecated in
      macOS 10.12 - Use std::atomic_compare_exchange_strong() from <atomic> instead [-Werror,-Wdeprecated-declarations]
    if (OSAtomicCompareAndSwap64Barrier(
        ^
/usr/include/libkern/OSAtomicDeprecated.h:645:9: note: 'OSAtomicCompareAndSwap64Barrier' has been explicitly marked deprecated here
bool    OSAtomicCompareAndSwap64Barrier( int64_t __oldValue, int64_t __newValue,
        ^
```

**Comment by michael-berlin** [comment]
That means that the removal of `-Werror` doesn't have the right effect? Maybe we need a different compiler flag to disable that check?

Can you verify that `-Werror` is gone from the `c++` command line invocation?

```sh
cd $VTROOT/dist/grpc/grpc/third_party/protobuf

# Use -j1 to disable parallel builds (1 simultaneous invocation only).
make -j1
```

**Comment by Rastusik** [comment]
yes, the removal of the -Werror flag doesn't change anything :)

the commands you wanted me to run print this:

```
~/DEV/vitess/dist/grpc/grpc/third_party/protobuf • make -j1   
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in .
make[2]: Nothing to be done for `all-am'.
Making all in src
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
make[3]: Nothing to be done for `all-am'.
```

**Comment by michael-berlin** [comment]
That's weird. That should have failed.

Martin, do you maybe have time to go through with me on Slack? I sent you a DM there.

**Comment by Rastusik** [comment]
no problem, let's do it, if you have time :)

**Comment by michael-berlin** [comment]
Summary of the debugging session on Slack:

* grpc passes `-Werror` to the protobuf Makefile and therefore the patching didn't work
* setting the environment variable `CPPFLAGS="-Wno-deprecated-declarations"` has the effect that protobuf and grpc compile without errors

@Rastusik created a PR for this: https://github.com/youtube/vitess/pull/2128
