### ISSUE TITLE
OSX 10.12 and PHP client error: Trying to connect an http1.x server

### ISSUE THREAD

**Issue by Rastusik** [youtube/vitess#2131]
I’m getting this error from the PHP client:

```
{
  "created":"@1475881058.787187000",
  "description":"Failed parsing HTTP/2",
  "file":"/private/tmp/pear/temp/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.c",
  "file_line":2022,
  "grpc_status":14,
  "referenced_errors":[{
    "created":"@1475881058.787155000",
    "description":"Expected SETTINGS frame as the first frame, got frame type 80",
    "file":"/private/tmp/pear/temp/grpc/src/core/ext/transport/chttp2/transport/parsing.c",
    "file_line":479
  }
  {
    "created":"@1475881058.787180000",
    "description":"Trying to connect an http1.x server",
    "file":"/private/tmp/pear/temp/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.c",
    "file_line":1995,
    "http_status":400
  }]
}
```

does anybody have a clue what might be wrong?

Looks like the PHP GRPC extension has got some sort of problems with output from Vitess, but this didn’t occur in OSX 10.11 with the same version of the GPRC extension. I realized this problem before I was trying to build Vitess on 10.12 - this was the reason why I found that I'm unable to build GRPC under 10.12. I wass getting this error message with my older Vitess build (compiled on OSX 10.11) which I tried to run on 10.12

What I'm exactly doing is that I’m trying to query VTCombo from examples/demo using a php script.

Just for the record - I'm using PHP Grpc extension in version 1.0.0 ( https://pecl.php.net/package/gRPC )

**Comment by enisoc** [comment]
Are you sure you're connecting to the vtgate grpc port on vtcombo, rather than the status port? Are you using a particular PHP script we provide, or a modified one? If modified, can you share it?

**Comment by Rastusik** [comment]
I'm pretty sure, I'm running VTCombo from examples/demo and the default port there is 12345 and the vtcdl port is 12346 ... Both are open (checked with telnet) and both are closed when I shut down the examples/demo script. I also tried to connect to the server using adminer and using the modified php client script in examples/local (I just modified sql queries)

**Comment by Rastusik** [comment]
strange thing is that the demo works, so it looks like a PHP specific error

**Comment by michael-berlin** [comment]
Could this be related with our switch to gRPC 1.0.0? We switched to gRPC 1.0.0 here: https://github.com/youtube/vitess/pull/2012

When I google for "Expected SETTINGS frame as the first frame, got frame type 80", I find only this bug report: https://github.com/grpc/grpc/issues/7726

As a first step, let's reproduce the issue and then we can dig deeper to check if it's a gRPC issue.

@Rastusik I've used the following procedure below to run client.php against vtcombo.

I don't run into the problem which you're encountering :( Can you please post your instructions as well?

Re-install gRPC with php enabled.
```sh
# Remove the existing grpc installation.
$ rm -rf $VTROOT/dist/grpc
$ export INSTALL_GRPC_PHP="$HOME/.phpenv/lib"
$ ./bootstrap.sh 
```

Setup PHP.
```sh
$ export PATH="$HOME/.phpenv/bin:$PATH"
$ ./travis/php_init.sh
```
Run vtcombo. Note that the --schema_dir must be an existing directory, but it will be ignored by the script. Instead, --default_schema_dir will be used eventually.
To shutdown vtcombo, please <Enter> in that terminal.
```sh
$ ./py/vttest/run_local_database.py --port 12345 --proto_topo 'keyspaces { name: "test_keyspace" shards { name: "0" } } cells: "test"' --web_dir $VTTOP/web/vtctld --schema_dir '.' --default_schema_dir $VTTOP/examples/local
# Verify the schema ("messages" table should be there).
$ vtctlclient --server localhost:12346 GetSchema test-0000000001
```

Run client.php against vtcombo.
```sh
$ php client.php --server localhost:12346
Inserting into master...
Reading from master...
(11, 1476404680339096064, V is for speed)
(35, 1476404680324784128, V is for speed)
(74, 1476404680342761984, V is for speed)
Reading from replica...
(11, 1476404680339096064, V is for speed)
(35, 1476404680324784128, V is for speed)
(74, 1476404680342761984, V is for speed)
```

**Comment by Rastusik** [comment]
@michael-berlin I'm sorry it looks like I did something wrong. Your example works for me as well as the demo example now. 

I was connecting to port 12345 but now I see that I should be connecting to 12346 ... I was sure that 12345 is the vtgate port, and 12346 is the vtctld port. But it looks like vtgate and vtctld are both running on port 12346, and 12345 is for vtctld ui, which I forgot.

I'm really sorry, I'm closing the issue now.

**Comment by michael-berlin** [comment]
No worries @Rastusik !

I'm glad we found the problem :)
