### ISSUE TITLE
Build break on master branch?

### ISSUE THREAD

**Issue by yancl** [youtube/vitess#2142]
Hi,
  When exec `bootstrap.sh`, I saw it needs install grpc&protobuf using `travis/install_grpc.sh`.
But there is no `Makefile` generated after `make` executed in grpc root dir. so the `make install`
while not work for `third_party/protobuf`, will you please make a check(maybe using `./autogen.sh && ./configure && make instead`?)?

```
//install_grpc.sh
# build everything
make

# install protobuf side (it was already built by the 'make' earlier)
cd third_party/protobuf
if [ -n "$grpc_dist" ]; then
  make install prefix=$grpc_dist/usr/local
else
  make install
fi
```

Also the gmock link in the protobuf with grpc v1.0.0 no longger available

```
commit bba446bbf2ac7b0b9923d4eb07d5acd0665a8cf0
Author: Feng Xiao <xfxyjwf@gmail.com>
Date:   Thu Aug 25 14:28:59 2016 -0700

    Update gmock links.

    The original link is no longer available.

    Change-Id: I2976d3f19c8e818689549fb31ff20af8eae92a07
```

**Comment by enisoc** [comment]
In the past, we've seen this happen if you have protobuf installed system-wide already. The grpc make command will skip generating the protobuf Makefile in that case. Do you have protobuf installed already?

For the gmock problem, I'm not sure what's best. Ideally we could wait until a new grpc patch release so we don't have to pin a commit between releases, but I don't know when their next release will be. Is the gmock problem causing the build to actually fail?

**Comment by yancl** [comment]
Thanks, I have protobuf installed on my system and the gmock download link broken make the compile failed, Now I manually fix the link and make it works. Maybe we need wait for grpc's next release. thanks again:)
