### ISSUE TITLE
[Vitess UI] :Seconds Behind Master Parameter does not reflect the correct stats

### ISSUE THREAD

**Issue by ashudeep-sharma** [youtube/vitess#2158]
We were trying to promote slave to Master and got the following error:
_./vtctld.ekl-sal-srms-vtctl-none-6029838.vitess.log.INFO.20160919-125415.12982:I1017 15:03:01.085967   12982 locks.go:344] Locking shard srms/-40 for action PlannedReparentShard(nm-0000000007)
./vtctld.ekl-sal-srms-vtctl-none-6029838.vitess.log.INFO.20160919-125415.12982:I1017 15:03:05.063958   12982 locks.go:380] Unlocking shard srms/-40 for action PlannedReparentShard(nm-0000000007) with error master-elect tablet nm-0000000007 failed to catch up with replication or be upgraded to master: rpc error: code = 2 desc = TabletManager.PromoteSlaveWhenCaughtUp on nm-0000000007 error: WAIT_UNTIL_SQL_THREAD_AFTER_GTIDS() failed: gtid_mode is OFF_

The error was as expected, we checked the UI but the Seconds Behind Master Parameter was showing as 0.
We logged into the slave and checked that there was a significant replication Lag in the slave, but the same has not been reflected in the UI.

Attaching the UX snapshot for the same.
<img width="405" alt="screen shot 2016-10-18 at 12 42 41 pm" src="https://cloud.githubusercontent.com/assets/12492010/19467735/66926fa8-9530-11e6-9692-737f0da7f011.png">

**Comment by alainjobart** [comment]
Are you running vttablet with the -enable_replication_reporter flag? If
not, we will not query the database for replication lag...

**Comment by ashudeep-sharma** [comment]
Yeah, we were not using it in our production Environment, however i tried testing it out in one of our staging environment and it works great :).

Closing this issue.
