### ISSUE TITLE
Support VitessDatabaseMetaData.getUserName() 

### ISSUE THREAD

**Issue by tjlee** [youtube/vitess#2163]
Is there any plans to implement method `com.flipkart.vitess.jdbc.VitessDatabaseMetaData.getUserName()` ?

**Comment by enisoc** [comment]
@harshit-gangal what do you think?

**Comment by harshit-gangal** [comment]
This username is the one which is provided in connection url or in the connection property.
@tjlee If you want that, this can be done.

**Comment by harshit-gangal** [comment]
@tjlee I checked the logs and found two issues there.

1. Use of getUserName method
We will implement this method.

2. Use of setFetchSize method
This method is used to provide hint to driver to load less data from database.
If there is 100 record and fetchSize is set to 10 then driver calls database 10 times to retrieve all results. This helps in less memory consumption.
To support these kind of use cases, Vitess already support STREAM option which can be set as connection property or in connection url with EXECUTE_TYPE=STREAM, default is SIMPLE.
@enisoc To avoid the Exception, we can either ignore this call or at least check if EXECUTE_TYPE is set to STREAM. Let us know your feedback.

**Comment by tjlee** [comment]
@harshit-gangal thank you.
