### ISSUE TITLE
ChangeSlaveType requires a restart of replication when choosing replica

### ISSUE THREAD

**Issue by rnavarro** [youtube/vitess#2195]
Hey Guys,

I noticed that when changing a tablet from rdonly to replica with ChangeSlaveType I ALSO had to run StopSlave and StartSlave, otherwise the new replica type wouldn't starting sending ACK's to the master for semi-sync replication.

I suspect that we want the same action when moving from replica --> rdonly, to disable the ACK

Could we get that fixed?

**Comment by alainjobart** [comment]
That sounds like something we should be doing, I'll look at it on Monday.

**Comment by alainjobart** [comment]
The PR should fix this, let me know if it's not the case.
