### ISSUE TITLE
go/vt/vitessdriver: (go1.8) support for additional features 

### ISSUE THREAD

**Issue by kardianos** [youtube/vitess#2204]
For the go/vt/vitessdriver package.

Many new important features will land in go1.8. Please see document:
https://docs.google.com/document/d/1F778e7ZSNiSmbju3jsEWzShcb8lIO4kDyfKDNm4PNd8/edit?usp=sharing for the full list.

Because these features are new we want drivers to implement them before they are released. Ideally they should be implemented by 2016-12-12 to allow for any driver provided feedback from implementation if necessary.

**Comment by michael-berlin** [comment]
Sugu, can you please look into this?
