### ISSUE TITLE
Adding SSL support to the JDBC driver

### ISSUE THREAD

**Issue by steve-perkins** [youtube/vitess#2209]
My company is currently using MySQL in a Java-based project, and is considering a migration effort to Vitess.  However, we use SSL for our database connections today, and have a requirement to continue doing so.  Unfortunately, the Vitess JDBC driver does not support SSL.  

I don't think it would too difficult to write a pull request that adds support, and we are happy to do so!  However, I'd like to gauge interest first, to determine how best to proceed.

The proposed PR would look for a `useSSL=true` option in the JDBC connection string, which is the same as default MySQL behavior ([see docs](https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-using-ssl.html)).  Presumably the `VitessDriver` class would look for the SSL keystore and truststore using standard MySQL conventions (see previous link)... and there would most likely be an overloaded version of the `VitessVTGateManager.getVtGateConn()` method to establish an `RpcClient` with SSL.

If there would be interest in potentially merging such a PR, then we'll schedule the development process to align with that goal (i.e. make a standard fork of this repo, and sign contributor agreements).  The PR would probably be submitted in 3 weeks or so. 

However, please let us know if there definitely wouldn't be interest... due to plans for an alternative approach, mismatched timelines, etc.  In that case, we could save some time and effort by maintaining our own private fork... skipping the contributor docs, stripping out the parts of this repo that we don't need, and switching the build system over to Gradle since that's what our internal CI system normally uses.

Thanks!

**Comment by sougou** [comment]
@alainjobart already did the work to support SSL at the gRPC layer. I thought @harshit-gangal did the JDBC part for it. We'll wait for him to reply.

**Comment by sougou** [comment]
While we wait for @harshit-gangal, can you check if this thread answers your question: https://groups.google.com/forum/#!searchin/vitess/context$20ssl%7Csort:relevance/vitess/AX_VFpnWcqU/szcf4d5eCQAJ. I think all you have to do is pass the SSL parameters in through the context.

**Comment by steve-perkins** [comment]
It appears that this thread is talking about SSL support down at the gRPC level.  I assumed that support was already there, and in great shape.  There will be a bit more development required if that's not the case!

Either way, the JDBC layer still needs:

1. a way to determine from the URL string that SSL mode should be used, and 

1. logic to request SSL at the gRPC layer when that is the case.

Perhaps this is a tangent, but there's a lot of other stuff going on that discussion thread you linked above.  It looks like they're trying to use SSL keys in "PEM" format, rather than Java-friendly "JKS" format... and so they're having to pull in some native OpenSSL dependency to make it work.  That seems a bit backwards from a Java perspective.  Generally you would work with "JKS" files at the point of constructing an "SSLContext", and if they need conversion then you would handle it before reaching that point.  BouncyCastle is probably the gold standard for that sort of thing, but there are other options too.

Anyhoo... my hope is that SSL support is there and working fine at the gRPC layer, and all we're talking about is just a URL-parsing tweak for the JDBC driver to use that support.

**Comment by harshit-gangal** [comment]
SSL support is there in GRPC layer. This needs to be implemented in the low level grpc & java client and later used in the JDBC Driver.

**Comment by steve-perkins** [comment]
Hi @harshit-gangal, I was scheduling some time in early December to work on this and submit a pull request.  I am more than delighted to NOT do this (!)... just checking on whether you assigning this issue means that you have plans to do that change sooner?

**Comment by harshit-gangal** [comment]
We currently do not need SSL support. So If you are willing to take it then proceed forward and submit the PR. :)
