### ISSUE TITLE
MySQL 5.7 new column type support

### ISSUE THREAD

**Issue by bbeaudreault** [youtube/vitess#2210]
According to https://groups.google.com/forum/#!searchin/vitess/json%7Csort:relevance/vitess/-jiqEC11Zww/fkOyYdfnAAAJ, Vitess does not include support for any of the new column types in 5.7. @sougou mentioned it should be both possible and fairly easy to add support.

Please add support for JSON and other new column types in MySQL 5.7

**Comment by sougou** [comment]
Let us know if it's a showstopper, or if you need it by a certain time. We'll prioritize it accordingly.

**Comment by bbeaudreault** [comment]
Thanks @sougou. Not a show-stopper yet. We're beginning to investigate vitess as a clustering solution for our 300+ isolated databases. All of those are MySQL 5.7, but only a handful use the new column types. So we have plenty of work and verification to do before it becomes a blocker for those final databases. Let's say Q1 2017 would be great, if possible.

**Comment by derekperkins** [comment]
We're looking to migrate to Vitess, but this would be a showstopper for us. We heavily use JSON fields.

**Comment by bbeaudreault** [comment]
Great, thanks @sougou!

**Comment by sougou** [comment]
New constructs might have been introduced in the grammar. I'll keep this issue open to make sure those are also added.

**Comment by derekperkins** [comment]
https://dev.mysql.com/doc/refman/5.7/en/json-function-reference.html
