### ISSUE TITLE
VitessInputFormat cannot query tables that match SQL keywords

### ISSUE THREAD

**Issue by smith-m** [youtube/vitess#2222]
Part of the VitessInputFormat process of getting splits routes queries by querying tablets without escaping the tablename. 

For example a SplitQuery with key of "id":
>Select * from \`order\`

Will be translated to 

>Select id from order limit 0

instead of

>Select id from \`order\` limit 0

**Comment by sougou** [comment]
@erzel you're probably using a simple string to process the table name. You should instead use sqlparser.TableIdent: https://github.com/youtube/vitess/blob/master/go/vt/sqlparser/ast.go#L1735. Similar rules for column names (ColIdent).

**Comment by erzel** [comment]
Hi Smith,

Can you try again? I recently updated the SplitQuery code that VitessInputFormat calls to the new version which shouldn't suffer from this issue.

 Thanks,

 Erez.
