### ISSUE TITLE
Vitess Build Failure on OSX

### ISSUE THREAD

**Issue by ashudeep-sharma** [youtube/vitess#2227]
The Current Master branch make build on Mac OS X fails with the following exception:
It works fine on linux but OS X has problem.

_make build
Mon Nov 7 12:32:53 IST 2016: Building source tree
go/vt/vtgate/tx_conn.go:8:2: cannot find package "context" in any of:
	/Users/ashudeep.sharma/go/vitess/src/github.com/youtube/vitess/vendor/context (vendor tree)
	/usr/local/opt/go/libexec/src/context (from $GOROOT)
	/Users/ashudeep.sharma/go/vitess/src/context (from $GOPATH)
make: *** [build] Error 1_

I made the following changes to go/vt/vtgate/tx_conn.go and go/vt/workflow/long_polling.go

**import golang.org/x/net/context** 
instead of 
**import context** 
and it works fine.

**Comment by ashudeep-sharma** [comment]
The fix has been merged in https://github.com/youtube/vitess/commit/a2cd82037a01ca33b65aac3b4b7527ed64e850d5 , verified that the latest master branch has no issues.

**Comment by michael-berlin** [comment]
The real solution is to upgrade your Go installation to 1.7. Please do this soon and let us know if this is a problem for you.

Go 1.7 also brings many speed improvements i.e. it's worth the effort :)

A couple weeks ago we started requiring Go 1.7. That's the reason why the code above passed our tests in the first place.

For now you may be safe using Go 1.5 or 1.6, but in the future other changes may get committed which require 1.7.

**Comment by ashudeep-sharma** [comment]
Thanks Michael, i upgraded my Go version to 1.7 and verified that it works fine with the older changes on OS X. Given that its recomended to use Go 1.7 here http://vitess.io/getting-started/local-instance.html , should we revert the changes and add a comment under the **OS X** section to make sure that using brew the user should install Go 1.7 , i can see a comment for installing Go 1.7 under **Ubuntu and Debian** Section but not in **OS X** .

**Comment by michael-berlin** [comment]
How do you usually install Go on macOS?

It looks like we don't have instructions for Go in the macOS section at all so far?

re: the change. No, we don't have to revert it. Both versions work.

**Comment by ashudeep-sharma** [comment]
I installed it using brew, my brew was not updated so it was installing Go 1.6, i updated the brew and then installed Go using _brew install go_ command which installed go1.7.3 darwin/amd64, after that everything worked fine.
