### ISSUE TITLE
Backup failure leaves tablet unusable

### ISSUE THREAD

**Issue by rnavarro** [youtube/vitess#2238]
I've noticed that sometimes when backing up a vttablet using the google storage APIs return an error, for example:

> W1110 01:00:07.587892      13 rpc_server.go:67] TabletManager.Backup(concurrency:4 )(on usc1b-0000001503 from ) error: can't backup files: googleapi: Error 503: Backend Error, backendError

When this happens the backup process doesn't recover gracefully. MySQL isn't restarted and the tablet just stays in a broken state unless we manually go in an reset mysql.

We should recover from these errors more gracefully and start MySQL again

**Comment by alainjobart** [comment]
The fix for this is included in PR: https://github.com/youtube/vitess/pull/2263

**Comment by alainjobart** [comment]
The fix has been merged.

**Comment by sougou** [comment]
@rnavarro reports that there may be a regression here.
