### ISSUE TITLE
Can't use keywords as column names

### ISSUE THREAD

**Issue by tirsen** [youtube/vitess#2249]
Even though it is valid to use many/all keywords as table names in MySQL this is not handled by the Vitess parser.

MySQL:
```
mysql> select virtual from issued_cards;
Empty set (0.00 sec)```
```

Vitesss:
```
parse_test.go:570: input: select /* keyword */ virtual from b, err: syntax error at position 29 near 'virtual'```
```

**Comment by tirsen** [comment]
A work around is to use backticks to quote the column names but this SQL is generated for us by Hibernate. I'm not sure to what degree I can change that.

**Comment by tirsen** [comment]
I managed to work around it by declaring the column to be quoted in the property definition:
```
@Column(name="`virtual`")
private boolean virtual;
```

So this isn't blocking me currently.

**Comment by sougou** [comment]
Looks like this was fixed by @bbeaudreault.
