### ISSUE TITLE
Can't run information_schema queries

### ISSUE THREAD

**Issue by tirsen** [youtube/vitess#2250]
If I run a query like:
```
SELECT table_comment FROM information_schema.tables
```

I get an error with something like: "No such keyspace id: information_schema"

The easiest is just to pass these queries on to the MySQL server.

**Comment by sougou** [comment]
Can you post the exact error message? I think vttablet will allow information_schema queries. It's likely that this is failing at the VTGate layer.

**Comment by tirsen** [comment]
Actually I think it does work. I think the issue is that it uses a named and not positional bind parameter which doesn't seem to be supported by the JDBC driver.

**Comment by tirsen** [comment]
Nope, you're right it does work now.

**Comment by tirsen** [comment]
So we probably do want to expose this some better way after all. I just started experimenting with vertical resharding and created a keyspace with a `served_from`. The work around for running information_schema queries in the JDBC driver (just to run them against tablet 1) doesn't work in this case because there is no tablet 1. Maybe I can get around with by consulting `GetSrvKeyspace` but then it's starting to get messy. We should probably track that with a different issue though of course.

**Comment by sougou** [comment]
I'll reopen this to track the end to end feature request.

**Comment by bbeaudreault** [comment]
I'm also interested in this and other system tables, such as mysql.user

**Comment by sougou** [comment]
@tirsen #2646 should allow you to connect to a specific `keyspace/shard` and run information_schema queries. Let me know if this will be sufficient.

**Comment by sougou** [comment]
With #2815, you should be able to run information_schema queries through the `use` function or by also specifying `keyspce:shard` as the target.

**Comment by bbeaudreault** [comment]
Does this work automatically for unsharded keyspaces?

**Comment by sougou** [comment]
Ahh. Forgot about this use case. Let's keep the issue open till it's addressed.

**Comment by sougou** [comment]
#2858 should address this now.
