### ISSUE TITLE
Receiving RPC Error as 10 instead of 9 for Not In Transaction Error

### ISSUE THREAD

**Issue by harshit-gangal** [youtube/vitess#2251]
java.sql.SQLNonTransientException: Vitess RPC error: code: UNKNOWN_ERROR
message: "execInsertSharded: target: ..., used tablet: (...), vttablet: rpc error: **code = 10** desc = gRPCServerError: not_in_tx: Transaction 1479214237661112363: not found, vtgate: http://localhost:15001/"

Because of this the client is throwing SQLNonTransientException instead of SQLRecoverableException

**Comment by sougou** [comment]
This should be fixed now.
