### ISSUE TITLE
Backup hook for pre/post-processing files

### ISSUE THREAD

**Issue by enisoc** [youtube/vitess#2256]
A user requested the ability to pipe files through a user-supplied command before uploading to backup storage, and through another command upon downloading. The user's specific need is user-controlled encryption/decryption of files before transit to remote backup storage. For example, they would pipe through appropriate `gpg` commands.

The reason for doing it as a pipe rather than expecting the hook to place the processed files in an output directory is so we avoid taking up ~2x the disk space upon backup/restore.

We already have a simple hook system, but it doesn't yet support running the hook command as a pipe. If we add that capability, it would address this need while giving the user the flexibility to plug in any command, and it would apply to all backup storage plugins without having to modify them.

**Comment by alainjobart** [comment]
This is ready for review in this PR: https://github.com/youtube/vitess/pull/2263

**Comment by alainjobart** [comment]
The PR has been merged, this is implemented. Use the backup_storage_hook command line parameter to specify a hook script to run. It will be called with '-operation write' or '-operation read' depending on the direction, if writing or reading a backup. See test/vthook-test_backup_transform for an example.

Also, if the hook actually compresses the data, there is no need for the backup code to compress it, so just add the -backup_storage_compress=false parameter to vttablet to disable that.
