### ISSUE TITLE
SHOW TABLE queries doesn't work in the JDBC driver with a served_from keyspace

### ISSUE THREAD

**Issue by tirsen** [youtube/vitess#2271]
The JDBC driver works around information schema queries by running those type of queries against the first tablet in a keyspace. This doesn't work for a keyspace which doesn't have tablets and instead `served_from` a separate keyspace.

We need a different strategy for information schema queries which uses the routing information correctly.

**Comment by tirsen** [comment]
I thought this only impacted our automated tests but It seems at start up Hibernate runs a bunch of "SHOW xyz" queries to determine the capabilities of the underlying database. So this will prevent us from doing online vertical resharding in production as well.

**Comment by harshit-gangal** [comment]
This was the hack we did to serve horizontal sharding use case. Now you have vertical sharding. This can be supported mostly by having this query support in VTGate.

**Comment by tirsen** [comment]
Yep agreed completely. AFAICT there is not enough information in the client to be able to serve these sort of queries. So it should be supported by VTGate natively.

**Comment by sougou** [comment]
This is now all done through VTGate.
