### ISSUE TITLE
Support context in Go 1.8 database/sql driver

### ISSUE THREAD

**Issue by derekperkins** [youtube/vitess#2273]
One of our biggest issues with Go right now is that database/sql doesn't respect context, so queries stack up when they should have timed out. 1.8 has merged support for database context, with details [here](https://docs.google.com/document/d/1F778e7ZSNiSmbju3jsEWzShcb8lIO4kDyfKDNm4PNd8/edit). Do you plan on adding support for the vitess driver?

**Comment by sougou** [comment]
This was done with #2213. From what I hear, it's experimental. So, fingers crossed.
