### ISSUE TITLE
VerticalSplitClone shouldn't allow an empty -tables flag

### ISSUE THREAD

**Issue by tirsen** [youtube/vitess#2282]
It actually copies all of the data but the filtered replication it sets up afterwards doesn't replicate any of the tables.

**Comment by michael-berlin** [comment]
@wangyipei01 I've assigned this issue to you.

This is a very easy fix and ideal to get your feet wet with our Go code.

**Comment by alainjobart** [comment]
This was fixed in https://github.com/youtube/vitess/pull/2294
