### ISSUE TITLE
Crash in CopySchemaShard

### ISSUE THREAD

**Issue by tirsen** [youtube/vitess#2287]
I think the issue is that the target keyspace didn't have a master. It was resolved after running `InitShardMaster`.

> -> % ./lvtctl.sh CopySchemaShard -tables ...tables... from_keyspace/0 to_keyspace/0
>
> E1122 14:25:03.233821   39796 main.go:43] Remote error: rpc error: code = 2 desc = uncaught vtctl panic: runtime error: invalid memory address or nil pointer dereference, /usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:458 (0x2cce3);	gopanic: reflectcall(nil, unsafe.Pointer(d.fn), deferArgs(d), uint32(d.siz), uint32(d.siz));/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:62 (0x2b83d);	panicmem: panic(memoryError);/usr/local/Cellar/go/1.7.3/libexec/src/runtime/sigpanic_unix.go:24 (0x41f04);	sigpanic: panicmem();/Users/jontirsen/Development/go/src/github.com/youtube/vitess/go/vt/topo/topoproto/tablet.go:63 (0x2e15c3);	com/youtube/vitess/go/vt/topo/topoproto.TabletAliasUIDStr: return fmt.Sprintf("%010d", ta.Uid);/Users/jontirsen/Development/go/src/github.com/youtube/vitess/go/vt/zktopo/tablet.go:27 (0xd393f);	com/youtube/vitess/go/vt/zktopo.TabletPathForAlias: return fmt.Sprintf("/zk/%v/vt/tablets/%v", alias.Cell, topoproto.TabletAliasUIDStr(alias));/Users/jontirsen/Development/go/src/github.com/youtube/vitess/go/vt/zktopo/tablet.go:77 (0xd4820);	com/youtube/vitess/go/vt/zktopo.(*Server).GetTablet: zkTabletPath := TabletPathForAlias(alias);/Users/jontirsen/Development/go/src/github.com/youtube/vitess/go/vt/topo/tablet.go:215 (0x77335);	com/youtube/vitess/go/vt/topo.Server.GetTablet: value, version, err := ts.Impl.GetTablet(ctx, alias);/Users/jontirsen/Development/go/src/github.com/youtube/vitess/go/vt/wrangler/schema.go:30 (0x111be6);	com/youtube/vitess/go/vt/wrangler.(*Wrangler).GetSchema: ti, err := wr.ts.GetTablet(ctx, tabletAlias);/Users/jontirsen/Development/go/src/github.com/youtube/vitess/go/vt/wrangler/schema.go:363 (0x1155ff);	com/youtube/vitess/go/vt/wrangler.(*Wrangler).compareSchemas: destSd, err := wr.GetSchema(ctx, destAlias, tables, excludeTables, includeViews);/Users/jontirsen/Development/go/src/github.com/youtube/vitess/go/vt/wrangler/schema.go:263 (0x1144c5);	com/youtube/vitess/go/vt/wrangler.(*Wrangler).CopySchemaShard: diffs, err := wr.compareSchemas(ctx, sourceTabletAlias, destShardInfo.MasterAlias, tables, excludeTables, includeViews);/Users/jontirsen/Development/go/src/github.com/youtube/vitess/go/vt/wrangler/schema.go:245 (0x114295);	com/youtube/vitess/go/vt/wrangler.(*Wrangler).CopySchemaShardFromShard: return wr.CopySchemaShard(ctx, sourceShardInfo.MasterAlias, tables, excludeTables, includeViews, destKeyspace, destShard, waitSlaveTimeout);/Users/jontirsen/Development/go/src/github.com/youtube/vitess/go/vt/vtctl/vtctl.go:1945 (0x340990);	com/youtube/vitess/go/vt/vtctl.commandCopySchemaShard: return wr.CopySchemaShardFromShard(ctx, tableArray, excludeTableArray, *includeViews, sourceKeyspace, sourceShard, destKeyspace, destShard, *waitSlaveTimeout);/Users/jontirsen/Development/go/src/github.com/youtube/vitess/go/vt/vtctl/vtctl.go:2287 (0x343b37);	com/youtube/vitess/go/vt/vtctl.RunCommand: return cmd.method(ctx, wr, subFlags, args[1:]);/Users/jontirsen/Development/go/src/github.com/youtube/vitess/go/vt/vtctl/grpcvtctlserver/server.go:57 (0xbb16c);	com/youtube/vitess/go/vt/vtctl/grpcvtctlserver.(*VtctlServer).ExecuteVtctlCommand: return vtctl.RunCommand(stream.Context(), wr, args.Args);/Users/jontirsen/Development/go/src/github.com/youtube/vitess/go/vt/proto/vtctlservice/vtctlservice.pb.go:105 (0x3fd3c7);	com/youtube/vitess/go/vt/proto/vtctlservice._Vtctl_ExecuteVtctlCommand_Handler: return srv.(VtctlServer).ExecuteVtctlCommand(m, &vtctlExecuteVtctlCommandServer{stream});/Users/jontirsen/Development/go/src/github.com/youtube/vitess/vendor/google.golang.org/grpc/server.go:716 (0x26f542);	com/youtube/vitess/vendor/google.golang.org/grpc.(*Server).processStreamingRPC: appErr = sd.Handler(srv.server, ss);/Users/jontirsen/Development/go/src/github.com/youtube/vitess/vendor/google.golang.org/grpc/server.go:800 (0x270456);	com/youtube/vitess/vendor/google.golang.org/grpc.(*Server).handleStream: s.processStreamingRPC(t, stream, srv, sd, trInfo);/Users/jontirsen/Development/go/src/github.com/youtube/vitess/vendor/google.golang.org/grpc/server.go:449 (0x27525b);	com/youtube/vitess/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1: s.handleStream(st, stream, s.traceInfo(st, stream));/usr/local/Cellar/go/1.7.3/libexec/src/runtime/asm_amd64.s:2086 (0x5ede1);	goexit: BYTE	$0x90	// NOP;

**Comment by wangyipei01** [comment]
manually closed the issue, due to wrong issue number in pull request to fix this issue.
