### ISSUE TITLE
vtctl SetShardTabletControl doesn't do what it says

### ISSUE THREAD

**Issue by tirsen** [youtube/vitess#2289]
Either the command needs to be fixed or the documentation.

1. There is no `--blacklisted_tables` flag, it's called `--tables`
1. If I specify `--remove` I expect the table to be removed from the blacklist, instead the entire `tablet_controls` record seem to be removed

**Comment by alainjobart** [comment]
Fixing the doc there: https://github.com/youtube/vitess/pull/2357
