### ISSUE TITLE
uint64 support in go database/sql driver

### ISSUE THREAD

**Issue by derekperkins** [youtube/vitess#2299]
`database/sql` doesn't support `uint64` values with the high bit set by default, but they do have a way for drivers to support it. Does vitess support uint64 values?
https://github.com/golang/go/issues/9373

**Comment by derekperkins** [comment]
According to the conversation @sougou and I had today on Slack, there is no way to support `uint64` natively. The workaround is to fork `database/sql` to the user source tree, adding support there and using the same driver.

There is a Go 1.9 milestone issue that would add driver support for custom database types.
https://github.com/golang/go/issues/13567 This would allow for true support from Vitess.

**Comment by sougou** [comment]
Looks like this is not a pressing issue any more. Let's hope Go fixes this in their future release.

**Comment by derekperkins** [comment]
Sounds good to me. Not a blocker for us.

**Comment by derekperkins** [comment]
FYI, this was just merged into Go 1.9. https://golang.org/cl/38533
