### ISSUE TITLE
Interacting with Kubernetes PetSet/StatefulSet

### ISSUE THREAD

**Issue by derekperkins** [youtube/vitess#2305]
> We restore the tablets from the backup by restarting them. Since the Kubernetes pods lose their state after a shutdown, they'll always restore from the latest backup and then connect to the master to catch up on changes which were made after the backup was taken.

With PetSets in Kubernetes 1.4, which are becoming StatefulSets in 1.5, will this change how Vitess interacts with persistent volumes?

**Comment by enisoc** [comment]
Yes, StatefulSet makes it much easier to run Vitess on Persistent Volumes, which means tablets won't have to restore from backup every time they get rescheduled. In the case when you intentionally want to force a restore from backup (e.g. for a [Pivot](http://vitess.io/user-guide/pivot-schema-changes.html)) you would need to use the new [RestoreFromBackup](http://vitess.io/reference/vtctl.html#restorefrombackup) command on a running tablet.

You can see an example Helm Chart that can optionally use PVs and the alpha PetSet in 1.4 here:

https://github.com/youtube/vitess/tree/master/helm/vitess

To enable them, you would need to set `controllerType` and `dataVolumeType` appropriately in the [values.yaml](https://github.com/youtube/vitess/blob/master/helm/vitess/values.yaml) (or in an override values file passed to the `helm install` command).

**Comment by derekperkins** [comment]
This is great!

**Comment by sougou** [comment]
This can be closed now?

**Comment by enisoc** [comment]
I believe so. The Helm Chart has been updated to show how the beta StatefulSet in Kubernetes 1.5+ can be used with Vitess.
