### ISSUE TITLE
Confusing error on autoinc seq table query

### ISSUE THREAD

**Issue by tirsen** [youtube/vitess#2323]
If there is an error with the query that generates a new id for autoinc then it looks like the error is due to the original INSERT. Since they usually go to separate keyspaces it actually looks like Vitess has misrouted the INSERT.

**Comment by tirsen** [comment]
Let me know if you need clarification. I think you need to do something about the error coming out of `handleGenerate` in `execInsertSharded`.

**Comment by sougou** [comment]
Can you post the exact error message you saw? That will help me identify the code path.

**Comment by sougou** [comment]
Is this still a problem? If so, can you show me the error message. Otherwise, I'll close this out.
