### ISSUE TITLE
Revisit varchar column sizes that store GTIDs

### ISSUE THREAD

**Issue by sougou** [youtube/vitess#2327]
@adkhare reports the following error:
```
mysql> alter table _vt.reparent_journal modify replication_position varchar(64000);
ERROR 1074 (42000): Column length too big for column 'replication_position' (max = 21845); use BLOB or TEXT instead
```
The MySQL version is: 5.6.32-78.1

Also, @enisoc reports that this needs fixing: https://github.com/youtube/vitess/blob/034f75da548eb4f6302d59f930afd83e8f951c7a/go/vt/binlog/binlogplayer/binlog_player.go#L460

**Comment by alainjobart** [comment]
You also need to change the charset to latin1, and collation to latin1_bin, for this to work.

**Comment by alainjobart** [comment]
The full command is:

ALTER TABLE _vt.reparent_journal MODIFY COLUMN replication_position VARCHAR(64000) CHARACTER SET latin1 COLLATE latin1_bin;

**Comment by alainjobart** [comment]
Still need to fix binlog player, so keeping this issue.

**Comment by alainjobart** [comment]
https://github.com/youtube/vitess/pull/2329 has the fix and has been submitted.
