### ISSUE TITLE
FileCredentialsServer not working, potentially due to issues with pointers

### ISSUE THREAD

**Issue by bbeaudreault** [youtube/vitess#2338]
I've been trying to get FileCredentialsServer, and was able to validate that the code is properly parsing and retrieving the username/password combos from the file I configured. However, they don't make their way into the vttablet due, i think, to some pointer issues.

Stepping through the code, I noticed https://github.com/youtube/vitess/blob/master/go/vt/dbconfigs/dbconfigs.go#L100

This expects a pointer to be passed in, dereferences the pointer to create a copy, modifies the copy with the User/Pass, and returns that copy.

However, a few functions below, in `Init(socketFile string, flags DBConfigFlag) (DBConfigs, error)` you'll see that the return value is not used. In fact `initConnParams ` drops that return value on the floor. I think this is expecting that the function will use the pointer to update the creds based on the credential server.

I was able to fix this bug in my own fork, by modifying `initConnParams ` to return the copied ConnParams, and fix Init to expect and use that return value. See the diff here https://github.com/youtube/vitess/compare/master...HubSpot:0f5670e43aeefa28d663c8a9fe4c1362a373d5a2

I have not yet been able to get local testing and such working so did not submit the above PR, but would be happy to if you'd like.

**Comment by alainjobart** [comment]
So the code you're pointing at is actually working as expected. The idea for this library (CredentialsServer) is that the user / password to use may change over time. (With a file implementation of the CredentialsServer, they obviously don't). But this initial MysqlParams is not meant to modify the global dbconfigs. Before using dbconfigs though, we have to go through MysqlParams to fill in the user and password. My guess is some code path is not doing that.

Where did you get an error? which part of vttablet was not doing the right thing?

**Comment by bbeaudreault** [comment]
Ahh, ok, thanks @alainjobart. 

Both Backup and ApplySchema were failing with a similar error:

```
I1204 21:47:11.945045   26421 mysqld.go:408] execCmd: /usr/bin/mysqladmin /usr/bin/mysqladmin [-u vt_dba -S /opt/mysql/dbprod/teset-q0.sock shutdown]
I1204 21:47:11.950899   26421 mysqld.go:419] execCmd: /usr/bin/mysqladmin failed: exit status 1
I1204 21:47:11.950926   26421 mysqld.go:422] execCmd: /usr/bin/mysqladmin output: ^Gmysqladmin: connect to server at 'localhost' failed
error: 'Access denied for user 'vt_dba'@'localhost' (using password: NO)'
I1204 21:47:11.953607   26421 state_change.go:117] Executing post-action state refresh: after backup
```

Basically the same thing but related to not being able to test the sql change for ApplySchema. Notice the execCmd is lacking a `-p` arg. If the DBA creds were properly pulling from the CredentialsServer, than it would be adding that flag according to https://github.com/youtube/vitess/blob/master/go/vt/mysqlctl/mysqld.go#L362

**Comment by alainjobart** [comment]
OK that's what I thought, I know where that is, I'll fix it soon then. I'll rework the code so it's obvious when we go through the CredentialsServer or not.

**Comment by alainjobart** [comment]
I have this PR for review to address this issue, and also clean up a few things: https://github.com/youtube/vitess/pull/2343

**Comment by alainjobart** [comment]
Merged the PR, fixed.
