### ISSUE TITLE
mysqld.go execCmd prints password to logs when password is in play

### ISSUE THREAD

**Issue by bbeaudreault** [youtube/vitess#2339]
We've started using the FileCredentialsServer in vitess, and since doing so have noticed that certain operations use the `mysql -p` arg to pass a password, which prints a warning. Additionally, vitess prints the password to the logs, due to https://github.com/youtube/vitess/blob/master/go/vt/mysqlctl/mysqld.go#L695

Example with a manually redacted password:

```bash
I1205 20:36:31.299715   32480 mysqld.go:408] execCmd: /usr/bin/mysql /usr/bin/mysql [--batch -u vt_dba -S /opt/mysql/dbprod/test-q0.sock -pMANUALLY_REDACTED]
I1205 20:36:31.382281   32480 mysqld.go:422] execCmd: /usr/bin/mysql output: mysql: [Warning] Using a password on the command line interface can be insecure.
```

Would it be possible to pipe the shell in to stdin? Alternatively, can it be modified to accept a `--defaults-file=` argument, as defined here http://dev.mysql.com/doc/mysql-security-excerpt/5.7/en/password-security-user.html?

**Comment by alainjobart** [comment]
First part of the fix is in this PR: https://github.com/youtube/vitess/pull/2343
To not run mysql_upgrade with the dba password, but just with 'root' user.

**Comment by alainjobart** [comment]
Added the second part of the fix there: https://github.com/youtube/vitess/pull/2343
Now we write credentials to temporary file.

**Comment by bbeaudreault** [comment]
Thanks, looks great!

**Comment by alainjobart** [comment]
Merged the PR, fixed.
