### ISSUE TITLE
Transactional commands (e.g. `BEGIN`, `COMMIT`, `ROLLBACK`) are not supported by the Java client and JDBC driver

### ISSUE THREAD

**Issue by steve-perkins** [youtube/vitess#2350]
Transactional commands such as `BEGIN`, `COMMIT`, etc are not recognized by VTGate.  

Based on chat with @sougou in Slack, the best way to support them would be on the client end.  Have each client parse SQL strings, making case-insensitive checks for `begin`, `commit`, and `rollback` (and perhaps the MySQL alternative `start transaction` syntax?).  Where they are found, they should be replaced with the appropriate RPC call.

The Python client does this here today:

https://github.com/youtube/vitess/blob/master/py/vtdb/base_cursor.py#L120

https://github.com/youtube/vitess/blob/master/py/vtdb/vtgate_cursor.py#L79

Although `BEGIN`, `COMMIT`, etc do not work when used up in the SQL level (i.e. in a desktop workbench app like DBeaver or SQuirreL)... the low-level JDBC API calls *do* work (i.e. `VitessConnection.commit()`, `VitessConnection.rollback()`).  So presumably those are the "appropriate RPC calls".

**Comment by sougou** [comment]
#2646 should fix this issue.
