### ISSUE TITLE
Vitess gRpc support for \G query termination 

### ISSUE THREAD

**Issue by FarzanRNobakht** [youtube/vitess#2352]
bin/vtctlclient ExecuteFetchAsDba  cell-313 "show slave status\G"
returns 
E1208 18:55:50.741417   11685 main.go:43] Remote error: rpc error: code = 2 desc = TabletManager.ExecuteFetchAsDba on cell-0000000313 error: rpc error: code = 2 desc = gRPCServerError: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '\g' at line 1 (errno 1064) (sqlstate 42000) during query: show slave status\g

so because the result row has too many column  results are not readable easily 
i even use -json but it prints column name seprated from column content

It will be nice if i can get something like this
*************************** 1. row ***************************
               Slave_IO_State: Waiting for master to send event
                  Master_Host: localhost
                  Master_User: root
                  Master_Port: 13000
                Connect_Retry: 60
              Master_Log_File: master-bin.000002
          Read_Master_Log_Pos: 1307
               Relay_Log_File: slave-relay-bin.000003
                Relay_Log_Pos: 1508
        Relay_Master_Log_File: master-bin.000002
             Slave_IO_Running: Yes
            Slave_SQL_Running: Yes
              Replicate_Do_DB:
          Replicate_Ignore_DB:
           Replicate_Do_Table:
       Replicate_Ignore_Table:
      Replicate_Wild_Do_Table:
  Replicate_Wild_Ignore_Table:
                   Last_Errno: 0
                   Last_Error:
                 Skip_Counter: 0
          Exec_Master_Log_Pos: 1307
              Relay_Log_Space: 1858
              Until_Condition: None
               Until_Log_File:
                Until_Log_Pos: 0
           Master_SSL_Allowed: No
           Master_SSL_CA_File:
           Master_SSL_CA_Path:
              Master_SSL_Cert:
            Master_SSL_Cipher:
               Master_SSL_Key:
        Seconds_Behind_Master: 0
Master_SSL_Verify_Server_Cert: No
                Last_IO_Errno: 0
                Last_IO_Error:
               Last_SQL_Errno: 0
               Last_SQL_Error:
  Replicate_Ignore_Server_Ids:
             Master_Server_Id: 1
                  Master_UUID: 3e11fa47-71ca-11e1-9e33-c80aa9429562
             Master_Info_File: /var/mysqld.2/data/master.info
                    SQL_Delay: 0
          SQL_Remaining_Delay: NULL
      Slave_SQL_Running_State: Slave has read all relay log; waiting for the slave I/O thread to update it
           Master_Retry_Count: 10
                  Master_Bind:
      Last_IO_Error_Timestamp:
     Last_SQL_Error_Timestamp:
               Master_SSL_Crl:
           Master_SSL_Crlpath:
           Retrieved_Gtid_Set: 3e11fa47-71ca-11e1-9e33-c80aa9429562:1-5
            Executed_Gtid_Set: 3e11fa47-71ca-11e1-9e33-c80aa9429562:1-5
                Auto_Position: 1
         Replicate_Rewrite_DB:
                 Channel_name:

**Comment by alainjobart** [comment]
I believe the \G terminator is interpreted by the 'mysql' command line tool, not by the server. vtctlclient sends the query 'as is' to the server, which doesn't know how to interpret the \G in the SQL. To support this, vtctlclient would need to parse the query and find the \G, and then change its display. I am not sure this is going to be easy to do.

**Comment by sougou** [comment]
I was actually thinking `ExecuteFetch` could strip out the `\G` before sending, and just print the output differently.

**Comment by enisoc** [comment]
Detecting the \G seems a bit hacky and hard for users to discover it's there. It should be straightforward though to add a flag on ExecuteFetchAsDba like the -json flag that instead requests this alternate output format.

For anyone who might want to take that on, the current format is produced here:

https://github.com/youtube/vitess/blob/6ef4ed6689f1b3bd7af67b436b5b6cd79cc202c5/go/vt/vtctl/query.go#L607

You could make a similar function that produces the alternate format, then add a subflag here that causes it to use your new function:

https://github.com/youtube/vitess/blob/6ef4ed6689f1b3bd7af67b436b5b6cd79cc202c5/go/vt/vtctl/vtctl.go#L1027

It would be a nice little task for a new contributor to start diving into the codebase.

**Comment by enisoc** [comment]
In the long term, we should fix this by adding a MySQL binary protocol interface to vtgate so you can just use tools like `mysql` directly. :)

**Comment by mdhheydari** [comment]
@enisoc, The binary protocol will be great for queries like `select` or `update`. Though for diagnosing a single mysql instance (commands like `SHOW SLAVE STATUS` or `SHOW STATUS`), I think the `ExecuteFetchAsDba` is still needed. 
I will write this over the weekend. :wink:

**Comment by sougou** [comment]
This is now supported through mysql protocol.
