### ISSUE TITLE
Schema swap workflow incompatible with semi-sync

### ISSUE THREAD

**Issue by rnavarro** [youtube/vitess#2385]
I've run a few tests in our stage environment, and for the most part things work great.

However, I noticed that when the schema swap workflow is propagating backups it takes down the replica node without promoting another node to replica.

When semi-sync is enabled this causes a write lock on the master because rdonly nodes do NOT ack the master for semi-sync.

I think we should promote a rdonly node to a replica while we are updating the old replica.

**Comment by pivanof** [comment]
Hm... I'd think the proper answer to this is to have several 'replica' tablets. It would be too complicated to try to write some rules for changing rdonly to replica and then back to rdonly.

**Comment by rnavarro** [comment]
That's fair, however, I think this limitation should be called out in the documentation for users.

We have our own in house version of this script that I wrote, so it's not a huge deal breaker for us. I just thought I'd point it out.
