### ISSUE TITLE
vtgate crashes when trying to watch on etcd topology

### ISSUE THREAD

**Issue by mdhheydari** [youtube/vitess#2386]
My vtgate crashed today and when I try to run it again, it fails immediately with the following output. 
```
I1217 14:37:36.939128    7736 discoverygateway.go:76] loading tablets for cells: peste
I1217 14:37:36.939697    7736 discoverygateway.go:97] Waiting for tablets
I1217 14:37:36.939955    7736 cell.go:103] etcdtopo: global address list = http://X.X.X.X:YYYY
E1217 14:37:37.026937    7736 serving_graph.go:81] modifiedVersion: 1425
E1217 14:37:37.039516    7736 serving_graph.go:81] modifiedVersion: 45
E1217 14:37:37.040201    7736 serving_graph.go:81] modifiedVersion: 118
E1217 14:37:37.040206    7736 serving_graph.go:83] Watch on /vt/ns/peste/_Data failed, waiting for 30s to retry: 401: The event in reque
sted index is outdated and cleared (the requested history has been cleared [1587/1045]) [2586]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x10 pc=0x4e6b55]
```
I've added this log `log.Errorf("modifiedVersion: %v", modifiedVersion)` just before https://github.com/youtube/vitess/blob/v2.0.0/go/vt/etcdtopo/serving_graph.go#L81

And modifiedVersion was wrong, it should have been `1587` but it was `118`.

I already made a hotfix for myself by hardcoding the modified version but I have to change it every time I need to restart vtgate or launch a new instance of it.

**Comment by alainjobart** [comment]
I'll look at it on Monday, I need to refactor that code anyway. Thanks for the report!

**Comment by alainjobart** [comment]
https://github.com/youtube/vitess/pull/2394 has support for the new etcd client, with reworked code. It should be a lot more stable.

**Comment by alainjobart** [comment]
This should be fixed now.
