### ISSUE TITLE
Native autocommit support

### ISSUE THREAD

**Issue by bbeaudreault** [youtube/vitess#2418]
There have been a few discussions about autocommit in the #vitess room. In terms of current state, here's what I understand:

- Vitess requires mysql to have autocommit enabled, for performance reasons, per the docs
- However, users of vitess do not get the benefits of autocommit by default.  In order to get an autocommit-like behavior, you need to enable `-enable-autocommit` config on the vttablet command line. With this enabled, vttablet wraps your query in a local transaction before executing.
- There is client-side autocommit behavior: when enabled, the client simply sends the request along expecting the vttablet to handle it (if `enable-autocommit` is set on vttablet). When disabled, it begins or retrieves a transaction before executing but does not commit. It does not know about the state of the autocommit flags in vttablet/mysql.
- There were/are hopes to deprecate the `-enable-autocommit` feature in vttablet, pushing the responsibility fully to the client, due to concerns of partial commits when v3 api splits your statements.

I think autocommit is a feature that is commonly enough used (defaults to enabled in mysql), and at my company we have thousands of queries which use it. If one hopes to be able to shim vitess into their environment with minimal consequences or extra migration work, autocommit needs to work natively in my opinion.

Additionally, I have some (slightly unfounded/based on intuition) concerns about taking existing systems where an UPDATE may currently result in 1 RPC call directly to a MySQL, and turning that into 3 RPC calls (begin/statement/commit), each to a vtgate -> vttablet -> mysql. If we need to push autocommit control to the client, it would be nice to warp the begin/statement/commit in a single RPC. However, I think pushing on clients increases compatibility complexity in the future, when thinking about new client languages, GUIs, etc.

@sougou suggests we need to scope out the work necessary to support this, but that it shouldn't be too much :crossed_fingers:

**Comment by sougou** [comment]
@bbeaudreault Let me know if #2646 addresses this issue.

**Comment by bbeaudreault** [comment]
Thanks @sougou! I'll close this for now. My only potential future concern is that vtgate does 3 RPCs to vttablet, as opposed to 1. But we can cross that bridge if it becomes an issue.

**Comment by sougou** [comment]
It's actually only 2 for now (BeginExecute->Commit). But yeah, I've been keeping that in mind also.
