### ISSUE TITLE
go memcache connection persistency & goroutine safety

### ISSUE THREAD

**Issue by seungryulchoisc** [youtube/vitess#2446]
Hi,

I am trying to use memcache api in go/memcache, and ran into two problems.

1.  Get() and Set() returns error with `write: connection reset by peer` after few hours of connection to the memcache. So I had to call Close() and Connect() again.  Is that what memcache is supposed to work?

2. Without mutex, Get() and Set() have error `external/com_github_youtube_vitess/go/memcache/go_default_library.a.dir/github.com/youtube/vitess/external/com_github_youtube_vitess/go/memcache/memcache.go:297` while running loadtest.  Is Get() and Set() goroutine safe? If not, can anyone let me know any better way than having global mutex?

**Comment by sougou** [comment]
Wow. That's really old code. We actually don't use it any more, at least for now. I see that it's still using the old style panic error handling which is not idiomatic go.
I would recommend you try to use a more official version of memcache client for now, like this one: https://github.com/bradfitz/gomemcache, unless you think that our version has other advantages.

**Comment by michael-berlin** [comment]
Should we delete the code?

godoc.org finds one other package on GitHub which is using it: https://godoc.org/github.com/youtube/vitess/go/memcache?importers

That package/project seems to be active. Last commit was 3 months ago: https://github.com/ptt/pttweb

**Comment by sougou** [comment]
Since the code is used by someone else, I'll leave the code as is and unmaintained.
I'll close this bug since there's no intention to make fixes right now.

**Comment by arthurnn** [comment]
I would vote to delete code that is not maintained and not in use.
