### ISSUE TITLE
LDAP auth for mysql protocol connections

### ISSUE THREAD

**Issue by bbeaudreault** [youtube/vitess#2458]
https://github.com/youtube/vitess/pull/2440 adds support for the mysql binary protocol. This should allow users to connect to the VTGate using tools like SequelPro, mysql workbench, etc. 

We'd like to support LDAP auth for those client connections. We use LDAP for both authentication and authorization, and would like to be able to enforce this at the VTGate as well. For instance, we would bind to LDAP with the passed username/password, then do an LDAP search using the username and some configurable query pattern. Depending on the result, the user would be allowed or denied access to the requested keyspace.

We were planning on building this into g10's mysql proxy initially, until this new mysql protocol work began which negates the need for the proxy. Now the logic makes senses to live in the VTGate.

This issue is to gauge the viability of such a system in VTGate. We'll be looking to begin implementing this in the very near future, and would obviously prefer to get it merged. Our plan would be to make a pluggable auth package, with an implementation for LDAP that is configurable to our needs (i.e. the queries described above).

Thoughts?

**Comment by alainjobart** [comment]
Let me start with the way MySQL native auth works: the server sends a challenge to the client, and then both client and server transform that same challenge using the password and the same transformation. The client sends its transformed version, the server compares with its transformed version, if they match then the user is allowed. What is worth noting is the server *never* sees the client password, but only the transformed challenge. And the transformation is not reversible (it's a couple layers of checksuming).

In this page:
https://dev.mysql.com/doc/refman/5.5/en/cleartext-authentication-plugin.html
it is also explained that clear text password can be sent up, and used by the server. This is used by PAM plugin for instance. I think we would need this here too.

But this is not secure at all, if we are not using SSL. If using SSL, the SSL negotiation happens before the password exchange, so it is secure. Without SSL, the password is sent in the clear. So we should at least echo a warning if clear passwords are used, and not SSL.

That being said, setting up the plug-in mechanism and implementing one plug-in that uses a simple JSON file with users and passwords in it is easy enough, I can do that. I actually need to do that so vtgate's server connector can recognize more users than just the hard-coded one.

As far as table ACLs are concerned, we can use the user used to log in as the VTGateCallerID (AKA immediate caller id), maybe with a prefix. So if you log in to vtgate's mysql binary protocol connector with 'user1', then 'user1' is passed to vttablet, and does table ACL checks on that. (note: here we can add a level of indirection, and map mysql user name to vttablet ACL name. Is that necessary? In the file case, it would be an extra field, with default to user name. In the LDAP case, it could be a user attribute).

**Comment by bbeaudreault** [comment]
Thanks for the detailed investigation/explanation @alainjobart. I hadn't realized that is how the challenge system works.

Can the vtgate mysql implementation work with SSL? Because I agree we're going to want that rather than sending the password in clear text. I think we'd even want to *just* support SSL for our case.

I think what you mentioned sounds like a good first start. In terms of your question towards the end "Is that necessary?": for us, yes. Like you suggested, we'd want to be able to use a user attribute as the immediate caller id.  For us, every LDAP user has a "group" field, which defines the engineering team their on. So I'd like to define an ACL like "this keyspace can only be queried by hs-foo", where hs-foo is a group/team name.

If you can provide the plugin setup, and thoughts on the SSL configuration, we can write an ldap plugin. I would think such a plugin would loosely be configurable with an ldap host to bind to, and a field or search query to use as the immediate caller id.

**Comment by alainjobart** [comment]
A few answers:

* I am working on SSL with our MySQL implementation. The main problem there is tests (create certs, keys for unit tests) and I am reworking this now. Should be ready soon.

* Next on my list is the plugin interface for the server side, and a file-based implementation. I will probably make it generic enough so it supports both the challenge-based method, and the clear text password method. It will allow the plug-in to set the immediate caller id. The file-based version will just use an extra field for that, and if not set, use the user name.

* For test purposes, I may have two versions of the file-based auth, one with the challenge, one with clear-text passwords.

* For clear text support, I'll make sure there is a check to only allow that over SSL. And it will probably be on by default.

* I'll let you work on your LDAP plugin. It should be fairly straightforward, as you can use any flag you want, and link it in vtgate.

**Comment by bbeaudreault** [comment]
Thanks @alainjobart, this sounds great!

**Comment by alainjobart** [comment]
SSL support is added in this PR: https://github.com/youtube/vitess/pull/2567

**Comment by bbeaudreault** [comment]
This is done.
