### ISSUE TITLE
vtctlclient: command not found

### ISSUE THREAD

**Issue by justechn** [youtube/vitess#2465]
I am in the process of following [these](http://vitess.io/getting-started/#start-a-vitess-cluster)
instructions, but I am stuck on the step that says to run "./kvtctl.sh help".

```
./kvtctl.sh help
Starting port forwarding to vtctld...
./kvtctl.sh: line 15: vtctlclient: command not found
```

So far everything else has worked fine.

I am running this on Windows 10, with Minikube.

**Comment by justechn** [comment]
nevermind

**Comment by justechn** [comment]
I made sure that the bin folder was added to my path, and I see that vtctlclient.exe is in that folder. However it is not found. 

I wonder if that happens because it is trying to start a .exe file from a .sh and they two systems are not compatible. I did notice that when I use Windows CMD to run the command it switches to GIT Bash, that also might be part of the problem.

**Comment by michael-berlin** [comment]
Yes, your observation is correct.

While Go binaries itself may compile and run on Windows, our Bash scripts definitely don't.

At this point we don't plan to support Windows. I recommend to setup e.g. a virtual machine and install Ubuntu. From there, you could run the example.
