### ISSUE TITLE
Support for CLIENT_FOUND_ROWS option

### ISSUE THREAD

**Issue by sougou** [youtube/vitess#2530]
Ref: https://dev.mysql.com/doc/refman/5.7/en/information-functions.html#function_row-count.

Implementation issues:
* This is a connection parameter. However, since vitess uses connection pools, it can likely be supported only as a command line setting.
* Vitess rewrites upserts. Behavior of row returned is different if that option is set. Vitess may need to adjust its behavior based on the setting.

**Comment by bbeaudreault** [comment]
My thoughts here were to add support for multiple lazy-loaded pools. We would have the usual default pool, eagerly loaded, where most connections would go. Additional pools would be kept in a map, keyed off of connection flag bitmask. When a connection comes in that does not match whatever the default server flags are, it would create a new pool. Connections in a pool, and perhaps the pool itself, could be given an idle timeout, at which point they are shut down. Future execute calls with the same execute option would continue going to the pool that matches their options.

**Comment by bbeaudreault** [comment]
@sougou with your RBR support change we now can trust the results for CLIENT_FOUND_ROWS. The only remaining problem is that this is a per-connection setting. I know you're embroiled in the v3 session work right now, but any thoughts on how we might support this in the txpool?

I'm at a decision point internally as to whether I disable CLIENT_FOUND_ROWS across the board or hold off. It's a concerning change because it can have very subtle impacts on return results that are hard to catch across all mysql code written. If you think we could handle this in the next 1-2 months, then I would prefer not to flip the switch. But if you think we might never support connection flags in txpool, then I should do it now so that people deploy before I ever enable vitess in prod.

Thoughts?

**Comment by sougou** [comment]
We did some more researching and brainstorming on this. It turns out that it is possible for vttablet to compute the correct values for `CLIENT_ROWS_FOUND`, but only if the MySQL connection flag doesn't set it (which was the previous option we considered).

For `UPDATE`, vttablet would have to perform a `SELECT...FOR UPDATE` and count the rows before updating. It already does this for non-pk where clauses. It would now do it for all updates.

For `INSERT...ON DUP`, it will do everything as normal. However, it will return `RowsAffected+1` instead.

It will basically be a new code path for those statements if the flag was in the request, which will be  set in `Session` variable. This code path will supersede RBR mode, which means that you won't benefit from the pass-through in such cases.

The other option is to build new pools and extend the API to specifically use them. We may eventually end up with with that design, which may be driven by other use cases. But we can punt on this for now with the above cheaper solution.

**Comment by bbeaudreault** [comment]
Thanks for the work/thought here. That sounds like a good compromise to me. We can push off the more complicated txpool redesign in favor of this for now.

One clarification though. When you say `RowsAffected+1` you mean +1 only in the case where a row is set to its current value. Right?  Docs for reference:

> For INSERT ... ON DUPLICATE KEY UPDATE statements, the affected-rows value per row is 1 if the row is inserted as a new row, 2 if an existing row is updated, and 0 if an existing row is set to its current values. If you specify the CLIENT_FOUND_ROWS flag, the affected-rows value is 1 (not 0) if an existing row is set to its current values.

**Comment by sougou** [comment]
Yes. `+1` on the `update`, only if we get a dup key error on `insert`.

**Comment by bbeaudreault** [comment]
Sounds good! I imagine this will come after the v3 work due to the dependence on Session?

**Comment by sougou** [comment]
After thinking about it some more, I don't feel good about the approach where vttablet rewrites the qureies to compute RowsAffected. The main reason is because vttablet's rewrite of `INSERT...ON DUPLICATE KEY` is very restrictive, and it will be very hard to document this special-case behavior.

So, I'm thinking of going back to the multiple pools approach. The special-casing will only affect the Begin, which will decide where to pull the connection from.

Hopefully, there will be no further requests for hybrid connection properties. So, I'll just special-case this situation (vs. building a generic framework). I'll also implement it in such a way that the second pool becomes active only if explicitly requested; Those who don't need it won't pay the price.

Let's see if the design sticks this time :).

**Comment by sougou** [comment]
Via #2827
