### ISSUE TITLE
vtctld: close of closed channel

### ISSUE THREAD

**Issue by nizsheanez** [youtube/vitess#2534]
Version: master, I checkout to master built vitess/base docker image on my local machine (Mac)

Not sure on which exactly commands it happened, but run only vtclt commands from `examples` folder: CreateKeyspace, SetKeyspaceShardingInfo, RebuildKeyspaceGraph, InitShardMaster, ApplySchema

mysqlctld was down, mysqld also

Logs: 
{code}
vtctld          | ERROR: logging before flag.Parse: E0204 06:33:16.223427       1 syslogger.go:110] can't connect to syslog
vtctld          | I0204 06:33:16.242875       1 long_polling.go:171] workflow Manager listening to web traffic at /api/workflow/{create,poll,delete}
vtctld          | I0204 06:33:16.244912       1 websocket.go:19] workflow Manager listening to websocket traffic at /api/workflow
vtctld          | I0204 06:33:16.246000       1 cell.go:107] etcdtopo: global address list = http://etcd-global:4001
vtctld          | I0204 06:33:16.246005       1 service_map.go:53] Registering vtctl for grpc, disable it with -grpc-vtctl service_map parameter
vtctld          | I0204 06:33:16.246261       1 grpc_server.go:127] Listening for gRPC calls on port 16100
vtctld          | I0204 06:33:16.246455       1 unix_socket.go:24] Not listening on socket file
vtctld          | I0204 06:37:22.110069       1 run.go:37] Entering lameduck mode for at least 50ms
vtctld          | I0204 06:37:22.110179       1 run.go:38] Firing asynchronous OnTerm hooks
vtctld          | I0204 06:37:22.110245       1 servenv.go:139] Firing synchronous OnTermSync hooks and waiting up to 10s for them
vtctld          | I0204 06:37:22.113408       1 servenv.go:152] OnTermSync hooks finished
vtctld          | I0204 06:37:22.113572       1 run.go:43] Sleeping an extra 45.625054ms after OnTermSync to finish lameduck period
vtctld          | panic: close of closed channel
vtctld          |
vtctld          | goroutine 58 [running]:
vtctld          | panic(0xd2e620, 0xc4203cba40)
vtctld          | 	/usr/local/go/src/runtime/panic.go:500 +0x1a1
vtctld          | github.com/youtube/vitess/go/vt/etcdtopo.(*etcdMasterParticipation).WaitForMastership(0xc420243a40, 0x7fe4e87da028, 0xc4203961c0, 0x0, 0x0)
vtctld          | 	/vt/src/github.com/youtube/vitess/go/vt/etcdtopo/election.go:60 +0x6fa
vtctld          | github.com/youtube/vitess/go/vt/vtctld.runWorkflowManagerElection.func1.2(0xc420284b10)
vtctld          | 	/vt/src/github.com/youtube/vitess/go/vt/vtctld/workflow.go:97 +0x3f
vtctld          | created by github.com/youtube/vitess/go/vt/vtctld.runWorkflowManagerElection.func1
vtctld          | 	/vt/src/github.com/youtube/vitess/go/vt/vtctld/workflow.go:108 +0x1ad
vtctld exited with code 2
{code}

**Comment by sougou** [comment]
This bug looks obsolete now. The topo code has gone through substantial revamp. Looking at the current code, it doesn't look like this can happen again. So, I'm closing this.
