### ISSUE TITLE
Backup does not snapshot correctly while using parallel replication

### ISSUE THREAD

**Issue by sougou** [youtube/vitess#2537]
Because there are parallel threads applying statements to MySQL, our current process of shutting down mysql leads to gaps in the binlog that are not applied compared to the last binlog position saved.
After restore, since we start from the last known position, those parts of the binlog get left out, and the replica has diverged from the master.
Either we need a way to ensure that there are no transactions left out in the replica as of the last position, or we need to restart replication at an earlier point to make sure that everything is replayed.

**Comment by alainjobart** [comment]
I think this was all a misunderstanding about how GTIDSets work. @sougou can we close this?

**Comment by sougou** [comment]
Yes.
