### ISSUE TITLE
Uncaught panic in vtgate

### ISSUE THREAD

**Issue by sougou** [youtube/vitess#2538]
Posting the info I have so far.

Stack trace is here: https://gist.github.com/sougou/f8121b3d8227e00c0f3d7bbd18b08df5

Waiting on @Rastusik for more reproduction info.

Most likely, vttablet returned rows without the field info. This means that it was a `select`. It's possible that the statement issued was one where bind vars were used in the select expressions, like `select :a+1 from t...`. If so, vttablet cannot cache the field info because the type returned depends on the supplied bind var. That's not a heavily used code path. So, there could be a bug there.

**Comment by Rastusik** [comment]
This happened in the `b35065b91d0945533f9e740e2b999aacb4eb9c66` commit hash build.

The query which had this problem should be this one: 
```
SELECT * FROM `player_data` WHERE `player_id` = '3' LIMIT 1
```

There were no bind vars in the query. The VtGates were running a couple of days before this incident. VtGate restart helped to resolve the problem.

**Comment by sougou** [comment]
Looks like this got resolved. Closing.
