### ISSUE TITLE
Standard package should be removed from `vendor/vendor.json`

### ISSUE THREAD

**Issue by blindpirate** [youtube/vitess#2551]
I'm writing a tool to analyze dependencies of Go repositories, and I found that there is a standard package `context` dependency in `vendor.json`, which should be removed in my view.

Is it necessary here?

```
{
	"comment": "",
	"ignore": "appengine test",
	"package": [
                ...
		{
			"path": "context",  // here it is
			"revision": ""
		},
                ...
	},
	"rootPath": "github.com/youtube/vitess"
}

```

**Comment by michael-berlin** [comment]
You're right. I've just removed it.
