### ISSUE TITLE
Bug in the Vtctld app2 UI

### ISSUE THREAD

**Issue by ashudeep-sharma** [youtube/vitess#2561]
In the app2 UI, if we click on a folder under Topology Browser tab and it doesn't consist of a subfolder, it just keep on appending in the URL as well as header. As a result if we try to click on another tab like Global it would not work because it has moved to a different hierarchy. 

Please check the screenshot for more details.
<img width="1156" alt="screen shot 2017-02-15 at 1 10 34 pm" src="https://cloud.githubusercontent.com/assets/12492010/22964848/aea682b2-f380-11e6-95e4-0a2a4c3c6cc7.png">

**Comment by alainjobart** [comment]
I think you're getting errors, and they're not reported / handled properly by the UI. I can't seem to reproduce the issue with my local test.

If you use Chrome, can you inspect the page, go to network traffic, and copy what the client - server interactions are? Thanks!

**Comment by ashudeep-sharma** [comment]
Api calls while using App2 UI:
Every time i click on the link the following requests are created 
**Click1** :
Request URL:http://10.85.112.245:15000/api/topodata/test
Referer:http://10.85.112.245:15000/app2/topo
**Click2**
Request URL:http://10.85.112.245:15000/api/topodata/test/test
Referer:http://10.85.112.245:15000/app2/topo?path=%2Ftest

API Calls while using App UI:
Request URL 1:http://10.85.112.245:15000/api/topodata/test
Referer 1:http://10.85.112.245:15000/app/
Request URL 2http://10.85.112.245:15000/app2/
Referer 2:http://10.85.112.245:15000/app/

I am seeing the difference here that when we use App UI, for one click 2 requests are being sent as mentioned above while for App2 UI  only 1 rest call is made.

Note the behaviour is seen only when while clicking the response is pending state. The App UI shows an image loading so we don't have the option to click anything but in App2 UI we can still click on test again which appends /test to the url
