### ISSUE TITLE
`message_test.go` not resilient to timeouts when Travis CI is under high load

### ISSUE THREAD

**Issue by steve-perkins** [youtube/vitess#2624]
During periods when Travis CI is under high load, the `message_test.go` test suite can fail due to timestamps not being within some small threshold (see example output below).  Is there a way to accomplish the goals of this test suite while also being more resilient to slow performance on the CI box?

```
--- FAIL: TestMessage (7.19s)
    message_test.go:148: ack: 1488573491. must be within 1s of end: 1488573492
W0303 20:38:16.960806   37151 query_engine.go:283] Cannot cache field info: select :bv from dual
```

**Comment by sougou** [comment]
I'm slightly reluctant to fix this because the only way is to increase the wait time, which will slow down all tests. I'll watch this over. If it happens too frequently, I'll increase the waits.
