### ISSUE TITLE
Enable_replication_reporter vttablet  parameter should not have to be set explicitly 

### ISSUE THREAD

**Issue by Rastusik** [youtube/vitess#2628]
Since the `enable_replication_reporter` vttablet startup parameter is mandatory for successful failovers, it should have a hardcoded default value, so users wouldn't need to declare this parameter explicitly on vttablet start. Currently it is needed to declare this parameter, and that's why there is a possibility for human error occurrence, which already happened at least once.

**Comment by alainjobart** [comment]
I agree here.

The problem we have internally is that we use a custom plug-in for replication monitoring, and not this one, so let me first change our internal configs to pass enable_replication_reporter=false, then I'll submit a change to make the default to true.
