### ISSUE TITLE
Are both local and global lock services really necessary?

### ISSUE THREAD

**Issue by elimist** [youtube/vitess#2632]
Hello,

I just wanted to ask if it's really that important to have both local and global lock services (in a multi-dc/multi-cell setup). 

From what I've read in the documentation, this is recommended to increase the reliability of the system (if the global lock service goes does, individual cells can keep functioning and if a local lock service goes down, the others are unaffected.)

But let's say you have a highly available Consul cluster spread across multiple cells already; can't you pretty much assume that it will always be available? If a network partition occurs between cells, you'd still be able to read meta data from the Consul node situated within the cell. I ask because it seems like a lot of overhead to have two levels of lock servers for perhaps not much benefit.  

Besides reliability, are there other factors that need to be taken into account if I was to just put everything into the global topology servers?

**Comment by sougou** [comment]
It's up to you. If you want simplified deployment, you can use the same lockserver for both local and global. The data is stored in non-overlapping paths.

In general, people say that lockservers should not be considered highly available. So, apps are encouraged to build resilience against possible downtime, which is what guided vitess's choices.

**Comment by elimist** [comment]
Great, thanks for the clarification!
