### ISSUE TITLE
last inserted id always returns null 

### ISSUE THREAD

**Issue by alouane** [youtube/vitess#2635]
Hi
Is there any way to debug why insert_id always returns null

`object(Vitess\Proto\Query\QueryResult)#196 (8) { ["fields"]=> array(0) { } ["rows_affected"]=> int(1) ["insert_id"]=> NULL ["rows"]=> array(0) { } ["extras"]=> NULL ["_descriptor":protected]=> object(DrSlump\Protobuf\Descriptor)#197 (4) { ["class":protected]=> string(30) "Vitess\Proto\Query\QueryResult" ["name":protected]=> string(17) "query.QueryResult" ["fields":protected]=>`

As you can see the insert_id attribute is null and does come from Vitess\Proto\Query\QueryResult

Also this simple query seems not working neither : select LAST_INSERT_ID(); when called from php

`vtgate: http://vtgate-test-l621r:15001/: syntax error at position 22 near 'last_insert_id' in /var/www/html/RESTFullAPI2/vendor/vitess/php-client/php/src/Vitess/ProtoUtils.php:56\nStack trace:\n#0 /var/www/html/RESTFullAPI2/vendor/vitess/php-client/php/src/Vitess/VTGateConn.php(53): Vitess\\ProtoUtils::checkError(Object(Vitess\\Proto\\Vtgate\\ExecuteResponse))\n#1 /var/www/html/RESTFullAPI2/vendor/pixelfederation/vitess-php-pdo/src/VitessPdo/PDO/Vitess/Vitess.php(231): Vitess\\VTGateConn->execute(Object(Vitess\\Context), 'select LAST_INS...', Array, 2)\n#2 /var/www/html/RESTFullAPI2/vendor/pixelfederation/vitess-php-pdo/src/VitessPdo/PDO/PDOStatem`

but does work when I use cmd: ./kvtctl.sh ExecuteFetchAsDba test-0000000100 "select LAST_INSERT_ID()"

Thanks

**Comment by sougou** [comment]
Are you sure you're inserting a row that generated an id? This is a heavily used feature. So, I'm surprised it doesn't work for you. Only possible difference is that you're using the php client.

As for `last_insert_id()`, it doesn't work yet. We have a bug for it (and other constructs) #2466.

**Comment by alouane** [comment]
Yep definitely something is wrong, 
I confirm that the row gets inserted successfully, check the previous log => `["rows_affected"]=> int(1) `
But only that particular last_inserted id fails
Running an insert query followed by a select query doesn't help, most of the time, the select query doesn't include the last insert row
Also I confirm that I'm testing on a table that has a PK & Auto inc flags
I didn't change vitess php client code much, but my guess is that each query gets a new connection, so the the insert id is always null, is there any part of code that can leads to this kind of behavior?

Cheers

**Comment by sougou** [comment]
Let's ping @Rastusik. It must be something very obvious we're missing.

**Comment by alouane** [comment]
I appreciate it @sougou :)

**Comment by Rastusik** [comment]
@sougou regarding this info: https://github.com/pixelfederation/vitess-php-pdo/issues/16#issuecomment-286453704 it looks like the Vitess PHP client doesn't get the newly generated ID from Vitess `["insert_id"]=> NULL` ... So I'm not sure, I can only say that maybe it would be nice to get the table schema from @alouane and also at least one insert query...

**Comment by alouane** [comment]
Yep sure:
`$sql = "insert into licence set title='Test', description='Test'";
        //execute request
        $stmt = $this->container["db"]->prepare($sql);
        $stmt->execute();
var_dump($this->container["db"]->lastInsertId());`

Here is the licence table schema:

![image](https://cloud.githubusercontent.com/assets/3225153/23916037/c4357364-08e2-11e7-8a15-1bbf1ee9e79b.png)

**Comment by alouane** [comment]
Debugging VitessClient.php => Execute() method returns the same result: ` ["insert_id"]=>NULL`

```php
public function Execute(\Vitess\Proto\Vtgate\ExecuteRequest $argument, $metadata = array(), $options = array()) {
      return $this->_simpleRequest('/vtgateservice.Vitess/Execute', $argument, '\Vitess\Proto\Vtgate\ExecuteResponse::deserialize', $metadata, $options);
    }
```
With this info, is it still related to php client code? or has something to do with vtgate configuration?

**Comment by Rastusik** [comment]
Well, it seems to me that this is either a problem in the GO binaries, or there is something wrong with the PHP Protobuf classes. Or maybe the configuration of the Vschema? @alouane , is your database sharded?

**Comment by alouane** [comment]
Yep It's very weird, I'm running one single shard called 0, juste like the getting started tutorial:
![image](https://cloud.githubusercontent.com/assets/3225153/23949821/b4301584-0980-11e7-95e3-dacafe91283c.png)
The Vshema seems empty from the ui:
![image](https://cloud.githubusercontent.com/assets/3225153/23949894/fea71bee-0980-11e7-8bef-d630690b0ee2.png)
But I'm able to execute queries: 
![image](https://cloud.githubusercontent.com/assets/3225153/23950000/68d57650-0981-11e7-9f41-fec39be2b43c.png)

I think I have to rebuild the go code, maybe something has broken there. but in the meanwhile I added a simple TemplastInsert function that returns last inserted id (select query) based on my last insert query parameters, I edited also the execute method from @Rastusik code so that this temp function always runs on the master

Feel free to close this one, once I get a fix/solution, I will post it here

Thanks @Rastusik & @sougou
