### ISSUE TITLE
Go 1.8

### ISSUE THREAD

**Issue by bbeaudreault** [youtube/vitess#2681]
I noticed that Go 1.8 was released in February. Thoughts on running with 1.8 for Vitess in production? There seem to be some performance improvements both in GC and Cgo, which may have impact on mysql connections that aren't yet using `mysqlconn` (i.e vttablet).

Also, [the docs](http://vitess.io/user-guide/server-configuration.html#go-version) say:

> The current version to use Go 1.6.

Should we update that to at least 1.7, and maybe 1.8?

Finally, with regard to development, should we update bootstrap.sh to validate or install go? I think as more people come on board, minor things may be an issue. For instance, sugu recently accidentally updated (then reverted) `go tool yacc` to `goyacc` in the Makefile, which we don't install by default but is required for 1.8.

**Comment by alainjobart** [comment]
go 1.8 seems like the way to go. A couple data points:

* it's been running in YouTube for some time now, with no negative impact.

* mysqlconn is being validated inside YouTube now. I estimate another couple weeks and we can make it the default, and remove the old code. Then I can refactor and simplify a bunch of things.

* we want whatever we recommend to be the version we're running with travis. So we should update that to 1.8 too.

**Comment by michael-berlin** [comment]
@bbeaudreault We already require 1.7 as minimum version since https://github.com/youtube/vitess/pull/2103.

The place you found just stated the current Go version. I've pushed https://github.com/youtube/vitess/commit/f8dd89b7d7ca4640fd3d12ad5793b582581a79ab to remove that.

I would be fine with requiring 1.8 instead of 1.7.

The most significant improvement in 1.8 is that the GC pauses are much shorter. I think this improved tail latencies in our production instance.

I've created a PR to update the docs and Travis: https://github.com/youtube/vitess/pull/2682

Sugu, you also have a TODO in the vitessdriver which we could address if we require at least Go 1.7.

**Comment by o1egl** [comment]
I think we should wait for 1.8.x https://github.com/golang/go/issues/19182

**Comment by michael-berlin** [comment]
Pull request #2682 is merged now and with that I consider the Go 1.8 migration done.

Two things are left:
- The Docker images must be rebuild. Let's do that opportunistically with the next release.
- @sougou we need to decide if you want to keep the vitessdriver Go 1.7 compatible for now or not: https://github.com/youtube/vitess/blob/master/go/vt/vitessdriver/driver_go18.go#L7 I'm fine with keeping things as is for now.

**Comment by michael-berlin** [comment]
FYI: Go 1.8 provides a new easy to use `Slice` function in the `sort` package: https://golang.org/pkg/sort/#Slice

See the examples there for details.

I started using it yesterday in vtclient.go i.e. there's no way back. Our code requires Go 1.8 now to successfully compile.

**Comment by michael-berlin** [comment]
For the record: Sugu is going to remove the pre-1.8 code from the `vitessdriver` package in the near future. Once that's done, we can close this issue.

**Comment by bbeaudreault** [comment]
I believe I can close this now right? We're officially on 1.8 and building with it in travis?

**Comment by michael-berlin** [comment]
Nope. We're waiting for Sugu to remove the pre Go 1.8 code from the `vitessdriver` package :)

**Comment by sougou** [comment]
It's another one of those things waiting on the protocol change to be submitted.
