### ISSUE TITLE
percona dialog plugin support in mysql plugin

### ISSUE THREAD

**Issue by bbeaudreault** [youtube/vitess#2708]
@acharis @alainjobart 

Vitess has support for the mysql protocol. It supports auth via static configuration, and recently we added LDAP auth support. LDAP auth requires cleartext plugin and SSL (unless explicitly disabled). The cleartext plugin is not well supported by clients, in fact it is disabled in clients unless explicitly enabled: https://dev.mysql.com/doc/refman/5.5/en/cleartext-authentication-plugin.html

An alternative to cleartext is the dialog plugin, provided by percona. This still transmits in cleartext so should also be used with SSL, but it works for any client as long as the required `dialog.so` file is in your mysql client path and supports prompting via dialog box.

We need to add support the server side of the dialog plugin. See https://www.percona.com/doc/percona-pam-for-mysql/index.html and https://github.com/percona/percona-server/blob/1e2f003a5bd48763c27e37542d97cd8f59d98eaa/plugin/percona-pam-for-mysql/src/dialog.c

@alainjobart suggests a change to the auth server interface to support this.

**Comment by alainjobart** [comment]
Server-side work should be done there:
https://github.com/youtube/vitess/pull/2710
But it is untested.

**Comment by alainjobart** [comment]
@bbeaudreault this is done, right?

**Comment by bbeaudreault** [comment]
Yep, this is done. Thanks for the work here, we've been using it for a few weeks now and works like a charm!
