### ISSUE TITLE
Be more strict about sequence values for INSERT statements

### ISSUE THREAD

**Issue by sougou** [youtube/vitess#2711]
VTGate currently allows constructs like `INSERT INTO a(id, val) values(NULL, 'aa')`. If id is tied to a sequence, it replaces the NULL with a generated value.

This type of substitution is misleading, and MySQL doesn't support it anyway. So, we should only support `INSERT INTO a(val) values('aa')`.

**Comment by bbeaudreault** [comment]
Are you sure this isn't supported by MySQL?

```mysql> create table e (id int auto_increment primary key, val varchar(10));
Query OK, 0 rows affected (0.06 sec)

mysql> insert into e (id, val) values(null, 'aa');
Query OK, 1 row affected (0.01 sec)

mysql> select * from e;
+----+------+
| id | val  |
+----+------+
|  1 | aa   |
+----+------+
1 row in set (0.00 sec)```

**Comment by sougou** [comment]
LOL. I could swear I saw that statement fail. Closing this :).
