### ISSUE TITLE
Sticky sessions

### ISSUE THREAD

**Issue by bbeaudreault** [youtube/vitess#2724]
This could be somewhat related to https://github.com/youtube/vitess/issues/2723

By default vttablet keeps open a pool of connections. A user sends queries through the pipeline and when the vttablet executes the query, it will be sent to one of the idle connections in the pool.

Some features of MySQL require a stable connection. Notably transactions and session variables. Transactions already get their own pool, and there is code to ensure a transaction always goes to the same connection. We should provide a similar implementation for users that want to use session variables.

This has at least two uses:

- Ad hoc queries can use constructs such as `SELECT .. INTO @var`, or changes to durability, etc for the duration of their session.

- There are many external tools out there that use MySQL, and now that we support the mysql protocol in vtgate we have the opportunity to use Vitess to back those services transparently. One thing I've almost universally noticed is that many of them call `SET` to set up their session. currently this causes the queries to fail, but with sticky sessions we could support them.

@sougou and I discussed at least two potential triggers for this scenario:

1) The user must explicitly request a sticky session through some configuration or sql command.

2) Any call to `SET` or `SELECT .. INTO @var` automatically establishes a sticky session.

I think possibly a combination of both would be nice.

**Comment by alainjobart** [comment]
Some random idea here: why don't we store the session variables in the vtgatepb.Session object? Then they can be substituted by whoever parses the SQL... or just sent to MySQL right before we send the query on the socket.

I know, groundbreaking, to store session variables in Session object...

**Comment by sougou** [comment]
Do you have a list of variables that you need support for? Many of those set statements don't materially affect a connection. If so, we may be able to provide simple pass-through solutions.

**Comment by bbeaudreault** [comment]
I don't have a list off-hand. I was thinking of this from 2 directions:

- make it Just Work™ with random apps we want to point at Vitess. Things like orchestrator, Hive, and other tools that use MySQL but dont have code we can easily change. 

- The `SELECT ... INTO @var` construct I mentioned could be anything. You can store the value of a result into a variable, and then query using that variable afterwards. I've seen that a number of times from various developers doing ad hoc queries.

**Comment by sougou** [comment]
Sticky Sessions framework is now in place.
I've opened #2855 & #2856 to track the individual requests.
