### ISSUE TITLE
MATCH/AGAINST not working when using alias[PHP]

### ISSUE THREAD

**Issue by alouane** [youtube/vitess#2729]
Hi there
I m testing this search query using match/against:

```php
select title from video as v where match(v.title, v.tag) against('DEMO' IN BOOLEAN MODE)
```
Result:
`2: vtgate: http://vtgate-test-l621r:15001/: syntax error at position 45
`
The same query works well from cmd, also when not using alias

Thanks

**Comment by sougou** [comment]
@bbeaudreault want to take this on?

**Comment by acharis** [comment]
can you attach/link to sample php?

**Comment by sougou** [comment]
This should just be a parser change. You should be able to reproduce the failure by adding this query to parse_test.go.

**Comment by acharis** [comment]
in progress

**Comment by acharis** [comment]
@alouane fix is PR'ed, just waiting for a merge

**Comment by alouane** [comment]
Thanks @acharis nice job ;)
