### ISSUE TITLE
2.1 Release Master Bug

### ISSUE THREAD

**Issue by michael-berlin** [youtube/vitess#2755]
Let's use this bug to post the general status of the 2.1 release.

I've created a RC1 release today (v2.1.0-rc.1). New Docker images have been pushed and the "release-2.1" branch was updated as well.

We expect minimal changes between RC1 and the final release.

**Comment by sougou** [comment]
Keep this bug open for 2.1.1 release?

**Comment by michael-berlin** [comment]
Nah.

This is done. For reference: We'll publish a 2.1.1 release soon because we have to cherry pick a fix in the vtgate binary for https://github.com/youtube/vitess/issues/2804

I'll announce the 2.1.1 release on our vitess-announce@ mailing list once it's out.
