### ISSUE TITLE
use "etcd2" plugin in Kubernetes examples

### ISSUE THREAD

**Issue by michael-berlin** [youtube/vitess#2756]
The example is still using the old "etcd" plugin and not the rewritten one which uses a different storage format ("etcd2"). More details: http://vitess.io/user-guide/topology-service.html#etcd-etcd2-implementation-new-version-of-etcd

I would like to change this in the Kubernetes configuration before we release 2.1.

**Comment by michael-berlin** [comment]
I'm moving this to the 3.0 milestone because I am no longer sure that this is a trivial task.

The new topo implementation "etcd2" will require at least etcd version 3 but our etcd Docker images are still on 2.0.13. That means we'll have to create and publish etcd 3 images first.

**Comment by alainjobart** [comment]
I was planning on removing 'etcd' and 'zookeeper' after 2.1. Maybe I'll look at this then.

**Comment by alainjobart** [comment]
So the examples/kubernetes directory now uses etcd2 with etcd-operator. What's left is @enisoc two directories:

* the helm/ directory
* the (not submitted yet) stateful set demo

So sending to @enisoc.

**Comment by enisoc** [comment]
As of #3582 the Helm chart now uses the `etcd2` implementation. The StatefulSet demo (#3311) doesn't need to be merged.
