### ISSUE TITLE
insert id gets lost for unsharded auto-inc from mysql

### ISSUE THREAD

**Issue by sougou** [youtube/vitess#2804]
A recent fix (#2576) accidentally missed the use case where there may still be mysql tables with traditional auto-inc columns.

@harshit-gangal do you need a 2.1 patch for this fix?

**Comment by bbeaudreault** [comment]
Yikes. Good find. This would be a problem for us, though we run master and can pull in a fix as soon as it's ready

**Comment by bbeaudreault** [comment]
I feel like this is worthy of a 2.1.1 though

**Comment by harshit-gangal** [comment]
Yes. It would be good to release the patch.
Otherwise we have to cherry pick.

**Comment by michael-berlin** [comment]
I can create a 2.1.1 release.

**Comment by sougou** [comment]
@harshit-gangal Let us know if you're done with the certification. If so, we can cut 2.1.1. Otherwise, we'll wait to see if you run into other issues.

**Comment by harshit-gangal** [comment]
I am validating 2PC. 

There is one finding, which we already have discussed that vttablet currently accept one coordinator address. If VTGates are not under service discovery / Load Balancer then there should be a way to add multiple coordinator addresses.

We can create a feature request and can work later, if we want to cut 2.1.1 as this is genuine bug.

**Comment by sougou** [comment]
Let's wait till you're done with 2PC then, make sure you don't run into any showstoppers.

**Comment by Rastusik** [comment]
@sougou are there any estimates when #v2.1.1 will be released?

**Comment by michael-berlin** [comment]
I'll start publishing the 2.1.1 release and only include the auto inc fix.

The 2PC validation went fine overall. harshit-gangal found a corner case which could be resolved manually if you run into it: https://github.com/youtube/vitess/issues/2850 Sugu will fix that separately and we can do another patch release once he's done with the fix.

**Comment by Rastusik** [comment]
thank you

**Comment by michael-berlin** [comment]
https://github.com/youtube/vitess/releases/tag/v2.1.1 is cut and pushed everywhere.

I'm closing this issue because it's fixed.
