### ISSUE TITLE
Make mysqlconn the default connection

### ISSUE THREAD

**Issue by bbeaudreault** [youtube/vitess#2806]
Now that 2.1 is released, this seems reasonably safe. AFAIK it's been running internally for YouTube for a while now.

**Comment by alainjobart** [comment]
I've been slacking off on this. It's not fully deployed internally yet, that's why I haven't done this. Give me a couple more weeks. :)

**Comment by alainjobart** [comment]
This PR has been submitted, it is done:
https://github.com/youtube/vitess/pull/2517
