### ISSUE TITLE
Should we transmit Session to vttablets?

### ISSUE THREAD

**Issue by sougou** [youtube/vitess#2814]
Tagging @alainjobart @michael-berlin 

There are many upcoming feature requests that require more state information to be shared with vttablets.

In the case of the (yet to be implemented) client_found_rows flag, the initial design we discussed was to make this a Session variable, but transmit it to vttablet through ExecuteOptions. However, ExecuteOptions is part of Session. So, storing this variable in ExecuteOptions would simplify code because VTGate could just pass it through without doing anything special.

However, there are other upcoming feature requests that require similar information to be passed through, and sometimes returned by vttablet. For example:
* last_insert_id
* Future ability to store reusable values inside `@` variables
* `SET` state, which will allow us to change a connection parameter to a certain state before executing a statement

In such cases, should we push those variables into ExecuteOptions, or do we rethink the design and consider sending the whole Session to vttablet?

For the second option, the con is that Session contains info that vttablet that doesn't need that we'll be unnecessarily exchanging.
Pros: Simpler code because VTGate doesn't have to mediate things that vttablet deals with. We can also consider folding ExecuteOptions into Session and have a simpler data structure.

**Comment by sougou** [comment]
For now, my main thought is to commandeer ExecuteOptions and rename it to TabletOptions. Variables that belong to VTGate only stay in Session, and those that belong to both or exclusively to VTTablet can go into TabletOptions.
Recently, `client_found_rows` was added to ExecuteOptions. We'll see how this evolves.

**Comment by michael-berlin** [comment]
Sounds reasonable to me :)

**Comment by bbeaudreault** [comment]
Sounds good to me too
