### ISSUE TITLE
vtctld ApplySchema doesn't work with vttablet and mysqld on separate machines

### ISSUE THREAD

**Issue by tirsen** [youtube/vitess#2818]
This is the error we're getting:
```
% 08:07 <franklin-vtctld@server:~ $ > vtctlclient -server $VTCTLD ApplySchema -sql '...' franklin_main
E0504 08:07:31.599053  316036 main.go:43] Remote error: rpc error: code = 2 desc = unable to get database schema, error: rpc error: code = 2 desc = TabletManager.GetSchema on sjc1-0000000101 error: Can't connect to local MySQL server through socket '' (111) (errno 2002) (sqlstate HY000)
```

**Comment by tirsen** [comment]
This is not top priority for us but I thought you should know.

**Comment by alainjobart** [comment]
This is expected given the current implementation, but can be fixed.

**Comment by alainjobart** [comment]
The code is there:
https://github.com/youtube/vitess/blob/master/go/vt/mysqlctl/mysqld.go#L813
it puts in socket=%s, it should check for socket to be empty, and if so, put host and port instead. Sugu will fix it :)
