### ISSUE TITLE
Error when running a RDONLY vttablet on a separate server than the mysqld

### ISSUE THREAD

**Issue by tirsen** [youtube/vitess#2819]
The health check shows:
```
Current status: unhealthy: replication_reporter: Can't connect to local MySQL server through socket '' (111) (errno 2002) (sqlstate HY000)
```

I see this in the logs:
```
2017-05-04_13:02:05.37689 W0504 13:02:04.066111  164784 action_agent.go:630] Cannot get current mysql port, not checking it: Can't connect to local MySQL server through socket '' (111) (errno 2002) (sqlstate HY000)
```

**Comment by alainjobart** [comment]
This one I'm not sure: mysqld.FetchSuperQuery should connect using the dba connection parameters, not hard-coding the socket...

The log you have is just a warning, which should probably be fixed, but unrelated.

**Comment by bbeaudreault** [comment]
I think @tirsen said on slack that this was actually due to missing the dba connection options. Can we close it @tirsen?
