### ISSUE TITLE
Not able to delete a shard

### ISSUE THREAD

**Issue by harshit-gangal** [youtube/vitess#2838]
There is a working shard
test_keyspace/-80 and test_keyspace/80-

Mistakenly, I created test_keyspace/0

Now, when I want to delete test_keyspace/0 it gives error
E0509 23:41:11.703055   16742 main.go:43] Remote error: rpc error: code = 2 desc = partial result

**Comment by alainjobart** [comment]
I don't really see where that comes from, by reading the code.

However, DeleteShard has a bunch of safely checks to make sure we don't delete a shard that has tablets. My guess is while trying to find the list of tablets for that bad shards, we don't get them all cleanly, and abort.

I would go through all the possible cells for that shard ('vtctl GetShard' to see them, look at Cells), and all the possible tablets for these cells for that shard, and 'vtctl DeleteTablet' them, until you have no more, then try again.

**Comment by harshit-gangal** [comment]
Below are the output for few commands, If this helps.

$ vtctl GetShard orchestrator/0
{
  "served_types": [
    {
      "tablet_type": 1
    },
    {
      "tablet_type": 2
    },
    {
      "tablet_type": 3
    }
  ],
  "cells": [
    "nm"
  ]
}

$ vtctl ValidateShard orchestrator/0
E0511 10:59:32.879382   25511 main.go:40] E0511 05:29:32.878510 validator.go:40] TopologyServer.FindAllTabletAliasesInShard(orchestrator, 0) failed: partial result
E0511 10:59:32.880571   25511 main.go:43] Remote error: rpc error: code = 2 desc = some validation errors - see log

$ vtctl ListShardTablets orchestrator/0
E0511 10:59:55.542562   25570 main.go:43] Remote error: rpc error: code = 2 desc = partial result

$ vtctl ListAllTablets nm 
nm-0000000005 lookup 0 master ...
nm-0000000006 lookup 0 replica ...
nm-0000000008 orchestrator -40 master ...
nm-0000000009 orchestrator -40 replica ...
nm-0000000011 orchestrator 40-80 master ...
nm-0000000012 orchestrator 40-80 replica ...
nm-0000000014 orchestrator 80-c0 master ...
nm-0000000015 orchestrator 80-c0 replica ...
nm-0000000017 orchestrator c0- master ...
nm-0000000018 orchestrator c0- replica ...

**Comment by michael-berlin** [comment]
Can you tell us which version of Vitess you're running? Alain couldn't match the error with the current code in the master branch.

**Comment by harshit-gangal** [comment]
This is 2.0

**Comment by alainjobart** [comment]
I see it in 2.0, it was probably changed after:
tabletMap, err := wr.ts.GetTabletMapForShard(ctx, keyspace, shard)
if err != nil {
	return err
}
So that's what's going on, a partial result there makes it not go forward.

Can you please run:
vtctl GetShardReplication nm orchestrator/0
And copy the result? In there there's probably a tablet or two that don't exist any more.

If that's the case, run:
vtctl ShardReplicationRemove orchestrator/0 nm-XXXX
where nm-XXXX is the alias of the tablets that shouldn't be there.

When that's done, the initial command should work again...

**Comment by harshit-gangal** [comment]
As this was blocking any DDL query executing in prod. So, I went ahead and deleted the path from zookeeper manually.

But AFAIK, the only entry that exists were /zk/global/keyspaces/orchestrator/shards/0 -> action and actionlog

**Comment by alainjobart** [comment]
On a somewhat related subject, what is your guys plan to upgrade to 2.1? And to migrate to the new 'zk2' topology implementation? As 2.1 is released now, I'm going to remove 'zookeeper' as a topology server option...

**Comment by harshit-gangal** [comment]
Currently may sale is on. Migration will happen in June 1st-2nd week.

**Comment by sougou** [comment]
Closing this as obsolete.
