### ISSUE TITLE
Query with a leading multi-line /* */ comment not recognized by vtgate

### ISSUE THREAD

**Issue by tirsen** [youtube/vitess#2861]
After recently upgrading vtgate we've started getting the following errors from vtgate (slightly edited):
```
vtgate: http://apa4.sjc1.square:31901/: unrecognized statement: /* criteria query */ select this_.id as id1_35_0_, this_.created_at as created_2_35_0_, this_.updated_at as updated_3_35_0_, ... more columns..., this_.name as name7_35_0_ from mytable this_
```

I think the issues is the leading comment `/* criteria query */`. I'm going to see if disabling those in Hibernate helps.

**Comment by sougou** [comment]
Yes. The new query previewer is a simple but efficient way to identify the statement type. It assumes that the first word is the start of the query. I'd like to avoid complicating it so it remains efficient. If it's unavoidable, I can add logic to strip leading comments, but it's a price all queries will have to pay.

**Comment by tirsen** [comment]
I think you might not have a choice. :-( This is the SQL that Hibernate generates. Hibernate is the most popular ORM framework for Java. If you don't support Hibernate you're going to face an uphill struggle with adoption. :-(
