### ISSUE TITLE
vttablet and auto detection of the MySQL flavor

### ISSUE THREAD

**Issue by sjmudd** [youtube/vitess#2877]
I noticed that I need to explicitly tell vitess which MySQL flavour I'm talking to.
I think that given the versions of MySQL / MariaDB that are supported this should be straight-forward.  I believe that Vitess uses `SELECT VERSION()` to find the version.

As far as I know the following "rules" should be pretty good at making that distinction:
* `/^(5\.[67]|8\.0)/` should match for MySQL56 flavours 5.6, 5.7 and 8.0 for MySQL and Percona Server
* `/^10\.[0123]\..*-MariaDB/` should match for MariaDB 10.0-10.3

Recognising this information automatically avoids the user having to explicitly check this so it would be good if this could be detected automatically.

Also should the environment variable `MYSQL_FLAVOR` be set and not be understood an error message indicating valid values would avoid the user having to lookup which values are permitted.  This was triggered when first starting up `vttablet`.

**Comment by alainjobart** [comment]
The code to auto-detect the flavor is there:
https://github.com/youtube/vitess/blob/master/go/vt/mysqlctl/mysql_flavor.go#L126
But it is not used consistently in the code base. Also, this code should be somewhat refactored and moved to go/mysql so it can use the server version returned at connection time, and avoid a round trip with a query.

Also, there are two layers that need the version: the replication / binlog layer to know which GTID implementation to use, and the go/vt/mysqlctl layer, to know what SQL commands to execute for reparenting. This is confusing, and unnecessary. Both should be collocated in the go/mysql package.

**Comment by alainjobart** [comment]
Started to work on this in this PR:
https://github.com/youtube/vitess/pull/2977

**Comment by alainjobart** [comment]
All the golang code now will auto-detect the flavor. However, we still need MYSQL_FLAVOR environment variable in a few places:
- creation of the my.cnf with the right templates (from mysqlctl)
- integration tests, as they don't know which version is there
- some unit tests in go/mysql/endtoend that only depend on the client (and therefore don't have a server version to connect to for auto-detect.
I'll try to to tackle some of these over time.

**Comment by sougou** [comment]
@alainjobart I think this is addressed to the extent possible. Close this?
