### ISSUE TITLE
character set "introducer" support

### ISSUE THREAD

**Issue by slanning** [youtube/vitess#2890]
Queries that look like
`WHERE some_binary_id = _binary 'gobbledygook'`
give an error at the quote mark, since `_binary` isn't recognized.

Not sure if you want to support these [character set introducers](https://dev.mysql.com/doc/refman/5.7/en/charset-introducer.html).

**Comment by sougou** [comment]
@bbeaudreault @acharis want to tackle this?

**Comment by bbeaudreault** [comment]
We tried to implement this in the past, but encountered shift/reduce conflicts: https://github.com/youtube/vitess/issues/2466#issuecomment-276198208

**Comment by sougou** [comment]
Ahh. Let's keep this bug open then. I'll take a look later to see how deep this rabbit-hole is.

**Comment by acharis** [comment]
@xhh1989 
what's the difference between:
`select 1 from t where foo = binary 'bar'`
and
`select 1 from t where foo = _binary 'bar'`
??

**Comment by sougou** [comment]
`binary` is a cast function whereas `_binary` is a qualifier. You can do `binary expr`, but a `_binary` should be followed by a literal.

**Comment by acharis** [comment]
TIL
