### ISSUE TITLE
Support for cross-shard aggregations

### ISSUE THREAD

**Issue by sougou** [youtube/vitess#2897]
V3 only supports aggregations that can be fully pushed down to individual shards. But there are many practical use cases for cross-shard aggregations that require VTGate to do additional work.

It would be good to support the most common of those use cases, if not all.

**Comment by sougou** [comment]
There are three strategies to implement cross-shard aggregations. They stem from the fact that vtgates are lightweight and cannot process more than a few thousand rows at a time:
1. Aggregate as you stream: If most of the grouping and ordering can be done by mysql, vtgate could do the final work as the rows are streamed. This strategy allows you to fetch large results.
2. Get all rows and perform processing in-memory. This strategy will allow vtgate to perform operations of any complexity, but will work only if the rowset is small.
3. Map-reduce: This strategy can be used when 1 & 2 cannot be performed. This will involve multiple proxies fetching partial results and then passing them on to reducers that can perform the next stage of processing.

I'll initially start off with strategy 1. This will cover the following use cases:
* Scatter queries where the group by can be pushed down to each shard and where the results come in sorted order. This will allow vtgate to perform the final grouping and continue streaming 'as the rows come'.
* Scatter queries where ordering can be pushed down, which allows VTGate to merge-sort results as they come.
* Combination of group by and ordering as long as the ordering does not conflict with the group by order.
* Limit queries where the limit can be pushed down, and the final limit be reapplied on the streaming result.

Specifically, I plan to implement the ability to order and aggregate from ordered streams, which will allow us to support:
* `select count(*) ...`
* `select distinct ...`
* `select a, b, c, d, count(*) ... group by a, b, c...`
* `select (like above) order by b desc, a`
* `select (like above) limit 10`: For any of the above operations, a limit can be requested.

The above queries will work for both streaming and non-streaming requests.

Unsupported:
* Additional filtering through the `having` clause. This can be added if it's a blocker for someone.
* Expressions that use aggregates, like `1+count(*)`.
* Ordering that needs to be performed after aggregation: `order by count(*)`.
* Aggregates from cross-shard joins.
* Non-standard use like grouping by a column not listed in the select expression.

Phase 2:
This phase will involve building primitives that can perform operations in-memory. I can implement on-demand features here. The limitation is that the rowset be small.

Phase 3:
Distant future. The work-around for now is to run your own map-reduce operations.

If there are constructs that you need immediately supported, but are not listed above. Let me know, and we can scope it to see what it will take.

**Comment by harshit-gangal** [comment]
Will this change also serve
select shardKey, pKey, a, b, c from test_table order by b, a limit 10;
or this will be implemented in phase 2 ?

**Comment by sougou** [comment]
The should be in phase 1. I've updated the comment with the following text:

Since the above algorithm is the following steps: Scatter an ordered query -> merge sort -> aggregate, we can also support constructs that require only the first two steps:

* `select ... order by a, b, c`
* `select (like above) limit 10`
