### ISSUE TITLE
web UI: /api/tablets/ path seems to be hard coded and ignores the base path i.e. it doesn't work with Kubernetes proxy

### ISSUE THREAD

**Issue by michael-berlin** [youtube/vitess#2900]
I noticed this issue myself and somebody else recently reported it as well.

Because of this bug, you don't see the list of tablets once you selected a shard in the UI.

**Comment by michael-berlin** [comment]
User report: https://groups.google.com/d/topic/vitess/ge1iai3kg8k/discussion

**Comment by rnavarro** [comment]
Oops, I meant to report this one a while back...I've seen this too.

+1

**Comment by giaquinti** [comment]
There's a _kind of similar_ issue also in the `vtgate` web UI. We are exposing it via a reverse proxy and all the links in the "TabletStats" column are using an hardcoded `http://<hostname>:<http_port>/`

**Comment by fuyar** [comment]
Got that also, just fired up the kubernetes example and got that error 
`POST http://localhost:8001/api/tablets/ 404 (Not Found)
Error getting tablet list`

**Comment by skymeyer** [comment]
You can work around it by using `kubectl port-forward` to the `vtctld` pod directly:
```
kubectl --namespace=vitess port-forward vtctld-xxx 15000
```
Replace `vtctld-xxx` with your pod name and then hit `http://127.0.0.1:15000`.

**Comment by guidoiaquinti** [comment]
We don't use k8s

**Comment by alainjobart** [comment]
Should be fixed by https://github.com/youtube/vitess/pull/3390
(I ran into it as well, and found the fix quickly :) )

**Comment by alainjobart** [comment]
Verified the fix worked, closing this.
