### ISSUE TITLE
vttablets fail to start after latest upgrade to master

### ISSUE THREAD

**Issue by rnavarro** [youtube/vitess#2901]
I noticed this in my stage cluster.

After upgrading to dcf21a26be84f02ae25afe3329dfd8de61690a3e on master my tablets no longer start up.

Here are the logs:
vttablet container
```
I0531 21:40:30.844303      17 streamlog.go:122] Streaming logs from TabletServer at /debug/querylog.
I0531 21:40:30.844535      17 streamlog.go:122] Streaming logs from TxLog at /debug/txlog.
I0531 21:40:30.844612      17 mycnf_flag.go:126] No mycnf_server_id, no mycnf-file specified, using default config for server id 11: /vt/vtdataroot/vt_0000000011/my.cnf
F0531 21:40:30.844748      17 vttablet.go:77] mycnf read failed: Value for key 'tmpdir' not set
```

mysql container
```
rm: cannot remove '/vt/vtdataroot/vt_0000000011/mysql.sock.lock': No such file or directory
I0531 21:40:30.778994      15 mysqlctld.go:91] mycnf file (/vt/vtdataroot/vt_0000000011/my.cnf) already exists, starting without init
E0531 21:40:30.779290      15 mysqlctld.go:96] failed to find mysql config: couldn't read my.cnf file: Value for key 'tmpdir' not set
```

@bbeaudreault Suggested the following change in slack:

i think we should make this change in mycnf.go:

```
-       mycnf.TmpDir = mycnf.lookupAndCheck("tmpdir")
-       mycnf.SlaveLoadTmpDir = mycnf.lookupAndCheck("slave_load_tmpdir")
+       mycnf.TmpDir = mycnf.lookup("tmpdir")
+       mycnf.SlaveLoadTmpDir = mycnf.lookup("slave_load_tmpdir")
```

**Comment by bbeaudreault** [comment]
Upon further investigation, I think the change should be slightly (but not too much) more involved. Basically we should unify mycnf_gen.go's NewMycnf and mycnf.go's ReadMycnf.  The issue here is we need to provide default values. Currently there is a lookupAndCheck and a lookup. I think both should be replaced with a `lookupOrDefault` which fails/returns an error when no default is specified.

**Comment by bbeaudreault** [comment]
https://github.com/youtube/vitess/pull/2904

**Comment by sougou** [comment]
@bbeaudreault @rnavarro ok to close this?

**Comment by bbeaudreault** [comment]
Will let @rnavarro confirm, but I believe this is fixed.

**Comment by rnavarro** [comment]
Confirmed, we can close
