### ISSUE TITLE
Some way of figuring out to which shard a record would go

### ISSUE THREAD

**Issue by tirsen** [youtube/vitess#2918]
Given a "vindexed" column and a value, return the shard id.

Preferably through some kind of metadata SQL syntax so that we can do it even over the MySQL protocol.

For example (this is the best I've come up with, I'm sure you can do better!):
```
SELECT shard('mytable', 'id', 123);
=> 'mykeyspace/-80'
```

**Comment by sougou** [comment]
#3076
