### ISSUE TITLE
Unify the Vitess type system

### ISSUE THREAD

**Issue by sougou** [youtube/vitess#2919]
The vitess type system is mostly unified under sqltypes and querypb. But there are still a few stragglers that are causing code fragmentation:
* Bind variables have two representations, one from querypb, and the other as map[string]interface{}. The latter allows non-sqltype values to be added to it and there are many places in the code that still do.
* Plan building by vttablet and vtgate use a 'Values' field which is of type interface{}. This is either a value supplied in the query, or the name of a bind var. There are subtle differences between how vtgate stores values vs. vttablet.

The complication is that some of these values are non-standard that cannot be represented in sqltypes.Value. We need either extend the capabilities of sqltypes, or come up with some higher level wrappers that provide the necessary extensions.

As the code grows, some areas are getting increasingly confusing. So, this work will have to be prioritized soon.

**Comment by sougou** [comment]
@alainjobart 
In order to perform more optimizations to address #2849, we need the ability to handle the new `string literal` type gracefully. This requires the type system to be cleaned up. So, I'm going to start with addressing phase 1 of this issue first.

## Change bind vars type to map[string]*querypb.BindVariable

The purpose of this change is to simplify handling of bind vars and also make it more efficient by avoiding repeated conversions and validations.

### Validation

Bind vars are currently transmitted as proto variables, but converted to map[string]interface{} at entry points. The vtgate or vttablet processes then add more entries to this map, but the value can be any go type or sqltypes.Value. This makes it confusing for bind var handlers because they don't know what to expect in such a map. So, they have to handle all possible types, and they also have to conservatively perform validity checks on any *querypb.BindVariable they encounter.

To remove this confusion, bind vars will be validated by vtgate at entry point. Any new entries added to the map will be created as *querypb.BindVariable and certified as valid by the creator. All other parts of the system can trust the bind var to be validated.

### The meaning of validity

A valid bind variable is one that parses correctly. This means that something like an Int64 contains a valid int number. There is no guarantee that the value is canonically represented. The only guarantee is that the value can be safely encoded as SQL.

### Conversion to sqltypes.Value

A bind variable can be cheaply converted to an sqltypes.Value because the validity guarantees are the same. You can then use comparison functions in arithmetic.go, which perform safe conversions before comparing values.

I'm likely to remove `Raw`, `String` and `Bytes`, and provide a more formal set of functions that will return a canonical representation of a Value, which will allow us to use it in places where values need to be understood: Vindexes, DML comments and other such places.

### Exceptions

In vttablet, we use some special bind variable types like TupleEqualityList that helps us generate the final query efficiently. Fortunately, the part of the code is at the lowest level and isolated. I may make an exception here and continue using a `map[string]interface{}` for just this part.

**Comment by alainjobart** [comment]
I agree with this, in fact I may have been the one talking about it first. :)

**Comment by sougou** [comment]
yes :)
