### ISSUE TITLE
MySQL streaming protocol support

### ISSUE THREAD

**Issue by sougou** [youtube/vitess#2933]
The current MySQL protocol only uses the non-streaming version of VTGate (Execute). We also need to support the streaming version (StreamExecute).

Why not stream always? Execute gives you some benefits that Stream does not:
1. It can have shorter timeouts and limit rowcount. These two features protect the databases from accidental abuse.
2. Because Execute does everything in memory, it may be able to fulfill some queries that StreamExecute may not.

So, it's a good idea to support both options. There are multiple ways this can be supported:
1. `SET STREAMING=1 // or 0`: This option allows you to initialize a connection for streaming at the beginning, or switch back and forth as needed. The main advantage is that this can be deployed at the connection level, and the app doesn't have to change much.
2. Extend USE syntax: Something like `USE keyspace:shard@rdonly+streaming`. One problem with this approach is that the USE statement gets too complicated. The other problem is that streaming is a protocol requests. So, trying to overload USE for it feels incorrect. Upside is that you don't have to make the extra `SET STREAMING` request.
3. Automatically use streaming if it's `@rdonly`: The idea is that rdonly should be the tablet type you should be streaming from. The master and replica types are for OLTP workloads. This feels very inflexible. Just suggesting this for completeness.
4. Query hints like `SELECT /* streaming */ ...`: The upside is that a query is usually written for streaming (or not). So, this makes sense in some way. Downside is that all call-sites will have to be hunted down and changed. This gets even harder if there's an ORM layer in the middle.

Feel free to share your thoughts. If there are no strong opinions, I'm likely to go with option 1.

**Comment by acharis** [comment]
if i can vote for two options, i'd vote for 1 and 4. i'm not sure which of those i prefer if i can only vote for one.

**Comment by sougou** [comment]
Fifth option: provide a separate port for streaming. However, VTGate already has three ports now: http, grpc and mysql.

**Comment by bbeaudreault** [comment]
I think we should make it compatible with the useCursorFetch option of the oracle/mysql jdbc -- in sure other MySQL clients have a similar setting. Not totally sure how that translates into protocol options, will need to check the code.

**Comment by harshit-gangal** [comment]
In JDBC specification, if we set fetchSize(int) on a statement object then
any select query through that object should stream results.
So, I think option 1 should be there to enable stream at any time.

**Comment by sougou** [comment]
Note that this is only for the MySQL protocol. For grpc, the API is already split between Execute and StreamExecute. This is something we have to independently revisit. Maybe think about consolidating the two.

As for the wire protocol for MySQL, it always streams. So, the differences are the functional parts, which could be renamed to OLTP vs OLAP:

* OLTP allows DMLs, has aggressive timeouts and limits rowcounts.
* OLAP: Only selects, generous timeouts and indefinitely large result sets.

**Comment by sougou** [comment]
### Short term
* Add a field to `ExecuteOptions` called `workload`. It can be `oltp` or `olap`. The reason why it should be in ExecuteOptions is because the field will also be sent to vttablet. Justification below.
* This field can be set through the `SET WORKLOAD='OLTP'` SQL command. For now, it will only be used by the mysql protocol. The difference in behavior will be as described in my previous post.

### Longer term
* We can change grpc to always use `StreamExecute` and deprecate `Execute`. StreamExecute is more memory efficient than Execute. The current downside is that it sends at least two packets per request, which can be easily fixed. Once this is done, the grpc clients can get the older `Execute` functionality by calling `StreamExecute` with `workload` set to `oltp`.
* `ExecuteBatch` can also be taken over by StreamExecute by making it accept semi-colon separated statements and return multiple results. This will fulfill most existing use cases, and will also extend gracefully for the mysql protocol. We may still have to build special functions for the parallel execution use case.
* The workload flag will need to be sent to vttablet because it also needs to behave differently when its StreamExecute is called. This is why the flag should be in `ExecuteOptions`.
