### ISSUE TITLE
ERROR: table dual not found

### ISSUE THREAD

**Issue by ankit-jain-applift** [youtube/vitess#2952]
When establishing connection to mysql from a jdbc driver (mysql-connector-j) it tries to run a sample query:
`select @@version_comment limit 1`

VTGate throws an error for this:
ERROR 1105 (HY000): vtgate: http://hostname:port/: table dual not found

There are queries for other session and environment variables too
` vtgate.go:933] Execute: table dual not found, request: map[Sql:/* mysql-connector-java-5.1.38 ( Revision: fe541c166cec739c74cc727c5da96c1028b4834a ) */SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_buffer_length AS net_buffer_length, @@net_write_timeout AS net_write_timeout, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@tx_isolation AS tx_isolation, @@wait_timeout AS wait_timeout BindVariables:map[] Session:target_string:"fcapdb" options:<included_fields:ALL client_found_rows:true > ] `

**Comment by michael-berlin** [comment]
Sugu, the error is probably that vtgate tries to find the "dual" table in the vschema and of course it doesn't exist there?

**Comment by sougou** [comment]
Yeah. I've been working with him. The call would work if the specified target is an unsharded keyspace, but it becomes ambiguous for sharded ones where vtgate intervenes more with its own behavior.

I'm thinking of assigning reasonable defaults to those vars and returning them as canned response.

**Comment by ankit-jain-applift** [comment]
Will it also work to just send these queries to one of the shards (Some kind of a bypass) and return back the result as is. This will take care of all such cases and may also work for those that might need a different value from the canned response.

**Comment by sougou** [comment]
I'm looking at that option also. Send it to the first shard of a default keyspace.

**Comment by sougou** [comment]
I ran into a possible issue with the default keyspace approach. I was planning on categorizing these statements as ExecDBA, which would execute them on the first shard of any keyspace outside of the existing transaction. However, this would also affect `select last_insert_id()`, which needs to honor transaction scope.

So, I'll either have to create a brand new Opcode for this, or go back to canned responses.
