### ISSUE TITLE
Stopping vtctld seems to cause a panic

### ISSUE THREAD

**Issue by sjmudd** [youtube/vitess#2955]
#2921 This may be triggered by a bad config but I'm not sure. Trying to stop `vtctld` by using kill as suggested in the `examples/local/vtctld-down.sh` script seems to generate a panic.

```
[user@myhost]$ ./vtctld-down.sh
Stopping vtctld...
I0622 10:52:11.540834   33600 run.go:53] Entering lameduck mode for at least 50ms
I0622 10:52:11.540893   33600 run.go:54] Firing asynchronous OnTerm hooks
I0622 10:52:11.540918   33600 servenv.go:151] Firing synchronous OnTermSync hooks and waiting up to 10s for them
I0622 10:52:11.540954   33600 election.go:153] Canceling leadership 'vtctld' upon Stop.
[user@myhost]$ panic: close of closed channel

goroutine 114 [running]:
github.com/youtube/vitess/go/vt/topo/zk2topo.(*zkMasterParticipation).WaitForMastership(0xc42013ae10, 0x7fb5a237c0c0, 0xc420144140, 0x0, 0x0)
        /home/myuser/src/youtube_vitess/src/github.com/youtube/vitess/go/vt/topo/zk2topo/election.go:101 +0x6f1
github.com/youtube/vitess/go/vt/vtctld.runWorkflowManagerElection.func1.2(0xc420198df0)
        /home/myuser/src/youtube_vitess/src/github.com/youtube/vitess/go/vt/vtctld/workflow.go:114 +0x37
created by github.com/youtube/vitess/go/vt/vtctld.runWorkflowManagerElection.func1
        /home/myuser/src/youtube_vitess/src/github.com/youtube/vitess/go/vt/vtctld/workflow.go:125 +0x1a1
```

So maybe the panic isn't a big thing as you're killing the process anyway. It just looks ugly.

My vtctld-up script had `-alsologtostderr` which is why there was some logging being shown in the background.

If you need more details let me know.
The commit I'm seeing this on is: `9f5965c61a8fbc`.

**Comment by sougou** [comment]
@alainjobart It appears that this happens because multiple functions of zkMasterParticipation can be running at the same time. When the context gets canceled, they all close the same mp.done channel, which causes the panic. Should I change it to use a waitgroup instead?

Are similar changes needed in the other topos?
