### ISSUE TITLE
Check errant transaction on tablet replicas before changing replication topology

### ISSUE THREAD

**Issue by giaquinti** [youtube/vitess#2989]
Creating this issue to keep track in GH of our previous [discussion](https://vitess.slack.com/archives/C0PQY0PTK/p1499781816829230)

> guido: what do you think about adding a check to detect errant transaction on tablet replicas before allowing Vitess to change replication topology? Yesterday we had some issue reparenting our cluster as few "Vitess unrelated transactions" were executed directly on replicas. This broke replication while reparenting.
[...]
> sougou: guido that's a very good idea. I think it will work only for MySQL flavor, but it may be worth doing it for just that. Pinging @alainjobart to see what he thinks.

**Comment by sougou** [comment]
This was serendipitously fixed by https://github.com/youtube/vitess/pull/3091.
