### ISSUE TITLE
Ability to reset shard targeting with a SQL statement

### ISSUE THREAD

**Issue by tirsen** [youtube/vitess#3001]
Currently we can do this to target a specific shard:
```
USE mykeyspace/-80
```

We also need the ability to "untarget" a shard and go back to untargetted "mode". I don't know what's a good syntax because the parameter to use is "preqouted", i.e. doing `USE NULL` actually means use the database named "null". Maybe just a nullary USE call?
```
USE
```

**Comment by sougou** [comment]
Addressed via #3058
