### ISSUE TITLE
Add caller id information to tablet errors

### ISSUE THREAD

**Issue by bbeaudreault** [youtube/vitess#3016]
At hubspot we have 1000s of deployables and even a single mysql maybe used by 10s. When we get an error, we find ourselves in the painful process of searching code for snippets of a dynamically generated query. This is not always fruitful and so we have to somewhat blindly ask some teams if the query looks familiar.

However, we also use the gRPC authentication for all users of vitess, which means that the context has the immediate caller id in it.  Would it be possible to add this context to the errors somehow? I was thinking we could pass hte ctx in here: https://github.com/youtube/vitess/blob/master/go/vt/vttablet/tabletserver/tabletserver.go#L1242 and call `callerid.ImmediateCallerIDFromContext` on it.

Thoughts?

**Comment by bbeaudreault** [comment]
We'd be happy to do the work for this, mostly looking for comments from the youtube folks

**Comment by alainjobart** [comment]
Yes, that sounds useful, and the way you're suggesting to implement it sounds good too. Go for it!
