### ISSUE TITLE
A direct way of getting which shard a record belongs to

### ISSUE THREAD

**Issue by tirsen** [youtube/vitess#3076]
There are times when we need to know up front which shard a record belongs to. Right now we iterate through all shards and do a `SELECT COUNT(*) FROM table WHERE id = ?` query to see if the shard contains the record.

This is fine for the time being because we won't have that many shards for the next year or so. But eventually we will have 100s of shards and it won't be very nice any more.

It would be nice with a more direct way.

**Comment by sougou** [comment]
I think you've reported this before, or something similar: #2918.
I'll try to prioritize this.
