### ISSUE TITLE
Route REPLICA traffic cross cells

### ISSUE THREAD

**Issue by tirsen** [youtube/vitess#3099]
vtgate can currently route MASTER traffic to another cell if there is no MASTER locally. We should do the same with REPLICA traffic.

**Comment by alainjobart** [comment]
The logic is mostly there:
https://github.com/youtube/vitess/blob/master/go/vt/discovery/tablet_stats_cache.go#L147
Where we ignore non-master updates from different cells. The logic in that method would have to change to not only accept these updates, but use them the right way.

I believe this new behavior should be driven by flags, so the default behavior remains the same.

(an advanced way of doing this would be to define 'distance' between cells, and fallback to the 'closer' cell. But this may be too much.)

**Comment by sougou** [comment]
After looking at the code for this, I found two issues:
1. The current and remote cells may have a different topology, especially during resharding. So, if no tablet is available locally, the logic has to perform a fresh re-resolve top-down for the target cell.
2. For complex queries, VTGate will perform multiple round-trips to the remote cell, which can become potentially very slow.

So, I'm thinking the problem may be better addressed by redirecting the request to a remote vttablet, which will address both the above problems better. We do have to make sure they don't get into a redirect loop.

**Comment by tirsen** [comment]
I don't understand why these two issues are different for a REPLICA tablet compared to a MASTER tablet. Don't you have those issues in both cases?

Sure, we can route to a separate vtgate at the app level, that's what we do now. But my expectations are that Vitess deals with query routing, not the app. The fact it can route queries most of the time but just not in this very special case is confusing to me and I know Vitess pretty well. I think it will be even more confusing to a new user of Vitess.

So let's not cop out on this, let's figure out a solution. Can we get Vitess to route to a separate vtgate?

**Comment by sougou** [comment]
That's what I was implying, that the routing should be done by vtgate at a higher level.

**Comment by demmer** [comment]
@tirsen Does the latest comment I made in #3355 suffice for your use case?

**Comment by tirsen** [comment]
@demmer Yes I like your proposal. We don't currently need it because we're routing at the app/vtgate level instead but I think your proposal seems useful enough we may look into using that instead.

**Comment by sougou** [comment]
Dup of #3355
