### ISSUE TITLE
Proposal: expose a counter on query cache eviction in vttablet

### ISSUE THREAD

**Issue by guidoiaquinti** [youtube/vitess#3113]
Right now there isn't a way to measure the `vttablet` query cache eviction rate. I think it could be useful to add a counter for it.

**Comment by sougou** [comment]
The query cache reports the age of the oldest item in the list as `QueryCacheOldest`. The main intent of that variable was for tracking the effectiveness of the cache.

But it may be useful to just count the number of items evicted.

**Comment by demmer** [comment]
Yeah the count is easily aggregated across a cluster which is much harder for per tablet dates. 

-m
