### ISSUE TITLE
Some wrong

### ISSUE THREAD

**Issue by peng19832** [youtube/vitess#3125]
Successfully installed enum34-1.1.6 futures-3.1.1 grpcio-1.0.4 protobuf-3.4.0 setuptools-36.3.0 six-1.10.0
+ '[' -n '' ']'
Installing dev tools with 'go get'...
package golang.org/x/tools/go/gcexportdata: unrecognized import path "golang.org/x/tools/go/gcexportdata" (https fetch: Get https://golang.org/x/tools/go/gcexportdata?go-get=1: dial tcp 216.239.37.1:443: getsockopt: connection refused)
package golang.org/x/tools/cmd/goimports: unrecognized import path "golang.org/x/tools/cmd/goimports" (https fetch: Get https://golang.org/x/tools/cmd/goimports?go-get=1: dial tcp 216.239.37.1:443: getsockopt: connection refused)
package golang.org/x/tools/cmd/goyacc: unrecognized import path "golang.org/x/tools/cmd/goyacc" (https fetch: Get https://golang.org/x/tools/cmd/goyacc?go-get=1: dial tcp 216.239.37.1:443: getsockopt: connection refused)
package golang.org/x/tools/go/loader: unrecognized import path "golang.org/x/tools/go/loader" (https fetch: Get https://golang.org/x/tools/go/loader?go-get=1: dial tcp 216.239.37.1:443: getsockopt: connection refused)
package golang.org/x/tools/go/ast/astutil: unrecognized import path "golang.org/x/tools/go/ast/astutil" (https fetch: Get https://golang.org/x/tools/go/ast/astutil?go-get=1: dial tcp 216.239.37.1:443: getsockopt: connection refused)
package golang.org/x/tools/go/types/typeutil: unrecognized import path "golang.org/x/tools/go/types/typeutil" (https fetch: Get https://golang.org/x/tools/go/types/typeutil?go-get=1: dial tcp 216.239.37.1:443: getsockopt: connection refused)
package golang.org/x/tools/cmd/cover: unrecognized import path "golang.org/x/tools/cmd/cover" (https fetch: Get https://golang.org/x/tools/cmd/cover?go-get=1: dial tcp 216.239.37.1:443: getsockopt: connection refused)
ERROR: Failed to download some Go tools with 'go get'. Please re-run bootstrap.sh in case of transient errors.

**Comment by michael-berlin** [comment]
The key here is:

> dial tcp 216.239.37.1:443: getsockopt: connection refused

Maybe it was a transient issue?

Can you browse e.g. https://golang.org/x/tools/cmd/cover?go-get=1 ?

It's working for me (located at West Coast, USA).

**Comment by peng19832** [comment]
Oh
It‘s redirected:
https://godoc.org/golang.org/x/tools/cmd/cover

**Comment by sougou** [comment]
I assume this is addressed. I'll close this if there is no further update on this.

**Comment by JerryCui** [comment]
Did anyone get this resolution?　I had the same error

**Comment by sougou** [comment]
If you're getting 'connection refused' errors, you may need to check your internet connectivity. It's also possible that the site you're accessing is temporarily down, or you may have a misconfigured proxy.
