### ISSUE TITLE
Query parse error

### ISSUE THREAD

**Issue by rnavarro** [youtube/vitess#3149]
I think this is a regression.

I have a query like this:

`SELECT
   af.`<col_3>`,
   DATE_FORMAT(MAX(af.`<col_1>`), '%Y;%m;%e;23;59;59') fiscalEndDate,
   DATE_FORMAT(DATE_ADD(MAX(af.`<col_1>`), INTERVAL 1 YEAR), '%Y;%m;%e;23;59;59') fiscalAddDate,
   MAX(af.`<col_1>`) fiscalEndDateForSort 
FROM
   `<table>` af 
WHERE
   af.`<col_2>` = '1' 
   AND af.`<col_3>` IN (123)
GROUP BY
   af.`<col_3>`;`

MySQL returns this error:

`select
   af.<col_3>,
   DATE_FORMAT(MAX(af.<col_1>), '%Y;%m;%e;23;59;59') as fiscalEndDate,
   DATE_FORMAT(DATE_ADD(MAX(af.<col_1>), interval 1 `year`), '%Y;%m;%e;23;59;59') as fiscalAddDate,
   MAX(af.<col_1>) as fiscalEndDateForSort 
from
   <table> as af 
where
   af.<col_2> = '1' 
   and af.<col_3> in (123)
group by
   af.<col_3> limit 10001;`

The issue is here:
INTERVAL 1 YEAR) --> interval 1 \`year\`)

I think this issue is happening at the vttablet level?

**Comment by demmer** [comment]
This could be caused by the recent changes to support the `create table` DDLs since YEAR is now a keyword.

**Comment by bbeaudreault** [comment]
I think we need to change IntervalExpr's Unit field to not be a `ColIdent`.  @demmer is correct, that adding `YEAR` as a keyword caused it to become quoted due to https://github.com/youtube/vitess/blob/master/go/vt/sqlparser/ast.go#L2783. Not sure if there's a reason to make Unit a ColIdent

**Comment by bbeaudreault** [comment]
Yea, colident seems unnecessary. Here's the docs on that UNIT field: https://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html#function_date-add
