### ISSUE TITLE
Handle re-used ip:port addresses in vtgate healthcheck/discoverygateway

### ISSUE THREAD

**Issue by bbeaudreault** [youtube/vitess#3156]
In our kubernetes environment, each pod (tablet+mysql, etc) gets its own ip address that is routable from the rest of our network. Each kubernetes node is given 128 addresses to use, and docker allocates them to pods as they start up on the node. Unfortunately in our version of docker (which we cant upgrade due to k8s constraints), docker allocates these IP addresses in a lowest-first manner. It works like this:

If node A has pods 1 (1.1.1.1), 2 (2.2.2.2), and 3 (3.3.3.3), and pod 1 moves off host, ip 1.1.1.1 will be given to the next pod to be created on node A. So if pod 4 comes in, it will now have that IP, resulting in:  pod 4 (1.1.1.1), 2 (2.2.2.2), 3 (3.3.3.3).

This has a major implication for vtgate. Vtgate uses the ip:port as the TabletMapKey in the discoverygateway. So when the above happens, vtgate still thinks 1.1.1.1 is pod 1, and the address is routable but routes to pod 4.

Prior to https://github.com/youtube/vitess/pull/3004 we saw cause confusing errors where vtgate would send queries to the wrong tablets. With that PR, I added validation which causes the healthcheck to error out instead.  This worked reasonably well when we used CNAMEs as our `tablet_hostname`, but for other reasons we need to move to IP address now.

In a recent reproduction in a test cluster, you can see the aftermath of a full rolling restart of pods:

<img width="1554" alt="screen shot 2017-09-10 at 1 57 40 pm" src="https://user-images.githubusercontent.com/116591/30252386-6e878a5c-963f-11e7-8ec5-726dd969e0fe.png">

This was a mild case because in this cluster there are less pods to conflict with, so that no keyspace-shards were left without a serving tablet. But in our QA cluster which has ~500+ pods, we see issues where all the tablets for a keyspace-shard have the above error and the keyspace-shard is left `UNAVAILABLE`.

I've started digging into a fix for this and have a couple ideas so far:

- Fix the topology watcher to clean these up when they run, by checking the alias in the tablet map: https://github.com/HubSpot/vitess/commit/fad9557f76d9b2a2eb2226bf476434f1b3fb7cd5

- Update the code I changed in #3004 to instead of throwing an error instead mark oldTs as !Up so it gets removed, and later in the `processResponse` it will get re-added under the new Target.

I'm testing the first internally and looking into the second, while also entertaining other ideas.

Thoughts?

**Comment by bbeaudreault** [comment]
Here's an example where `loadtest5` was left with no serving replicas:

<img width="1589" alt="screen shot 2017-09-10 at 3 56 14 pm" src="https://user-images.githubusercontent.com/116591/30252433-aab4ff7c-9640-11e7-933b-a2be2ca0044d.png">

**Comment by bbeaudreault** [comment]
My first idea (https://github.com/HubSpot/vitess/commit/4e93004e5a22162d98c2c4eaa97848325b2fbfaf) significantly improved the situation. It's less real-time than the second idea, so to be totally insulated you need to space out your restarts (no more than 1 per `tablet_refresh_interval`). However, that same goes for typical tablet add/removes, so maybe that's fine for now.

I also need to add some synchronization between the Add and Remove, because Remove happens in a goroutine. Perhaps an Update is in order.

**Comment by sougou** [comment]
@bbeaudreault looks like this can be closed?
