### ISSUE TITLE
Add support to update column with secondary lookup vindex

### ISSUE THREAD

**Issue by rafael** [youtube/vitess#3177]
## Proposal / Motivation

This proposal is to support updating a column that is used as a secondary lookup vindex.

Currently Vitess does not support updates to any columns that have a [vindex](https://github.com/youtube/vitess/blob/master/doc/V3VindexDesign.md#updates-1).

Per the design document:

> *This is because such changes could effectively require us to migrate a row from one shard to another.*

We propose relaxing this restriction to support updating the implicitly created row used to implement the lookup vindex even though it may require moving the row to a different shard.

## Design

First, let's define some constraints on which kind of updates will be supported.

### Constraints

1.  It will only support updates to columns that are secondary vindexes, not the primary vindex. This will avoid the more complicated case of having to migrate both the vindex rows and the row with the actual content.
2. It will not support updating vindexes that are shared among different tables since this could leave orphan rows in those [tables](https://github.com/youtube/vitess/blob/master/doc/V3VindexDesign.md#the-vindex-owner). Because of this:
   1. You can't update columns with secondary vindexes that are not owned by the table being updated.
   2. You can't update columns with secondary vindexes that are shared by different tables.

### Strategy

Given a statement within the constraints exposed above, the following strategy is proposed:

1. Select for update the current vindex column value from the row being updated. In this way we can get the existent values for all the columns that might have vindexes. This is very similar to what is being done in the delete [plan](https://github.com/tinyspeck/vitess/blob/master/go/vt/vtgate/engine/route.go#L451).
2. Insert into a secondary owned vindexes the row with the updated column values.
3. Execute update statement to change the actual column.
4. Delete the old vindex entry.

Insert and delete are done in two steps because the vindex could be sharded and then the updated column value could land in a different shard.

This strategy should keep the same level of isolation existent before introducing this feature.

### Example

Given a table with the following schema and secondary vindex on name:

```
create table user(user_id bigint, name varchar(128), primary key(user_id));
```
and existent row:

| user_id 	| name 	|
|---------|------	|
| 1       	| jose 	|

For the following statement:
```
update user set name='rafael' where user_id=1
```

The plan should look similar to this:

```
select name from user where user_id = 1 for update
insert into name_user_idx(name, user_id) values ('rafael', 1)
update user set name = 'rafael' where user_id in (1)
delete from name_user_idx where (name = 'jose' and user_id = 1)
```

### Partial Failure

Similarly to existing insert for tables with a secondary vindex, these operations are done in a best-effort manner.

For example in the case that insert to the vindex succeeds, but then actual update of the row fails, it is possible to leave inconsistent data in the vindex lookup table. However, this will not yield incorrect results to the application.

**Comment by sougou** [comment]
This plan looks good. Some minor comments:

* On the Constraints implementation: you could add an `exclusive` flag to a vindex to indicate that it's not shared, and you can compute it at the time of loading vschema.
* Partial Failure: VTGate will rollback the entire transaction if it detects partial failure. So, there's no need to worry about this.
