### ISSUE TITLE
Please ensure `make` only builds binaries and does not run the test suite

### ISSUE THREAD

**Issue by sjmudd** [youtube/vitess#3193]
Hi,

In most build trees `make` is expected to build the binaries taking into account any dependencies whereas `make test` actually runs any tests of the code.

In Vitess this behaviour is not respected. It's not a big thing but if you want to build the code only you have to type `make build` rather than just `make`, and `make` builds the software but also runs the local test suite.

I would therefore suggest that for consistency with other software build processes the default make target `make` only _builds_ the source and `make test` runs the test suite.

If you want to provide a hint for people (this is good as I've been bitten by issues in the past with failed tests) to run the tests then after completing the build step adding a hint to do the build might be appropriate. I guess something along the lines of:

```
whatever_make_target_this_is:
     ...
     echo "Build completed successfully. Please ensure all tests work by running `make test` as failing to do so may lead you to spending more time diagnosing any issues."
```

**Comment by michael-berlin** [comment]
Good point. I've created https://github.com/youtube/vitess/pull/3199 to fix it.

I did not add a message to the "build" target though because "make test" is already mentioned in our docs.
