### ISSUE TITLE
Please add some extra warnings about proxy configuration

### ISSUE THREAD

**Issue by sjmudd** [youtube/vitess#3194]
I've been able to build Vitess without too many problems but when I ran the local tests they failed with some weird (to me) errors about not being able to reach some port. Basically the tests failed. I wasn't able to figure out why.

Later with some help from @sougou the issue boiled down to two things:
* to run `bootstrap.sh` I needed proxy access to the outside world as direct access is not permitted, so I set the appropriate proxy variables.
* To run the local test suite, to check the software was working, this proxy *MUST* be disabled as the proxy servers were remote to my build machine and so were obviously not able to reach 127.0.0.1:<some_port> used by Vitess and required to check the processes work properly.

It may be obvious in hindsight but having to switch proxy settings according to whether I'm `pulling git or dependencies`, `pushing to git`, building or doing `local tests` was not something that was obvious and there seem to be no checks that the proxy settings are appropriate. Having at least some warnings about this in the README / build instructions would be good as others may bump into this same issue.

**Comment by michael-berlin** [comment]
I didn't even know that we support using a proxy ;)

Which variables did you set to make this work?

Ideally, I would not like to bloat the documentation with a warning for such a special case. Maybe, we can detect this in the code instead and warn the user when they run tests?

**Comment by sjmudd** [comment]
Hi.  I do not have direct internet connectivity from any servers inside my office. I'm sure I could do all sorts of magic to "get out" but requiring the use of a proxy is typical I'm sure in many locations.

In my case, in order for `git pull` and some of the curl commands to work all I needed was to set the environment variables: `https_proxy` and `http_proxy`.  e.g. `export https_proxy=proxy.example.com:3128`, after which `bootstrap.sh` would work properly as would `git <whatever>`.

However, trying to run the local tests immediately after doing a `git pull; make build` would lead them to fail.  Logging does not show that (1) a proxy was being used.  It seems some of the python checks to see if the go processes are up and working use a python library which if these proxy environment variables are set will use them causing the issues described. The checks for things like vttablet being up fail when actually it's working fine.

So maybe when running the local tests any *proxy* variables should be reset/disabled etc such that they won't be used and things will work as expected.

**Comment by sougou** [comment]
What made this hard was the troubleshooting. It took a long time, up to the point of running an `strace` to figure out that things were going through a proxy. On the other hand, I can see a scenario where a proxy may be required for vitess to work.

So, a middle ground would be to warn about it at the beginning. That way, one can ignore it if it was intentional.

**Comment by sjmudd** [comment]
First figuring out exactly which environment variables affect Vitess' behaviour would be good and then I agree a log line indicating it is set would help. Hopefully the extra logging won't be considered useless noise.
