### ISSUE TITLE
Can authors provide some documents ? 

### ISSUE THREAD

**Issue by openinx** [youtube/vitess#32]
Hi  All: 
I recently try to play with vitess , but there are no documents basically .  we can just read the code .....   can authors write something to introduce more to us ? 

thank you very much .

**Comment by enisoc** [comment]
There's now a follow-up to the [Getting Started](https://github.com/youtube/vitess/blob/master/doc/GettingStarted.md) guide, which describes how to bring up a cluster, including scripts:

https://github.com/youtube/vitess/tree/master/examples/local
