### ISSUE TITLE
disable (and then fix) test_mysql_connector in travis

### ISSUE THREAD

**Issue by demmer** [youtube/vitess#3203]
Recently the `test_mysql_connector` test has been continuously failing in travis with failures like the following from https://travis-ci.org/youtube/vitess/jobs/277379836

```
-- 2017-09-19 16:29:46,091 utils:79 INFO ===== ======================================================================
-- 2017-09-19 16:29:46,091 utils:79 INFO ===== ERROR: test_mysql_connector (__main__.TestMySQL)
-- 2017-09-19 16:29:46,091 utils:79 INFO ===== ----------------------------------------------------------------------
-- 2017-09-19 16:29:46,091 utils:79 INFO ===== Traceback (most recent call last):
  File "test/mysql_server_test.py", line 153, in test_mysql_connector
    conn = MySQLdb.Connect(**params)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 187, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (2003, "Can't connect to MySQL server on '::' (101)")
```

@rafael attempted to fix this a few times but never managed to get something that worked.

My understanding is that this is on @michael-berlin's plate to address in the future changing of how the vitess tests run in travis.

In the meantime however, this is just causing annoyance as all the tests are failing.

As such I think it would best to disable that failing test for now, but keep this issue open to fix and re-enable the test once we get a real fix for it.

**Comment by michael-berlin** [comment]
I'll submit the change to temporarily disable the test.

**Comment by sougou** [comment]
Looks like this is fixed now.
