### ISSUE TITLE
Error reporting of rpc failures would be more useful if the destination address:port were reported and any proxy settings were visible

### ISSUE THREAD

**Issue by sjmudd** [youtube/vitess#3211]
I have an example where I was trying to run a command from vtctlclient. Examples are anonymised but I've kept enough info so you can see what's going on:

```
[user@host ~]$ vtctlclient -server :15999 TabletExternallyReparented dev-0000000100
E0920 09:00:04.707107   45371 main.go:62] Remote error: rpc error: code = Unavailable desc = grpc: the connection is unavailable
[user@host ~]$ vtctlclient -server :15999 ListAllTablets dev
dev-0000000100 dev -40 replica dev1mdb-01.example.com:15201 dev1mdb-01.example.com:3306 []
dev-0000000101 dev -40 replica dev1rdb-01.example.com:15202 dev1rdb-01.example.com:3306 []
dev-0000000200 dev 80-c0 replica dev2mdb-01.example.com:15401 dev2mdb-01.example.com:3306 []
dev-0000000201 dev 80-c0 replica dev2rdb-01.example.com:15402 dev2rdb-01.example.com:3306 []
dev-0000000300 dev 40-80 replica dev3mdb-01.example.com:15601 dev3mdb-01.example.com:3306 []
dev-0000000301 dev 40-80 replica dev3rdb-01.example.com:15602 dev3rdb-01.example.com:3306 []
dev-0000000400 dev c0- replica dev4mdb-01.example.com:15801 dev4mdb-01.example.com:3306 []
dev-0000000401 dev c0- replica dev4rdb-01.example.com:15802 dev4rdb-01.example.com:3306 []
11:00:28 [user@host ~]$ telnet dev1mdb-01.example.com 15201
Trying 1.2.3.4...
Connected to dev1mdb-01.example.com.
Escape character is '^]'.
^[^]

telnet> quit
Connection closed.
```

If you know the code and you understand the internal Vitess workflows then it may be clear what's going wrong here but for me it is not.
* I can see that connectivity to `vtctld` is working as the `ListAllTablets` command works
* I think that `vtctld`, which runs on the box I'm calling vtctlclient on, is trying to connect to `dev1mdb-01.example.com:15201` and I can at least see that I can connect to the telnet port. Yet the `TabletExternallyReparented` command fails.
* The given error does not clearly identify the source and destination of the grpc failure. It would be good to show this as it removes any ambiguity.
* After doing some checks I noticed that I had started `vtctld` (inadvertently) with a proxy setting in the environment. The go code is respecting this setting and trying to use it but the proxy it has configured is unable to reach the destination tablet.  Therefore making any proxy settings (and connections via a proxy) visible would be most helpful.
* Reason for proxy settings are linked to https://github.com/youtube/vitess/issues/3194

This is how I found the issue:

```
[user@host ~]$ cat /proc/20140/environ | tr '\0' '\n' | grep -i proxy
http_proxy=proxy.example.com:3128
https_proxy=proxy.example.com:3128
[user@host ~]$
```

**Comment by alainjobart** [comment]
One thing to mention here: the gRPC port is different than the main port on all of our processes, we listen to regular HTTP traffic on the main port (/debug/status pages, ...), but to a different port for gRPC. To find the port that is used, run a 'vtctl GetTablet  ...' and it will list the port. Maybe that port is unreachable...

Overall though, I agree, we need to fix the cryptic error message.

**Comment by sjmudd** [comment]
My understanding is that the environment in which Vitess currently works has been unencumbered by "proxies" so current code does not take them into account. Yet given the amount of time that I've wasted trying to debug Vitess not working due to this "misconfiguration" it strikes me that others could be affected the same way.  Hence both better error reporting and adding more relevant and appropriate information may help us identify these things more quickly.
