### ISSUE TITLE
Bump required Go version to 1.9

### ISSUE THREAD

**Issue by michael-berlin** [youtube/vitess#3219]
We discussed this internally today and agreed that we'll just do this.

I'll update everything shortly.

**Comment by guidoiaquinti** [comment]
Related to #2681

**Comment by michael-berlin** [comment]
I think this is done?

**Comment by michael-berlin** [comment]
Yes, it's done :)

PR: https://github.com/youtube/vitess/pull/3220

Website was updated as well: http://vitess.io/getting-started/local-instance/

I'm closing the issue.
