### ISSUE TITLE
Configurable maxrows of 10k

### ISSUE THREAD

**Issue by tirsen** [youtube/vitess#3224]
We need to temporarily increase the 10k limit on rows in result sets for some queries.

AFAICT this seems to be hardcoded currently.

It would be good to be able to:
* override this on a query by query basis and,
* be able to change that limit globally using a flag.

**Comment by tirsen** [comment]
Actually. It looks like globally there is already a flag?

`--queryserver-config-max-result-size` ?

**Comment by bbeaudreault** [comment]
That's correct. There's also a warn threshold you can set. At hubspot we set the warm threshold to 10k and limit to 100k so we can fix those queries as we migrate, rather than blow up

**Comment by sougou** [comment]
I guess I can close this issue :)
