### ISSUE TITLE
Drop PHP client.

### ISSUE THREAD

**Issue by michael-berlin** [youtube/vitess#3230]
Since we fully support the MySQL server protocol now, we plan to remove the PHP client from the code base.

The test for it is currently broken anyway. That's because we picked up regressions after we disabled it on Travis when the test no longer worked with gRPC 1.0.

Advantages of this decision:
* One thing less to maintain.
* Less build dependencies.
* Faster Docker image builds because PHP compiles the gRPC C library itself.

**Comment by sougou** [comment]
@rnavarro @jrossiter

**Comment by Rastusik** [comment]
finally! 👍 :)

**Comment by enisoc** [comment]
This makes me sad, but also happy.

**Comment by ronlobo** [comment]
PHP AF

**Comment by rnavarro** [comment]
I have seeded this notion internally and it's on everyone's radar. We're going to look at effort required to get this done so we can port over.

YAY
