### ISSUE TITLE
Documentation link problem http://vitess.io/user-guide/horizontal-sharding-workflow/

### ISSUE THREAD

**Issue by sjmudd** [youtube/vitess#3238]
I notice some links here http://vitess.io/user-guide/horizontal-sharding-workflow/ at the top of the page which give a 404. This probably needs fixing.

**Comment by michael-berlin** [comment]
Thanks for the report. I've fixed this now.

In general, note that the "workflow" in "Horizontal Resharding Workflow" stands for our workflow automation. You find this automation in the vtctld UI.

Therefore we have two tutorials, one for an automated resharding and one for a manual resharding:

automated: http://vitess.io/user-guide/horizontal-sharding-workflow/
manual: http://vitess.io/user-guide/horizontal-sharding/

As far as I understand, you're currently not using the automation and instead run SplitClone manually? In any case, the information on both pages should be correct.

**Comment by sjmudd** [comment]
Thanks for the clarification.

Yes, right now I'm doing this manually as I'm trying to reshard from a non-vitess source (using only RDONLY vttablets connected to a couple of slaves).  Understanding the manual workflow is good but having something that automates this when the system is up and running normally is obviously very attractive. I'll re-read both sections again.
