### ISSUE TITLE
Add shellcheck to our test suite

### ISSUE THREAD

**Issue by guidoiaquinti** [youtube/vitess#3292]
It could be nice to add [shellcheck](https://www.shellcheck.net/) to our test suite

**Comment by michael-berlin** [comment]
This would be yet another dependency in our bootstrap process ;)

They are also available through CodeClimate which we already have set up: https://github.com/youtube/vitess/blob/master/.codeclimate.yml

How about we only enable it there?

**Comment by michael-berlin** [comment]
Do you maybe want to take care of enabling it in our CodeClimate config?
