### ISSUE TITLE
Missing database name from template in SplitClone

### ISSUE THREAD

**Issue by sjmudd** [youtube/vitess#3308]
I see in logging when running a SplitClone I noticed a mistake due to a difference in configuration between the source and destination shards. (Source is running from a non-vitess setup and destination is trying to use a vitess compatible setup hence the differences).

```
E1016 13:58:02.621489    8630 main.go:62] Remote error: rpc error: code = Unknown desc = CopySchemaShard was not successful because the schemas between the two tablets cell:"cel
l1" uid:9999  and cell:"cell1" uid:100  differ: [source and dest don't agree on database creation command:
CREATE DATABASE /*!32312 IF NOT EXISTS*/ {{.DatabaseName}} /*!40100 DEFAULT CHARACTER SET utf8 */
 differs from:
CREATE DATABASE /*!32312 IF NOT EXISTS*/ {{.DatabaseName}} /*!40100 DEFAULT CHARACTER SET utf8mb4 */]
```

The incorrect definition and thus the warning was correct but the `{{.DatabaseName}}` was not being correctly filled in from some template setting.

Suggestions:
* fix the template to show the .Database name
* make it absolutely clear which alias refers to which command so probably add something like 
source: `cell1-00000009999` ... (show CREATE TABLE command) differs from destination: `cell1-0000000100` ... .(show CREATE TABLE command)

Not urgent but helps clarify the problem.

**Comment by sjmudd** [comment]
Related similar issue to https://github.com/youtube/vitess/issues/3307, though that's the result of a table diff.

**Comment by sougou** [comment]
I'm fixing the error message. However, the database name substitution looks intentional. It must be because the source and destination are allowed to have different names. So, I'll leave that part unchanged for now.
