### ISSUE TITLE
Confused by SplitClone logging

### ISSUE THREAD

**Issue by sjmudd** [youtube/vitess#3309]
I see `SplitClone` logging (run by hand to copy from a single shard 0 to 2 shards -80 and 80- the following):

```
I1016 14:36:49.712201   19694 command.go:162] Working on: keyspace/-80
State: cloning the data (online)
Running:
Copying from: cell1-0000000102 cell1-0000000202 cell1-0000002997 cell1-0000002998 cell1-0000002999
```
What confuses me is the fact it says **copying from** yet the source tablets are 2997, 2998 and 2999 and the destination tablets are 100, 101 and 102 for shard `-80` and 200, 201, 202 for shard `80-`.

A quick look at the code shows the following function is being used:

```
                result += "<b>Copying from:</b> " + scw.formatOnlineSources() + "</br>\n"
```

and `formatOnlineSources` uses `aliases := scw.tabletTracker.TabletsInUse()`

It may be that vitess is being smart and I don't understand this but I'd expect the copying to happen from: cells 2997..2999 only and if a destination is shown it would be the master (200 in this case).

So perhaps the functionality is fine. Making the logging clearer would be good and maybe that's either changing the wording of the logging or alternatively adjusting the tablet numbers being shown.

Actually functionality seems fine. So this is not about functionality, just making the logging easier for Vitess newbies.

**Comment by sougou** [comment]
While doing online clone, the worker needs to read from both source and destination to compare rows. The message is outdated. I'll send out a PR that changes it to: "Comparing source and destination using:".
