### ISSUE TITLE
flaky unit test: go/mysql/endtoend

### ISSUE THREAD

**Issue by michael-berlin** [youtube/vitess#3318]
Example: https://travis-ci.org/youtube/vitess/jobs/289290022

```
--- FAIL: TestKill (0.01s)
	main_test.go:55: was expecting SQLError 2013 / HY000 / EOF but got message io.ReadFull(header size) failed: read unix @->/vt/vtdataroot/vttest874417268/vt_0000000001/mysql.sock: read: connection reset by peer
FAIL
FAIL	github.com/youtube/vitess/go/mysql/endtoend	5.992s
```

Is this related to the recent change in the local cluster thing?

**Comment by alainjobart** [comment]
Looking at the code, this can only happen if io.ReadFull() on the unix socket doesn't return EOF when the other side closes the connection, but something else. note we get the right error code, but the error message doesn't contain 'EOF' (it's not an io.EOF), instead is:

io.ReadFull(header size) failed: read unix @->/vt/vtdataroot/vttest874417268/vt_0000000001/mysql.sock: read: connection reset by peer

I don't see how that would be flaky though, I'd feel it should always work or always fail...

**Comment by sougou** [comment]
Additional data point: this started happening after the new vttest.

**Comment by alainjobart** [comment]
I honestly have no idea. Sugu, I'll show you what I think when you get in, and we can agree on a solution.

Note this is not a critical issue at all, the error codes are 100% correct, it's just the message we get is not what we expect, but it's still correct.

**Comment by alainjobart** [comment]
Fixed in https://github.com/youtube/vitess/pull/3322
