### ISSUE TITLE
support more than one uniqueness column on a secondary vindex

### ISSUE THREAD

**Issue by demmer** [youtube/vitess#3376]
Currently an owned lookup vindex can contain only two columns -- the `From` and `To` in order to map the secondary sharding column value to the primary sharding column.

However, this only works properly when the combination of columns is unique. As a simple motivating example, assume a data model corresponding to a news site with users, articles, and comments:

```
create table user(
    user_id bigint,
    name varchar(128),
    primary key(user_id)
);

create table article(
    article_id bigint,
    timestamp bigint,
    content text,
    primary key(article_id)
);

create table comment(
    article_id bigint,
    user_id bigint,
    timestamp bigint,
    message varchar(1024),
    primary key(article_id, user_id, timestamp)
);
```

Note that the comment table doesn't have its own unique id column -- the data model enforces that there can't be more than one user comment on a article for a given timestamp but the user could comment more than once on an article.

The sharding definitions for this example are:
  * `user`: sharded by `hash(user_id)`
  * `article`/`comment`: sharded by `hash(article_id)`

This sharding scheme would enable efficient lookup of an article and all associated comments by given article ID.  However in order to efficiently get all comments by a given user on a given article, we would ideally want to add a secondary owned lookup vindex on the comment table.

The problem is that a given comment is uniquely identified by `(article_id, user_id, timestamp)`. So the secondary lookup vindex needs to be defined as such:

```
create table comment_user_idx(
    article_id bigint,
    user_id bigint,
    timestamp bigint,
    primary key(article_id, user_id, timestamp)
);
```

This table would then be sharded by `hash(user_id)` enabling efficient lookup of all comments by a given user.

In order to solve this, the vindex API for lookup tables would be extended to support more than two columns for Create and Delete, so that the secondary index rows could still be accurately "owned" by their corresponding primary table row.

As a final note, this feature would also enable vitess to transparently maintain a table sharded by two (or more) sharding columns. If a configuration included all columns from the original table in the vindex table definition, then the vindex management code would effectively maintain two copies of the same data, just sharded by a different key.

**Comment by rafael** [comment]
This will be addressed by: https://github.com/youtube/vitess/issues/3481
