### ISSUE TITLE
DeleteKeyspace leaves a Lock file in the topo

### ISSUE THREAD

**Issue by demmer** [youtube/vitess#3377]
When cleaning up a keyspace, we noticed that sometimes the `DeleteKeyspace` vtctl command doesn't end up removing it from the list.

Looking into this, I noticed that deleting the keyspace deleted the file `<global>/keyspaces/<keyspace>/Keyspace` but did not delete the file `<global>/keyspaces/<keyspace>/Lock`, which meant that the containing path `<global>/keyspaces/<keyspace>` was still around.

**Comment by alainjobart** [comment]
This is a bug with the Consul topo implementation, the Lock file is not removed after the Lock is released. It should be, in a transaction. Will look into it.

**Comment by alainjobart** [comment]
Should be fixed.
