### ISSUE TITLE
Vitess on docker compoose

### ISSUE THREAD

**Issue by cpapidas** [youtube/vitess#3384]
Is docker compose supported by vitess ?
Where can I find some example about it (a docker-compose.yml file) ?

**Comment by arthurnn** [comment]
@vmg and I worked in a docker-compose file for vitess, in our local setup. I can share that, maybe push to the repo?
@sougou thoughts?

Curiosity, are you going to use docker-compose for your local dev? or tests?
Do you know about vtcombo?

**Comment by cpapidas** [comment]
yes please I really need it.

**Comment by sougou** [comment]
That will be a good idea. Ideally, it should be under `examples`, and it should recreate what `kubernetes` has.

**Comment by hmcgonig** [comment]
This would be phenomenal for local testing.

**Comment by arthurnn** [comment]
Ok, I will create a PR with what I have.

BTW, for test/CI, we use `vtcombo` which is a single binary that can start MySQL, vttablet and vtgate with a fake in memory topology.
That works amazingly well for our CI env.
