### ISSUE TITLE
If port is already in use then vitess should cleanly exit

### ISSUE THREAD

**Issue by sjmudd** [youtube/vitess#3391]
Right now it doesn't. I inadvertently started the same vtworker twice and see this backtrace as a result.

```
Starting vtworker...
I1116 15:24:52.346912   63862 interactive.go:140] Interactive mode ready
I1116 15:24:52.347407   63862 grpc_server.go:114] Setting grpc max message size to 4194304
I1116 15:24:52.347483   63862 service_map.go:65] Registering vtworker for grpc, disable it with -grpc-vtworker service_map parameter
I1116 15:24:52.347514   63862 service_map.go:68] Not registering throttler for grpc, enable it with grpc-throttler service_map parameter
I1116 15:24:52.347597   63862 grpc_server.go:138] Listening for gRPC calls on port 15033
F1116 15:24:52.347734   63862 grpc_server.go:141] Cannot listen on port 15033 for gRPC: listen tcp :15033: bind: address already in use
goroutine 1 [running]:
github.com/youtube/vitess/vendor/github.com/golang/glog.stacks(0xc4202f7100, 0xc4202fc000, 0x88, 0x96)
        /home/user/dev/src/github.com/youtube/vitess/vendor/github.com/golang/glog/glog.go:769 +0xcf
github.com/youtube/vitess/vendor/github.com/golang/glog.(*loggingT).output(0x122e8c0, 0xc400000003, 0xc4202fa000, 0x108419e, 0xe, 0x8d, 0x0)
        /home/user/dev/src/github.com/youtube/vitess/vendor/github.com/golang/glog/glog.go:720 +0x345
github.com/youtube/vitess/vendor/github.com/golang/glog.(*loggingT).printf(0x122e8c0, 0xc400000003, 0xc6c648, 0x25, 0xc4201e3d88, 0x2, 0x2)
        /home/user/dev/src/github.com/youtube/vitess/vendor/github.com/golang/glog/glog.go:655 +0x14c
github.com/youtube/vitess/vendor/github.com/golang/glog.Fatalf(0xc6c648, 0x25, 0xc4201e3d88, 0x2, 0x2)
        /home/user/dev/src/github.com/youtube/vitess/vendor/github.com/golang/glog/glog.go:1148 +0x67
github.com/youtube/vitess/go/vt/servenv.serveGRPC()
        /home/user/dev/src/github.com/youtube/vitess/go/vt/servenv/grpc_server.go:141 +0x263
github.com/youtube/vitess/go/vt/servenv.Run(0x3ab8)
        /home/user/dev/src/github.com/youtube/vitess/go/vt/servenv/run.go:40 +0x4e
github.com/youtube/vitess/go/vt/servenv.RunDefault()
        /home/user/dev/src/github.com/youtube/vitess/go/vt/servenv/servenv.go:194 +0x30
main.main()
        /home/user/dev/src/github.com/youtube/vitess/go/cmd/vtworker/vtworker.go:108 +0x189
```

Clearly this is my fault but I would expect after recognising that the port is in use that the process exits cleanly.  Not urgent but it would be nicer to see it terminate.

**Comment by alainjobart** [comment]
This is a regular log.Fatal, that we use at startup when we can't start cleanly:
F1116 15:24:52.347734   63862 grpc_server.go:141] Cannot listen on port 15033 for gRPC: listen tcp :15033: bind: address already in use

It then displays a stack trace for debugging purposes, and should exit with a non-zero error code.

Is that not happening? Sorry, it's not clear what else you were expecting?

**Comment by sjmudd** [comment]
oh. I see. I was expecting A clean error message like:

`Cannot listen on port 15033 for gRPC: listen tcp :15033: bind: address already in use, exiting`

I can see why in some cases you might want to see a stack trace but for this specific issue it's almost certainly not process's fault that it can't bind as something else is there already. So the stack trace doesn't seem to make much sense (to me).

It's an error but probably a human / scripting error which the process can't be expected to handle.

**Comment by sjmudd** [comment]
I guess this would be a logical separation of "oh dear this has happened and I'm the one to blame", vs "oh dear this has happened and it can't possibly be my fault".

**Comment by sjmudd** [comment]
So a non-0 exit status seems good. I'm just not sure in this case of the utility of the stack strace.
