### ISSUE TITLE
can it support running out with sort and pagination by mysql sharding ?

### ISSUE THREAD

**Issue by ShuraChow** [youtube/vitess#347]
thanks for this code first!
i have a doubt about this code, can it support to running out a list with sort and pagination by mysql sharding ?

**Comment by sougou** [comment]
Yes, as long as the query targets a single keyspace id (shard). You can run queries like 'select * from t where <condition> order by x limit :v1, :v2.
You'll still need the correct indexes on the table to make sure the query will be run efficiently by MySQL.

**Comment by ShuraChow** [comment]
>>>>the query targets a single keyspace id (shard)
I'm sorry, maybe I don't express clearly
i means cross sharding nodes. table 't' was sharded  into different node by primary key,  
then, i want to get a list with sort and pagination from the two nodes....

**Comment by sougou** [comment]
It may be more clear if you give an example. Let's say you have table t sharded by key k, where key values 0-0x80 are in shard 0, and values 0x80-0xff are in shard 1. What would your query look like?

In my example, if you ran a 'select * from t where k=:v1 order by x limit :l1, :l2', then all rows for this query will either be in shard 0, or shard 1, but not both. So, pagination will work.

If the results of your query are going to be on both shards, that is if the where clause does not contain the sharding key, then you can get two sets of results that you'll have to merge on the application side. We plan to eventually support cross-shard aggregations, order by & limit constructs. But we don't support it right now.

**Comment by ShuraChow** [comment]
thx for your comment.

    If the results of your query are going to be on both shards, that is if the where clause does not contain the sharding key, then you can get two sets of results that you'll have to merge on the application side. We plan to eventually support cross-shard aggregations, order by & limit constructs. But we don't support it right now.

this is that i want. ^_^
i was thought about it such as merge data on application side, but i always feel that should be done on driver side, application just do application stuff, not about processing data for query and merge, and the efficiency must be lower than database, in particular when a large amount of data be query.

whatever , maybe it have sth compromise way.
i'm looking forward your repository for cross-shard aggregations

by the way , do i need to close this issue?

**Comment by sougou** [comment]
VTGate was built to do this kind of processing. We just haven't gotten around to implementing it yet. It will happen eventually :).
