### ISSUE TITLE
Vitess and mariadb

### ISSUE THREAD

**Issue by pjebs** [youtube/vitess#3526]
Is Vitess safe to use with mariadb?

**Comment by derekperkins** [comment]
Yes, though I'm not sure to what version. There is a default `my.cnf` for mariadb.
https://github.com/youtube/vitess/blob/master/config/mycnf/master_mariadb.cnf

**Comment by sougou** [comment]
YouTube runs on 10.0.X, with some internal patches (that are not relevant to vitess).
But newer versions of MariaDB should also work.

**Comment by pjebs** [comment]
I thought youtube used mysql internally. Not mariadb.

**Comment by enisoc** [comment]
@pjebs I would trust @sougou to know. He works there. ;)

**Comment by sougou** [comment]
Yes :).
