### ISSUE TITLE
vtgate should only start up if it manages to read from the Topology service

### ISSUE THREAD

**Issue by mpawliszyn** [youtube/vitess#3549]
Swallowing the topology service error leads to new un-configured vtgates that take traffic and throw keyspace not found exceptions.

https://github.com/youtube/vitess/blob/ca2a7f1d9810411e875407746a67de05a3c483f6/go/vt/vtgate/vtgate.go#L158

**Comment by alainjobart** [comment]
The merged PR should address this.
