### ISSUE TITLE
regression: vtgate hangs if started before DDL + vschema

### ISSUE THREAD

**Issue by derekperkins** [youtube/vitess#3567]
From @tirsen 
> We bumped to latest Vitess master SHA and we’re seeing this error in our test suite:

```
unsharded keyspace %s has multiple shards: possible cause: sharded keyspace is marked as unsharded in vschema
```

Workaround:
> If we move the start of the vtgate to AFTER deploying the DDL and vschema then it works

This works ok for the standard examples, which go through a specific startup order. For helm charts however, there is no ordering guarantee on startup, so this will prevent any Kubernetes installs from working out of the gate.

**Comment by sougou** [comment]
Looks like this is fixed now.
