### ISSUE TITLE
bootstrap.sh should fail fast if go is not installed

### ISSUE THREAD

**Issue by rushiagr** [youtube/vitess#360]
Even if go is not installed (or is not on the $PATH, which is more likelier), the script goes on and executes completely. Two solutions: 1. Check if go is present, and fail if not. 2. Pass -e flag to the bash script (set -e), which will make the script fail as soon as first error is encountered (but we might not want this)

**Comment by enisoc** [comment]
We should probably run with 'set -e' but we'd need to clean up bootstrap.sh and dev.env first. I think there are places where we're ok with things failing, so we'd need to fix those so they don't derail everything.

**Comment by rushiagr** [comment]
Yes, that's the problem with using 'set -e'. I have submitted a pull request https://github.com/youtube/vitess/pull/361 which fails if go is not present
