### ISSUE TITLE
Change username/password

### ISSUE THREAD

**Issue by snthibaud** [youtube/vitess#3603]
I am trying out Vitess on Kubernetes and have successfully set up a cluster, but now I want to access it from outside. I took a look at the guestbook example and discovered that is connects without password from within the cluster. The cluster also seems to have a MySQL port exposed (port 3306). I would like to connect over that port and I assume I should use the 'vt_app' user to connect, but I think I somehow have to change the password (it does not work without password and if it would, the whole world would be able to access it).
How should I change this password so that I can access the database from the outside?

**Comment by derekperkins** [comment]
@snthibaud I'm not sure how you installed Vitess. We're currently upgrading the [Vitess helm chart](https://github.com/youtube/vitess/tree/master/helm/vitess), and it has instructions for enabling MySQL authentication.

If you want to set it up manually, here are the appropriate flags and file structure.

### vtgate flags
```
-mysql_server_port=3306
-mysql_auth_server_static_file="/mysqlcreds/creds.json"
-mysql_server_socket_path $mysql_server_socket_path # optional
```

### mysql_auth_server_static_file format
the `myusername` needs to be repeated as shown
```
{
  "myusername": [
    {
      "UserData": "myusername",
      "Password": "somepassword"
    }
  ],
  "vt_appdebug": []
}
```

**Comment by snthibaud** [comment]
@derekperkins Thank you! I have been trying the Helm approach, but got stuck on the error `Error: apiVersion "autoscaling/v2beta1" in vitess/templates/vitess.yaml is not available`. Any idea?

**Comment by derekperkins** [comment]
Ok, that api went from `autoscaling/v2alpha1` to `autoscaling/v2beta1` in 1.8, so I'm guessing that you're running 1.7? Try adding a new `maxReplicas` line into your topology and have it match the `vtgate` number, then the chart won't add an HPA.

```
topology:
  cells:
    - name: "zone1"
      etcd:
        replicas: 3
      vtctld:
        replicas: 1
      vtgate:
        replicas: 3
        maxReplicas: 3
```

**Comment by snthibaud** [comment]
I created a 7-instance cluster, installed etcd-operator and set maxReplicas to 3 as you suggested and the helm installation seems to finish, but the vtgate doesn't come up. The logs show this:
```

vtgate | 2018-01-30T02:29:46.727208674Z | F0130 02:29:46.722902 1 vtgate.go:158] gateway.WaitForTablets failed: node doesn't exist
-- | -- | --
vtgate | 2018-01-30T02:29:46.727190759Z | E0130 02:29:46.722794 1 resilient_server.go:198] GetSrvKeyspaceNames(context.Background.WithDeadline(2018-01-30 02:30:16.72025092 +0000 UTC m=+30.022198954 [29.997449941s]), zone1) failed: node doesn't exist (no cached value, caching and returning error)
vtgate | 2018-01-30T02:29:46.722401974Z | E0130 02:29:46.722293 1 topology_watcher.go:157] cannot get tablets for cell: zone1: node doesn't exist
vtgate | 2018-01-30T02:29:46.720234318Z | I0130 02:29:46.720184 1 gateway.go:90] Gateway waiting for serving tablets...
vtgate | 2018-01-30T02:29:46.720136669Z | I0130 02:29:46.720086 1 discoverygateway.go:104] loading tablets for cells: zone1
vtgate | 2018-01-30T02:29:46.719913560Z | I0130 02:29:46.719782 1 buffer.go:144] vtgate buffer not enabled.
vtgate | 2018-01-30T02:29:46.701470038Z | ERROR: logging before flag.Parse: E0130 02:29:46.701246 1 syslogger.go:122] can't connect to syslog
vtgate | 2018-01-30T02:29:46.696788870Z | ++ exec /vt/bin/vtgate -topo_implementation=etcd2 -topo_global_server_address=etcd-global-client.default:2379 -topo_global_root=/vitess/global -logtostderr=true -stderrthreshold=0 -port=15001 -grpc_port=15991 -service_map=grpc-vtgateservice -cells_to_watch=zone1 -tablet_types_to_wait=MASTER,REPLICA -gateway_implementation=discoverygateway -cell=zone1
vtgate | 2018-01-30T02:29:46.695275407Z | + eval exec /vt/bin/vtgate -topo_implementation=etcd2 '-topo_global_server_address="etcd-global-client.default:2379"' -topo_global_root=/vitess/global -logtostderr=true -stderrthreshold=0 -port=15001 -grpc_port=15991 '-service_map="grpc-vtgateservice"' '-cells_to_watch="zone1"' '-tablet_types_to_wait="MASTER,REPLICA"' '-gateway_implementation="discoverygateway"' '-cell="zone1"'
```
Is there any other configuration I should have done?

**Comment by derekperkins** [comment]
@snthibaud That `node doesn't exist` error should eventually resolve itself once the vttablets spin up. Did this not ever succeed? It usually takes about 5-10 minutes to complete on my cluster. Also, if you want to paste your `site-values.yaml` here, I can take a look at it.

**Comment by derekperkins** [comment]
Ok, I see your problem now. The base `values.yaml` file is there for default options, but it can't describe everything, since we don't know what your schema looks like. Helm then uses a `site-values.yaml` that you provide and merges that config with these defaults to describe the final chart. https://docs.helm.sh/helm/#helm-install

You'll want to take something like the following data and create a new `site-values.yaml` file. Then you'll run:
```
helm install /path/to/github.com/youtube/vitess/helm/vitess/ -f /path/to/site-values.yaml --name=vitess --namespace vitess
```

### site-values.yaml
```
topology:
  cells:
    - name: "zone1"
      etcd:
        replicas: 3
      vtctld:
        replicas: 1
      vtgate:
        replicas: 3
        maxReplicas: 3
      keyspaces:
        - name: "unsharded-dbname"
          shards:
            - name: "0"
              tablets:
                - type: "replica"
                  vttablet:
                    replicas: 2
```

**Comment by snthibaud** [comment]
Thank you. I succesfully created a cluster with shards. Both shards showed `replication_reporter: no slave status`, however. Should one of these shards become the shard master? I tried to choose one with `./kvtctl.sh InitShardMaster -force sharded-db/-80 zone1-1104301100`、but it seems to hang on that command. I executed it on both shards and had to kill it with ctrl-c, because it did not finish. They both show as master now, but with health error `Unknown database 'vt_sharded-db' (errno 1049)`. I feel like there should probably be only one master.

**Comment by derekperkins** [comment]
You can try it via the UI (there are actually two separate UIs, each with different functionality). After your helm install completes, it will show you a url that looks similar to this that you'll be able to reach via `kubectl proxy`.

http://localhost:8001/api/v1/proxy/namespaces/vitess/services/vtctld:web/app/
http://localhost:8001/api/v1/proxy/namespaces/vitess/services/vtctld:web/app2/

### app2 is the one you'll want to use first, and it will looks something like this
![image](https://user-images.githubusercontent.com/3588778/35574455-1d244e12-0597-11e8-95ec-6b3c62b583e4.png)

### Click into the shard and you'll see a table like this (except both will be replicas)
![image](https://user-images.githubusercontent.com/3588778/35574524-3cdcc6f8-0597-11e8-882a-218aaa52a7bc.png)

### Choose `Initialize Shard Master` from the dropdown menu at the top
![image](https://user-images.githubusercontent.com/3588778/35574575-5d9aedb6-0597-11e8-9a24-08fbc25ad44d.png)

### Finally pick one of the tablets (doesn't matter which one) and click the Force checkbox
![image](https://user-images.githubusercontent.com/3588778/35574668-aae6af10-0597-11e8-9ef7-c548ed19f9c8.png)

**Comment by snthibaud** [comment]
@derekperkins Thanks. If I do that, the UI keeps hanging on the window below:
![Uploading Screen Shot 2018-01-31 at 9.42.47.png…]()
Another question: if I want to distribute the data over both shards without any duplication of the data, should I make both shards (80- and -80) the master, right?

**Comment by derekperkins** [comment]
Your screenshot didn't upload, so I can't see it. I'm guessing it's just the spinner?

Yes, each shard runs as a separate "cluster", so you'll need a master per shard.

**Comment by snthibaud** [comment]
Yes, just a spinner indeed

**Comment by snthibaud** [comment]
It says 'Loading response...'

**Comment by derekperkins** [comment]
Have you tried deleting the entire Vitess install, including the PVCs, and reinstalling the helm chart?

`helm del --purge vitess`

**Comment by snthibaud** [comment]
Yes, I deleted the entire cluster just before I tried the suggestion to shard in the GUI.
Then I installed etcd-operator, did 'helm init' and installed the chart.

**Comment by derekperkins** [comment]
What do your logs from `vtctld` and `vttablet` say?

**Comment by derekperkins** [comment]
BTW, I just invited you to the Vitess Slack group. It might be easier to debug in a chat context

**Comment by snthibaud** [comment]
Thank you!

**Comment by sougou** [comment]
Looks like this thread continued on Slack.
