### ISSUE TITLE
Website Docs showing 'Redirecting page'

### ISSUE THREAD

**Issue by polynomial** [youtube/vitess#3685]
Going to: http://vitess.io/ and clicking on 'Manual Build': http://vitess.io/getting-started/local-instance
Goes to a page that just says: 'Redirecting…
Click here if you are not redirected.'

Yet clicking there just gets redirected back to that page. Going to: http://vitess.io/getting-started/local-instance/index.html manually appears to get the page I want.

**Comment by thatsk** [comment]
even all page are showing redirecting page

**Comment by sougou** [comment]
I guess that means our DNS change went through :).
@derekperkins Can you take a look?

**Comment by lukmanulhakimd** [comment]
same here

**Comment by daemonfire300** [comment]
In the hope that it does not cluster this issue, but I have the same issue. Example: http://vitess.io/getting-started/local-instance

**Comment by derekperkins** [comment]
It's weird, I'm only seeing that happen for some of the links. Of the three main buttons on the homepage, only the middle of the three buttons is entering a redirect loop. Is that the same thing you are experiencing?

**Comment by polynomial** [comment]
Yeah, however subsequent hits seem to be broken for things too. Like the user guide.  😥

**Comment by sougou** [comment]
@g10 and I did some digging yesterday. Most likely, the culprits are the `redirect_from` lines like in this file: https://raw.githubusercontent.com/youtube/vitess/master/vitess.io/overview/scaling-mysql.md.

**Comment by derekperkins** [comment]
I don't have time to do it today, but you could try just deleting all of those lines. Netlify will generate a full site preview in the PR, and you could see if that fixes it.
