### ISSUE TITLE
too many branches

### ISSUE THREAD

**Issue by yaoshengzhe** [youtube/vitess#391]
There are too many branches in vitess repo and most of them are development branches, not release ones. Maybe we can utilize github pull request model better by forking vitess repo and leave these working branch there. In that way, vitess repo only contains necessary branches: master, releases or major feature branches.

**Comment by mitiger** [comment]
hi，你是中国人吧，我们中文交流OK不？主要是我的英文太差了。

关于vitess，我有几个问题不太明白。
(1) 关于备份这块， 在同一个shard =0里面，我创建了两个vttablet的实例，然后选举其中一个为master ，然后他们的数据是同步的，但是当我加了一个新的vttablet的实例进来的时候，就会出现问题了。首先是新加的这个vttablet不会自动同步master中的表结构， 其次当我手动把表结构写到vttablet中的时候，只能同步之后master的数据。但是master中旧的数据却不会同步过来，这个地方不太明白要怎么弄？

(2) 就是关于分片， 这个完全是不太明白，看文档也没有搞明白。 我创建一个新的shard =1，里面创建了两个vttablet的实例，选举其中一个为master， 但是分片功能还是没有成功，这个地方能不能给个稍微详细点的说明。

谢谢

**Comment by enisoc** [comment]
What kinds of problems come about because of the number of branches? I haven't encountered any myself.

**Comment by yaoshengzhe** [comment]
@enisoc number of branches is totally not a problem for git. I am just thinking if we could come up more meaningful branch strategy, just don't start one's temp work by creating a branch in the main repo. The main repo better to have master branch, stable releases and major feature branches only. That is the way I've observed for many other open source projects, like kafka (https://github.com/apache/kafka), spark (https://github.com/apache/spark), hadoop (https://github.com/apache/hadoop), etc. In that way, people could figure out which is the right one for them and have a clear picture of the status of the system. My two cents.

**Comment by yaoshengzhe** [comment]
@mitiger Anthony has addressed your issues in another tracking issue https://github.com/youtube/vitess/issues/399. I can help to explain to you things I know and if you prefer to talk, you can add my wechat: ipodfans

**Comment by rushiagr** [comment]
I second this issue. It felt weird to me that there were quite a few development branches. It just confused me. As we don't have enough docs, it was hard to understand the development model (are new features going directly into the master, or in a separate branch till they're stabilized, and if latter, which is the correct branch)...

**Comment by aaijazi** [comment]
Agree that we should have more clear docs on the development model. Would that be enough to resolve this issue?

I'd vote against adding release/feature branches since it'll be more process, and not enough gains yet.
