### ISSUE TITLE
Need docs on creating sharded setup

### ISSUE THREAD

**Issue by mitiger** [youtube/vitess#399]
hi , 
here i hava some questions about how to use with vitess ,
(1) . first i hava create  a shard =0 ,  and in this shard, i create two vttablet instance, then use command "./vtctl ReparentShard"  to electing a master ,everything is ok. but when i when to add a new vttablet into this shard=0 , question appeared。  if i do not create table in the new vttablet , it will no get some data from master . when i create table, it will get new data when master update, but  can not get old master data. so i don't know how to do in this place?

(2) . second ,i don't kown hao to use shard. can you give me a stronger document in hao to use shard?

**Comment by enisoc** [comment]
For your question (1), I have created a tracking issue here: https://github.com/youtube/vitess/issues/403

I am making this a tracking issue for (2). We haven't written documentation for sharded setups yet, but there is some discussion beginning on the mailing list: https://groups.google.com/forum/#!topic/vitess/EcUB0mIrLN4

We'll post on this issue with updates on docs for sharded setup.

**Comment by mitiger** [comment]
hello, I am very worried about shard .
can you give me a simple document or an example with shell for how to use shard.
thanks a lot.

**Comment by aaijazi** [comment]
Closing this as a duplicate, in favor of #441
