### ISSUE TITLE
Need docs on how to add a new vttablet to an existing shard

### ISSUE THREAD

**Issue by lihezh** [youtube/vitess#403]
first I have a live shard in a cell and two vttablets/databases instance in the shard, I create a table in the master database of the shard and insert data into the database through the mysql client(not vtgate), the other database of the shard could auto sync data from master database.Then I add a new vttablet and daabase instance into the shard,but I found that the new database didn't auto sync data from master database of the shard finally, the  new database is empty.
Thanks very much!

**Comment by enisoc** [comment]
We've had a couple questions about this, so I'm making this into a tracking issue to consolidate.

To add a new tablet to an existing shard, you need to do one of two things:

1) Use the `vtctlclient Clone` command to copy the data from an existing tablet that has it. Note that this will take the source tablet out of serving state during the copy.

2) Take a backup from an existing tablet with `vtctlclient Snapshot` and use a hook script to copy it to external storage somewhere. Then use `vtctlclient Restore` on the new tablet with a hook script that copies it back from external storage. The advantage of this over `Clone` is that you can make a single backup and then restore it to any number of tablets without taking existing tablets out of serving during the restore.

We're still working on writing documentation for these processes, and we'll update this issue when we have something. In the meantime, if you want to try to forge ahead of our docs, you can look at how it's done in the integration test script:

1) For `Clone`: https://github.com/youtube/vitess/blob/master/test/clone.py#L234
2) For `Snapshot`/`Restore`: https://github.com/youtube/vitess/blob/master/test/clone.py#L150

If you have any followup questions along the way, we'd be happy to help as it will be useful for the documentation effort.

**Comment by lihezh** [comment]
Thanks! I will look at the test scripts and hope to do something helpful. I think that is useful to make the process as simple as possible.

**Comment by mitiger** [comment]
I see the clone.py and try it, but with a problem , it need wo tablet alias type for idle, but i do not know hao to create a tablet which type is idle?

**Comment by alainjobart** [comment]
We just reworked our backup / restore to be a lot more straightforward and much simpler. Now the backups are handled with the 'vtctl Backup' command, and the restore is a vttablet startup option. See doc/BackupAndRestore.md for more details.

At this point, we are just in need of an implementation of BackupStorage on different Cloud services (we already provide the local file system one, that would work over NFS, or any file system that can be mounted on the local machine).

So I'm going to close this issue, let us know if something still needs attention. Thanks!
