### ISSUE TITLE
Problems about Authentication and Security

### ISSUE THREAD

**Issue by Juckey** [youtube/vitess#459]
Does client code need user and password to access vtgate?If not, then any code can access vtgate without any authentication,i.e. client code can access databases behind vttablets directly, then perhaps security problems occur.

**Comment by sougou** [comment]
@alainjobart can comment more on this.
We already support SASL authentication for the current RPC framework we're using. However, we're also looking at transitioning to [grpc](http://grpc.io), which has [authentication built into its design](https://github.com/grpc/grpc-common/blob/master/grpc-auth-support.md) as well as many other cool features.
