### ISSUE TITLE
PostgreSQL support?

### ISSUE THREAD

**Issue by kidoman** [youtube/vitess#479]
Hello guys,

Thanks for the work on this. But are they any plans of supporting PostgreSQL? Would it even be possible. Sorry if I have missed any prior discussions on this front.

Regards,
Karan Misra

**Comment by sougou** [comment]
Hi kidoman,
For now, Postgres is not on our roadmap. We may revisit this based on how the industry evolves. But we're currently focused on MySQL and their upcoming versions.

**Comment by lobosan** [comment]
Any updates on this?

**Comment by derekperkins** [comment]
@lobosan Still no work is being done on Postgres compatibility, though it is technically possible. I wouldn't hold your breath. :)

**Comment by sougou** [comment]
Interest in Postgres has been rising. It's possible we may add this to the roadmap depending on how much eng bandwidth we build and other priorities.

**Comment by yudiandreanp** [comment]
+1

**Comment by nilsocket** [comment]
Any plans to support PostgreSQL?

Thank You.

**Comment by dereknex** [comment]
A similar product but support postgreSQL. https://github.com/citusdata/citus

**Comment by irfn** [comment]
@sougou Since you mentioned the possibility of doing this, Lets say If anyone were to think about contributing on this, do you think Vitess can architecturally add postgres as a "backend". Is VTablet and VtGate and other components coupled with mysql implementation?

**Comment by sougou** [comment]
There's currently code in various places that deal with Statement Based Replication of mysql, which will be a hindrance. I plan to delete that code as my next project.

Once that is done, vitess will be more db agnostic. After that, the work will mostly be related to vttablets. Impact on other parts will be relatively less.

Rough estimate is likely to be 1-2 person-years of work.

**Comment by nusairat** [comment]
Curious if any work has gone on this route?

**Comment by deepthi** [comment]
> Curious if any work has gone on this route?

Not so far. See #7084
