### ISSUE TITLE
The Dockerfile can split two stage

### ISSUE THREAD

**Issue by netroby** [youtube/vitess#492]
The Dockerfile build need so much times to download and install requirements packages.
So i suggest it can be split two part.

# Create a container images include all packages need by build vitess

```
FROM golang:1.4-wheezy

# Install Vitess build dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    automake \
    bison \
    bzip2 \
    curl \
    g++ \
    git \
    libssl-dev \
    libtool \
    make \
    memcached \
    mercurial \
    openjdk-7-jre-headless \
    pkg-config \
    python-dev \
    python-mysqldb \
    python-software-properties \
    python-pip \
    python-virtualenv \
    unzip \
    && rm -rf /var/lib/apt/lists/*

# Install MariaDB 10.0.x
RUN apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 0xcbcb082a1bb943db && \
    add-apt-repository 'deb http://sfo1.mirrors.digitalocean.com/mariadb/repo/10.0/debian wheezy main' && \
    apt-get update && apt-get install -y mariadb-server libmariadbclient-dev
CMD ["bash"]
```

**Comment by enisoc** [comment]
This sounds like a good idea to me. The hardest part is going to be figuring out what name to use as the image tag, since I already used vitess/base for the one that actually builds vitess...

**Comment by netroby** [comment]
Named things just simple. 

what about ```vitess/core ```

**Comment by alainjobart** [comment]
Should we also add grpc in this base?

**Comment by enisoc** [comment]
Including grpc in the new base image (I'm thinking of calling it vitess/env) would be ideal. It'll require copying the install_grpc.sh script though, since we'll have to put the Dockerfile for vitess/env in a subdirectory, and then it won't be allowed to "include" from the travis dir.
