### ISSUE TITLE
Does vitess support distributed transaction?

### ISSUE THREAD

**Issue by lihezh** [youtube/vitess#536]
Does vitess support distributed transaction when a ACID operation occured across more than two shards?

**Comment by sougou** [comment]
We currently don't support distributed transactions. It's on our roadmap. We're planning to use MySQL's XA API to achieve this. I still need to study the consistency guarantees of that API, especially with respect to replication. If all goes well, we'll have them soon.

**Comment by sougou** [comment]
http://vitess.io/user-guide/twopc.html
