### ISSUE TITLE
about use golang's client

### ISSUE THREAD

**Issue by mitiger** [youtube/vitess#537]
hi ,sougou:

when i use golang's client about vitess to save my data , there is a question appeared.
In the vttablet, the log show as follows:

W0331 16:59:06.763275 12975 sqlquery.go:297] error: missing bind var v3: Sql: "insert into t_login_history(f_account_id, f_ip, f_createtime) values (?,?,?)", BindVars: {v0: 1, v1: "localhost", v2: 1427792377099, #maxLimit: 10001, }

i just only hava 3 params , why it show me , missing bind var v3?

if i use another sql like :
insert into t_login_history(f_account_id, f_ip, f_createtime) values (1, "localhost", 123456), it will be ok.

is there something wrong about my code ?

**Comment by mitiger** [comment]
my code are as follows:

tx, err := db.Begin()
		if err != nil {
			return
		}

		stmt, err := tx.Prepare("insert into t_login_history(f_account_id, f_ip, f_createtime) values (?,?,?)")
		if err != nil {
			fmt.Println("-----> stmt error:", err)
			return
		}

		_, err = stmt.Exec(1, "localhost", time.Now().UnixNano()/1000000)
		if err != nil {
			tx.Rollback()
			fmt.Println("---->> stmt exec error:", err)
			return
		}
		defer stmt.Close()
		tx.Commit()

**Comment by sougou** [comment]
This is most likely a bug on my go client. Let me confirm. If so, I'll have a fix out very soon.

**Comment by sougou** [comment]
I just submitted a fix. Can you try again?

**Comment by mitiger** [comment]
should i rebuild vttablet  , and restart it?

**Comment by sougou** [comment]
Yes. My fix went in https://github.com/youtube/vitess/pull/539

**Comment by mitiger** [comment]
ok, i just test it . Error does not appear again. 
thank you .
