### ISSUE TITLE
Does vitess support some common features for MySQL?

### ISSUE THREAD

**Issue by Juckey** [youtube/vitess#540]
Does vitess support some common features for MySQL as follows:
1、rewriteBatchedStatements=true
2、useServerPrepStmts=true
3、correlation sql operations such as:join、paging、sort、subquery
4、BLOB、BINARY、VARBINARY
5、SAVEPOINT operation
6、SET statement
7、update existed column value for sharded table

**Comment by sougou** [comment]
1,2. It looks like some of these settings are related to the Java API. We currently don't have an officially good API yet (we do have some experimental ones you can try). I'd be very surprised if what we have now supports those settings.
3. We support join, paging (limit clauses), sorts and subqueries, as long as they're targeting a single shard.
4. We support blob, binary & varbinary.
5. SAVEPOINT is not supported yet.
6. We allow SET statements that we just pass through to MySQL, but we haven't used them ourselves. So, we don't know what effect they'll have.
7. Not sure what the question is. We support update, delete and insert statements, but they're restricted to a single shard per statement.

**Comment by gigatexal** [comment]
+1 to hoping we get savepoints.
```
InternalError: (pymysql.err.InternalError) (1105, u'vtgate: http://vtgate-zone1-7c9f75979b-fbv2f:15001/: unrecognized statement: SAVEPOINT sa_savepoint_1') [SQL: u'SAVEPOINT sa_savepoint_1'] (Background on this error at: http://sqlalche.me/e/2j85)
```
