### ISSUE TITLE
May auto_increment column cause some problems while using vitess?

### ISSUE THREAD

**Issue by Juckey** [youtube/vitess#544]

**Comment by sougou** [comment]
It depends on your setup. If you're unsharded, then it's no problem. But if you have a sharded database and want a globally unique auto_increment, then you obviously can't use MySQL's autoinc directly.
There is a way to get the effect of a globally unique auto increment using the V3 API. I've shown how to do it here: https://groups.google.com/forum/#!searchin/vitess/auto$20increment/vitess/EcUB0mIrLN4/b49SZyOLLCkJ.
