### ISSUE TITLE
go/stats/influxdbbackend/influxdb_backend.go:40: undefined: client.ClientConfig

### ISSUE THREAD

**Issue by winkyao** [youtube/vitess#599]
I follow the instructions in GetStarted:

when I make build, there are wrongs:
```
# github.com/youtube/vitess/go/stats/influxdbbackend
go/stats/influxdbbackend/influxdb_backend.go:40: undefined: client.ClientConfig
go/stats/influxdbbackend/influxdb_backend.go:60: undefined: client.Series
go/stats/influxdbbackend/influxdb_backend.go:62: undefined: client.Series
go/stats/influxdbbackend/influxdb_backend.go:73: backend.client.WriteSeries undefined (type *client.Client has no field or method WriteSeries)
```

it seems like the Influxdb has been making lots of changes lately.

**Comment by alainjobart** [comment]
We are using godep for the influx db client, so this should actually use the version that is submitted under Godeps/_workspace/src/github.com/influxdb/influxdb/client/

Which command were you running that fails? We probably forgot to prefix one command with 'godep'...
