### ISSUE TITLE
Split library code into smaller repositories?

### ISSUE THREAD

**Issue by augustoroman** [youtube/vitess#620]
The libraries made available through this project are awesome.  It's a bit cumbersome to use them, though, due to the size of the repo.  For example, importing the cache go library requires cloning the entire 68MB repo for a few KB of code.  Splitting off go/\* (excepting go/vt) into a separate repo would result in only a single additional repository but provide the bulk of the benefit in terms of size reduction.

**Comment by enisoc** [comment]
It sounds nice, but I'm worried it would cause more trouble than it's worth. We'd lose the ability to update both trees in a single commit or pull request. We'd have to use either "go get" or godep to import our own changes, each of which has its issues in general for Go dependency management. If the only benefit is reducing the data size of a clone, it doesn't seem worth it to me.

As a compromise, maybe we could copy out the libs into a fresh repo, but leave them frozen and keep working in this repo. But then, you could just do that yourself - make a pseudo-fork that copies the libs but not the history.

**Comment by yaoshengzhe** [comment]
I have feeling it is better to move these independent go libs into a separate repo at some point. So that go folks could utilize them to build great applications. It's worth the effort, like Guava guys did. In the meanwhile, Vitess could have its own libs and developers could sync the changes manually, so you still have the ability to update change in a single commit.

**Comment by enisoc** [comment]
As articulated by @joshk0 in #819, there is another argument for doing this besides the size of the repo, which to me is just the price we pay for using Git. Basically he said it's more about discoverability - if we clearly advertise that these are general-purpose libraries, more people will use and hopefully contribute to them.

It's starting to sound good to me, but I'd like to see where the [vendoring discussion](https://groups.google.com/d/msg/golang-dev/nMWoEAG55v8/iJGgur7W_SEJ) goes before doing a big migration. Basically they're trying to get the Go community to agree on a single convention for doing vendoring.

**Comment by keunwoo** [comment]
Golang vendoring is no longer experimental as of 1.6.
https://golang.org/doc/go1.6
Any further thoughts on this issue?

**Comment by enisoc** [comment]
We do use native Go vendoring for all external dependencies now, and we're reasonably satisfied with it. One question that remains is what level of granularity to use for breaking out packages: (1) separate repository per package (e.g. github.com/youtube/cgzip), or (2) a single break-out repository for non-vitess packages (a la https://github.com/dropbox/godropbox).

**Comment by keunwoo** [comment]
IMO from a client's perspective the ideal granularity would be close to (1), although you might try to group closely related functionality together (e.g. "cacheservice" and "memcache"). It's rare that users want to pull a whole grab bag of utility code into their project.

**Comment by enisoc** [comment]
That's a good point, although logistically I'm worried that `github.com/youtube` may not be the right namespace in which to dump ~30 small Go packages (whereas a `github.com/dropbox/godropbox`-style repository would be an easier sell). I'll bring it up with the team and see what they say.

**Comment by sougou** [comment]
This issue is old. Looks like we're sticking to the default decision of status-quo.
