### ISSUE TITLE
vttablet error : open too many files

### ISSUE THREAD

**Issue by mitiger** [youtube/vitess#628]
when use vitess a few times , vttablet will break off.
the log shows : open too many files.

what's wrong for me?

**Comment by sougou** [comment]
The default fd limit is usually not enough. You should change it to a large value, like 100,000. Some instructions here: http://www.cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files/.

**Comment by mitiger** [comment]
thank you  sougou .
i change the fd from 1024 to 65535 , and will try again.

**Comment by rushiagr** [comment]
Since this is atleast the second time someone has this same issue, should we make a mention of this in our docs?

**Comment by sougou** [comment]
@enisoc where would be a good place to mention this?

**Comment by enisoc** [comment]
I vote for putting it in an FAQ. It doesn't seem to be universally necessary to change the default. For example, on my GCE micro instance running Ubuntu, the default is apparently well over 100K.

**Comment by yaoshengzhe** [comment]
I think it is worth to mention check fd limits on your machine and it is better to give a suggested number (e.g. 65536) from vitess side. 

e.g. HBase mentions that in its book.
See section "Limits on Number of Files and Processes (ulimit) (http://hbase.apache.org/book.html )
