### ISSUE TITLE
Clarification required in docs regarding being able to run Vitess in non-GCE environments

### ISSUE THREAD

**Issue by rushiagr** [youtube/vitess#734]
The 'getting started' page makes it look like Vitess only works with GCE/Kubernetes. I think it would be great if we add a sentence saying something like 'You can still use Vitess in a non-GCE environment, go <hyperlink>here</hyperlink> for more details'.

**Comment by enisoc** [comment]
The [Getting Started](http://vitess.io/getting-started/) page now has a left nav bar that links to the non-Kubernetes version of the guide.
