### ISSUE TITLE
Are there any plans to support Consul?

### ISSUE THREAD

**Issue by c4milo** [youtube/vitess#816]
As an alternative to etcd or zookeeper.

**Comment by enisoc** [comment]
We don't have any plans related to Consul right now. If you just mean to incorporate Vitess as a service in Consul, so other apps can use Consul to connect to Vitess, that should be pretty straightforward for someone who understands both Consul and Vitess. If you're interested in trying it out, we'd be happy to help with the latter. :)

**Comment by c4milo** [comment]
I meant as an alternative to etcd and zookeeper to keep topology state and any distributed lock.

**Comment by enisoc** [comment]
Ah that should also be straightforward with our pluggable architecture, although we don't have any plans to do it ourselves for Consul.

Essentially you would need to make a plugin similar to [etcdtopo](https://github.com/youtube/vitess/tree/master/go/vt/etcdtopo) to satisfy the [topo.Server](http://godoc.org/github.com/youtube/vitess/go/vt/topo#Server) interface.

It mostly just consists of various get, set, and atomic update calls. Let us know if you're interested in contributing a plugin and we'll be happy to offer more guidance.

**Comment by dropje86** [comment]
I would also love to see Consul support for the Topology and distributed locking.

**Comment by alainjobart** [comment]
Consul support for server version 0.7.2 is being added in this PR:
https://github.com/youtube/vitess/pull/2434

**Comment by michael-berlin** [comment]
Said pull request is merged and Consul support is properly documented as well: http://vitess.io/user-guide/topology-service.html#consul-consul-implementation

Therefore I'm closing this issue now.
