### ISSUE TITLE
Fork out cgzip, and possibly other goodies, to their own projects

### ISSUE THREAD

**Issue by joshk0** [youtube/vitess#819]
Hey guys, cgzip is a pretty simple and effective compress/gzip implementation that has many uses beyond Vitess. Would you be up for splitting it out into its own github project so it could be consumed independently? No need to clone the whole repo, or as I'm sure many will do, copy a random revision of the files into their own repos.

**Comment by enisoc** [comment]
We've considered this in #620 but never came to a consensus. To me it seemed like the only benefit was saving people a few dozen megabytes of disk space, while the cost was additional development friction.

On the other hand, everyone else seems to disagree with me, so maybe I'm missing something. I'm willing to be convinced if someone can explain how being in a separate repo will help developers use our libs, other than by helping their computers do a little less work. If it's just a choice between the computers doing more work and the developers doing more work, I'd rather make the computers do it. :)

**Comment by joshk0** [comment]
As someone coming to Go recently from other programming languages, I'll say this: performant versions of core libraries deserve their own chunk of the ecosystem, if not a place in the standard library. Having these at hand, and not hidden away in the corner of some other package, improves the quality of the language by not giving people any reason to reinvent the wheel.

Imagine that Go is a hardware store. You browse around for pieces of tubing, PVC, brackets, screws, two by fours to piece together to complete your project. You need only one more specific thing to finish the job, but it's in one of those silly shrinkwrapped toolboxes where you have to buy the whole thing for $99.99, pick what you want out, and let the rest of it rot in the garage.

Obviously, in this allegory, vitess is the shrinkwrapped toolbox and cgzip is the Useful Tool. :)

Just my opinion.

**Comment by enisoc** [comment]
That makes sense. I think I'm coming around, but let's merge this discussion back to #620 since that one came first.
