### ISSUE TITLE
'./bootstrap.sh' cannot find 'launchpad.net/gozk/zookeeper' at third_party/go

### ISSUE THREAD

**Issue by tvaillancourt** [youtube/vitess#838]
Hey guys,

I am in the process of building RPMs of Vitess for easy deployment. During troubleshooting I noticed that the "go install launchpad.net/gozk/zookeeper" command was failing to find the source code under the third_party/go dir of the vitess github checkout.

It turns out 'go install' always expects the path to the source code to start with the parent dir 'src', so I was able to fix the problem with this symlink, effectively tricking 'go install' into finding the right path:

ln -nfs src/github.com/youtube/vitess/third_party/go/launchpad.net src/github.com/youtube/vitess/third_party/go/src/launchpad.net

Has anyone else encountered this issue?

Secondly, is anyone else working on packaging vitess into RPMs? I am happy to contribute what I'm doing to this awesome project in thanks for the great code! :)

Cheers,

Tim Vaillancourt

**Comment by tvaillancourt** [comment]
Correction, here are the exact lines I use to fix:

# Hack to fix wrong path for gozk/zookeeper:
mkdir -p $VITESS_BASE/third_party/go/src
ln -vs $VITESS_BASE/third_party/go/launchpad.net $VITESS_BASE/third_party/go/src/launchpad.net

Cheers,

Tim Vaillancourt

**Comment by tvaillancourt** [comment]
Whoops, I think I've made a mistake here. I will close for now.

Tim

**Comment by enisoc** [comment]
You're right that the "go install" command can't find gozk in our third_party dir. In bootstrap.sh, we try to get around this by making a symlink similar to what you did, except we root it at a higher level:

``` sh
ln -nfs $VTTOP/third_party/go/launchpad.net $VTROOT/src
```

Which expands to something like:

``` sh
ln -nfs ~/src/github.com/youtube/vitess/third_party/go/launchpad.net ~/src
```

That way we can have a single GOPATH (in this case `GOPATH=$HOME`) that finds both.

Hope that helps. If you get it working, we'd be happy to accept a contribution of packaging configs. :)

**Comment by tvaillancourt** [comment]
Hi enisoc, thanks!

Yes, it does look like bootstrap.sh is already doing this symlink for you but somehow when my build was a bit broken I had to add it myself also, but now it work without my fix. I guess an env variable was probably not set earlier in my experimentation.

Great, I'd love to make it easier for people to get started with vitess. You'll hear more from me soon!

Tim
