### ISSUE TITLE
how to  add/remove a tablet to an existing tablet Cluster

### ISSUE THREAD

**Issue by mitiger** [youtube/vitess#868]
hi, all:

i create a tablet cluster, and create tables in it. now, i wont to add a new tablet as a slave in it , how to do?

**Comment by enisoc** [comment]
The way we do this is to configure the tablets for backup/restore, usually to a network drive. Then new tablets will automatically restore from the latest backup and then connect to the master and catch up on replication.

We hadn't yet configured our example scripts to set that up. I've just now modified our local cluster example to support that, in PR #871.

If you pull after that commit, you can try the following:

```
# Bring up the local example as described in http://vitess.io/getting-started/local-instance.html
./zk-up.sh
./vtctld-up.sh
./vttablet-up.sh
./vtgate-up.sh

# Initialize the keyspace.
vtctlclient -server localhost:15000 RebuildKeyspaceGraph test_keyspace
vtctlclient -server localhost:15000 InitShardMaster -force test_keyspace/0 test-0000000100
vtctlclient -server localhost:15000 ApplySchema -sql "$(cat create_test_table.sql)" test_keyspace

# Insert a row.
./client.sh --server=localhost:15001

# Take a backup from one of the replicas.
vtctlclient -server localhost:15000 Backup test-0000000102

# Insert another row after the backup.
./client.sh --server=localhost:15001

# Bring up a fourth tablet.
# It will automatically restore from backup and then catch up on replication.
./vttablet-up.sh 3

# Check that all the data is there on the new tablet.
vtctlclient -server localhost:15000 ExecuteFetchAsDba test-0000000103 'SELECT * FROM test_table'
```

**Comment by mitiger** [comment]
@enisoc 
thank you ,  i try the new vttablet.sh.  and everything is ok.

but  i don't know how to remove a vttablet from the existing cluster??

**Comment by enisoc** [comment]
To remove a tablet, you can do something like this:

```
# Remove the tablet from serving.
vtctlclient -server localhost:15000 ScrapTablet -force test-0000000102
# Delete the tablet record.
vtctlclient -server localhost:15000 DeleteTablet test-0000000102
```

Then you can just kill the corresponding vttablet process. If you then restart the process with the same flags, it will re-add itself to serving.

**Comment by mitiger** [comment]
thank you very much.
